/**
 * Shared rendering helpers for "snapshot" codegens — tenant reference data
 * that is stable for the workspace lifetime (roles, permission groups, org
 * hierarchy, org levels). Unlike entities/saved-queries, these aren't
 * type-deriving: we fetch a JSON array once at cold-boot and emit it as a
 * typed const + a greppable markdown catalog so the agent can reference real
 * tenant values (role ids, org codes, level names) without a runtime call.
 *
 * These are NOT runtime hooks by design: the data doesn't change within a
 * session, so a baked snapshot avoids an extra network round-trip and lets
 * the agent see concrete values at generation time.
 *
 * Extracted here (not inline in scripts/) so the rendering is unit-testable
 * in the starter's vitest env.
 */

/** A single record in a snapshot (an opaque JSON object with string keys). */
export type SnapshotRecord = Record<string, unknown>;

export interface SnapshotSpec {
  /** Const + type stem, e.g. "Roles" → `ROLES`, `RolesRecord`. */
  pascal: string;
  /** SCREAMING_SNAKE const name, e.g. "ROLES". */
  constName: string;
  /** Human title for the catalog/header, e.g. "Roles". */
  title: string;
  /** Source endpoint (for the AUTO-GENERATED header comment). */
  source: string;
  /** Which script emits this (for the header comment). */
  script: string;
  /** Columns to show in the catalog table (in order). Falls back to all keys. */
  catalogColumns?: string[];
}

/** Stable JSON.stringify with sorted keys so output is deterministic. */
function stableStringify(value: unknown, indent = 2): string {
  const seen = new WeakSet();
  function norm(v: unknown): unknown {
    if (v === null || typeof v !== 'object') return v;
    if (seen.has(v as object)) return undefined;
    seen.add(v as object);
    if (Array.isArray(v)) return v.map(norm);
    const obj = v as Record<string, unknown>;
    const out: Record<string, unknown> = {};
    for (const k of Object.keys(obj).sort()) out[k] = norm(obj[k]);
    return out;
  }
  return JSON.stringify(norm(value), null, indent);
}

/**
 * Render the typed `<name>.generated.ts` for a snapshot:
 *   export interface <Pascal>Record { [key: string]: unknown }
 *   export const <CONST>: ReadonlyArray<<Pascal>Record> = [ … ] as const;
 *   export const <CONST>_COUNT = N;
 */
export function renderSnapshotTs(
  spec: SnapshotSpec,
  records: SnapshotRecord[],
): string {
  const lines: string[] = [];
  lines.push(`/* eslint-disable */`);
  lines.push(`// AUTO-GENERATED by ${spec.script} - do not edit by hand.`);
  lines.push(`// Source: ${spec.source}`);
  lines.push(
    `// Tenant reference snapshot — regenerated on every workspace bootstrap.`,
  );
  lines.push(``);
  lines.push(
    `/** One ${spec.title} record (shape is tenant-defined; keys are open). */`,
  );
  lines.push(
    `export interface ${spec.pascal}Record { [key: string]: unknown }`,
  );
  lines.push(``);
  lines.push(`/** All ${spec.title} for this tenant (snapshot at bootstrap). */`);
  if (records.length === 0) {
    lines.push(
      `export const ${spec.constName}: ReadonlyArray<${spec.pascal}Record> = [];`,
    );
  } else {
    lines.push(
      `export const ${spec.constName}: ReadonlyArray<${spec.pascal}Record> = ${stableStringify(
        records,
      )} as const;`,
    );
  }
  lines.push(``);
  lines.push(`export const ${spec.constName}_COUNT = ${records.length};`);
  lines.push(``);
  return lines.join('\n');
}

function mdCell(value: unknown): string {
  if (value === null || value === undefined) return '';
  if (typeof value === 'object') return '`{…}`';
  return String(value).replace(/\|/g, '\\|').replace(/\r?\n/g, ' ');
}

/**
 * Render the agent-facing markdown catalog: a header + a table of the
 * snapshot's records limited to `catalogColumns` (or all discovered keys).
 */
export function renderSnapshotCatalog(
  spec: SnapshotSpec,
  records: SnapshotRecord[],
): string {
  const header =
    `# ${spec.title} Catalog\n\n` +
    `Auto-generated by \`${spec.script}\`. Tenant reference snapshot from\n` +
    `\`${spec.source}\`. Stable for the workspace lifetime — use these real\n` +
    `values (ids, codes, names) when generating code; do not invent them.\n\n`;

  if (records.length === 0) {
    return (
      header +
      `_No ${spec.title} available. Either the tenant has none, or the\n` +
      `fetch env vars were unset when this was regenerated._\n`
    );
  }

  // Determine columns.
  let columns = spec.catalogColumns;
  if (!columns || columns.length === 0) {
    const keys = new Set<string>();
    for (const r of records) for (const k of Object.keys(r)) keys.add(k);
    columns = [...keys];
  }

  const head = `| ${columns.join(' | ')} |`;
  const sep = `| ${columns.map(() => '---').join(' | ')} |`;
  const rows = records.map(
    (r) => `| ${columns!.map((c) => mdCell(r[c])).join(' | ')} |`,
  );

  return `${header}${head}\n${sep}\n${rows.join('\n')}\n`;
}
