// AUTO-GENERATED by scripts/fetch-entities.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/entity
// Tenant scope: see TENANT_ID used at generation time.

import type { CardTemplate } from '@/types/entities/aswathtestapp_6a67823a8fa7215710927dbc/card_template';
import type { ItemRevision } from '@/types/entities/aswathtestapp_6a67823a8fa7215710927dbc/item_revision';

/**
 * Card Spec
 * The card itself (JSON-first spec + typed columns), the Fabric.js artwork document for both faces, and the Jiffy Drive file id of the exported print PDF. The front preview is Json, not Text, because a PNG data URL blows past the 255 character check constraint Phoenix puts on every Text column.
 */
export interface CardSpec {
  /** Id — PK */
  id: string;
  /** Artwork Back — Fabric.js canvas document for the back face, serialised with toJSON. */
  artwork_back?: Record<string, unknown>;
  /** Artwork Front — Fabric.js canvas document for the front face, serialised with toJSON. */
  artwork_front?: Record<string, unknown>;
  /** Artwork Pdf At — When the PDF was last exported and uploaded. */
  artwork_pdf_at?: string;
  /** Artwork Pdf File Id — Jiffy Drive file id of the exported print-ready PDF. */
  artwork_pdf_file_id?: string;
  /** Artwork Pdf Name — File name of the exported PDF as stored in Jiffy Drive. */
  artwork_pdf_name?: string;
  /** Artwork Preview — PNG data URL thumbnails, shaped {front, back}. Json because Text is capped at 255 characters. */
  artwork_preview?: Record<string, unknown>;
  /** Artwork Updated At — When the artwork document was last saved. */
  artwork_updated_at?: string;
  /** Back Color Code — Back-face color code */
  back_color_code?: string;
  /** Bin — open-loop only */
  bin?: string;
  /** Card Brand — catalog - drives brand review routing */
  card_brand?: string;
  /** Finish — Surface finish */
  finish?: string;
  /** Front Color Code — Front-face color code */
  front_color_code?: string;
  /** Ica — ICA number (open-loop) */
  ica?: string;
  /** Item Rev Id — FK -> ItemRevision */
  item_rev_id?: ItemRevision;
  /** Mag Coercivity — Magnetic stripe coercivity */
  mag_coercivity?: string;
  /** Mag Stripe — Whether the card has a magnetic stripe */
  mag_stripe?: boolean;
  /** Mag Tracks — Encoded magnetic tracks */
  mag_tracks?: string;
  /** Preprint Bin — Pre-printed BIN block */
  preprint_bin?: string;
  /** Scratch Off — Whether a scratch-off panel is present */
  scratch_off?: boolean;
  /** Shape — Physical card shape */
  shape?: string;
  /** Sig Panel — Signature panel specification */
  sig_panel?: string;
  /** Spec — Full card spec captured as JSON (JSON-first) */
  spec?: Record<string, unknown>;
  /** Substrate — Card substrate/material */
  substrate?: string;
  /** Template Ref — FK -> card_template. The template this card was started from, if any. */
  template_ref?: CardTemplate;
  /** Thickness Mil — Card thickness in mils */
  thickness_mil?: number;
}

export const CARD_SPEC_APP_KEY = "aswathtestapp_6a67823a8fa7215710927dbc";

export type CardSpecSchema = { 'card_spec': CardSpec };

/**
 * Field-level validation declared in Phoenix for `card_spec`.
 * Use as DEFAULT UI constraints when building a form for this entity
 * (mark required fields, set maxLength / min / max, apply regex / oneOf).
 * Only fields that are required or carry a constraint are listed.
 */
export const CARD_SPEC_FIELD_CONSTRAINTS = {
  id: { required: true },
} as const;
