// AUTO-GENERATED by scripts/fetch-entities.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/entity
// Tenant scope: see TENANT_ID used at generation time.

import type { Party } from '@/types/entities/aswathtestapp_6a67823a8fa7215710927dbc/party';

/**
 * Item
 * Anything the business can define and later buy, sell or make.
 */
export interface Item {
  /** Id — PK */
  id: string;
  /** Component Role — Pricing component role: card, carrier, features or setup. Drives which PricingTemplate margin row applies. */
  component_role?: string;
  /** Item Type — Item type, from the item-type catalog */
  item_type?: string;
  /** Name — Item display name */
  name?: string;
  /** Owner Party Id — FK -> Party */
  owner_party_id?: Party;
}

export const ITEM_APP_KEY = "aswathtestapp_6a67823a8fa7215710927dbc";

export type ItemSchema = { 'item': Item };

/**
 * Field-level validation declared in Phoenix for `item`.
 * Use as DEFAULT UI constraints when building a form for this entity
 * (mark required fields, set maxLength / min / max, apply regex / oneOf).
 * Only fields that are required or carry a constraint are listed.
 */
export const ITEM_FIELD_CONSTRAINTS = {
  id: { required: true },
} as const;
