// AUTO-GENERATED by scripts/fetch-entities.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/entity
// Tenant scope: see TENANT_ID used at generation time.

import type { Orders } from '@/types/entities/aswathtestapp_6a67823a8fa7215710927dbc/orders';

/**
 * Margin Override
 * A CS-entered, per-order margin override for one component role. Does not change the client's pricing template. Every override carries a mandatory written reason.
 */
export interface MarginOverride {
  /** ID */
  id: string;
  /** Active — False once superseded by a later override or reverted to template. */
  active?: boolean;
  /** Component Role — card, carrier, features or setup */
  component_role?: string;
  /** Created At */
  created_at?: string;
  /** From Bps — The template (or previously committed) margin this override replaced, in basis points. */
  from_bps?: number;
  /** Margin Bps — Overridden margin in basis points. 1500 = 15%. */
  margin_bps?: number;
  /** Order Ref — FK -> orders. The order this override applies to. Named order_ref because the DynQL filter parser treats 'order' as a reserved word. */
  order_ref?: Orders;
  /** Reason — Mandatory free-text justification. An override cannot be saved without one. */
  reason?: string;
  /** Scenario — The scenario active when the override was made: standard, rfp or premium. */
  scenario?: string;
}

export const MARGIN_OVERRIDE_APP_KEY = "aswathtestapp_6a67823a8fa7215710927dbc";

export type MarginOverrideSchema = { 'margin_override': MarginOverride };

/**
 * Field-level validation declared in Phoenix for `margin_override`.
 * Use as DEFAULT UI constraints when building a form for this entity
 * (mark required fields, set maxLength / min / max, apply regex / oneOf).
 * Only fields that are required or carry a constraint are listed.
 */
export const MARGIN_OVERRIDE_FIELD_CONSTRAINTS = {
  id: { required: true },
} as const;
