// AUTO-GENERATED by scripts/fetch-entities.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/entity
// Tenant scope: see TENANT_ID used at generation time.

import type { Party } from '@/types/entities/aswathtestapp_6a67823a8fa7215710927dbc/party';

/**
 * Price History
 * Observed price history.
 */
export interface PriceHistory {
  /** Id — PK */
  id: string;
  /** Observed At — When observed */
  observed_at?: string;
  /** Party — FK -> Party */
  party?: Party;
  /** Signature Hash — Spec fingerprint */
  signature_hash?: string;
  /** Tier Qty — Quantity tier */
  tier_qty?: number;
  /** Unit Cost — Observed unit cost */
  unit_cost?: number;
}

export const PRICE_HISTORY_APP_KEY = "aswathtestapp_6a67823a8fa7215710927dbc";

export type PriceHistorySchema = { 'price_history': PriceHistory };

/**
 * Field-level validation declared in Phoenix for `price_history`.
 * Use as DEFAULT UI constraints when building a form for this entity
 * (mark required fields, set maxLength / min / max, apply regex / oneOf).
 * Only fields that are required or carry a constraint are listed.
 */
export const PRICE_HISTORY_FIELD_CONSTRAINTS = {
  id: { required: true },
} as const;
