// AUTO-GENERATED by scripts/fetch-entities.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/entity
// Tenant scope: see TENANT_ID used at generation time.

import type { ItemRevision } from '@/types/entities/aswathtestapp_6a67823a8fa7215710927dbc/item_revision';
import type { OrderLine } from '@/types/entities/aswathtestapp_6a67823a8fa7215710927dbc/order_line';

/**
 * RFE Line Row
 * One line to bid on.
 */
export interface RfeLineRow {
  /** Id — PK */
  id: string;
  /** Item Rev Id — FK -> Item Revision */
  item_rev_id?: ItemRevision;
  /** Order Line Id — FK -> Order Line */
  order_line_id?: OrderLine;
  /** Qty — Quantity to bid on */
  qty?: number;
  /** Rfe Id — The parent RFE id (plain UUID) */
  rfe_id?: string;
}

export const RFE_LINE_ROW_APP_KEY = "aswathtestapp_6a67823a8fa7215710927dbc";

export type RfeLineRowSchema = { 'rfe_line_row': RfeLineRow };

/**
 * Field-level validation declared in Phoenix for `rfe_line_row`.
 * Use as DEFAULT UI constraints when building a form for this entity
 * (mark required fields, set maxLength / min / max, apply regex / oneOf).
 * Only fields that are required or carry a constraint are listed.
 */
export const RFE_LINE_ROW_FIELD_CONSTRAINTS = {
  id: { required: true },
} as const;
