// AUTO-GENERATED by scripts/fetch-entities.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/entity
// Tenant scope: see TENANT_ID used at generation time.

import type { Rfe } from '@/types/entities/aswathtestapp_6a67823a8fa7215710927dbc/rfe';

/**
 * RFE Response
 */
export interface RfeResponse {
  /** ID */
  id: string;
  /** Commits To Delivery */
  commits_to_delivery?: boolean;
  /** Lead Time Weeks */
  lead_time_weeks?: number;
  /** RFE */
  rfe?: Rfe;
  /** Round */
  round?: number;
  /** Status */
  status?: string;
  /** Submitted At */
  submitted_at?: string;
  /** Supplier Quote No */
  supplier_quote_no?: string;
  /** Validity Until */
  validity_until?: string;
}

export const RFE_RESPONSE_APP_KEY = "aswathtestapp_6a67823a8fa7215710927dbc";

export type RfeResponseSchema = { 'rfe_response': RfeResponse };

/**
 * Field-level validation declared in Phoenix for `rfe_response`.
 * Use as DEFAULT UI constraints when building a form for this entity
 * (mark required fields, set maxLength / min / max, apply regex / oneOf).
 * Only fields that are required or carry a constraint are listed.
 */
export const RFE_RESPONSE_FIELD_CONSTRAINTS = {
  id: { required: true },
} as const;
