// AUTO-GENERATED by scripts/fetch-entities.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/entity
// Tenant scope: see TENANT_ID used at generation time.

import type { RfeLineRow } from '@/types/entities/aswathtestapp_6a67823a8fa7215710927dbc/rfe_line_row';

/**
 * RFE Line Tier
 */
export interface RfeLineTier {
  /** ID */
  id: string;
  /** RFE Line */
  rfe_line?: RfeLineRow;
  /** Tier Qty */
  tier_qty?: number;
}

export const RFE_LINE_TIER_APP_KEY = "aswathtestapp_6a67823a8fa7215710927dbc";

export type RfeLineTierSchema = { 'rfe_line_tier': RfeLineTier };

/**
 * Field-level validation declared in Phoenix for `rfe_line_tier`.
 * Use as DEFAULT UI constraints when building a form for this entity
 * (mark required fields, set maxLength / min / max, apply regex / oneOf).
 * Only fields that are required or carry a constraint are listed.
 */
export const RFE_LINE_TIER_FIELD_CONSTRAINTS = {
  id: { required: true },
} as const;
