// AUTO-GENERATED by scripts/fetch-entities.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/entity
// Tenant scope: see TENANT_ID used at generation time.

import type { TqSubTaskDefinition } from '@/types/entities/aswathtestapp_6a67823a8fa7215710927dbc/tq_sub_task_definition';

/**
 * TQ Definition
 * [task-queue] A task/process template.
 */
export interface TqDefinition {
  /** Id — PK */
  id: string;
  /** Created At */
  created_at?: string;
  /** Created By */
  created_by?: unknown;
  /** Last Modified At */
  last_modified_at?: string;
  /** Last Modified By */
  last_modified_by?: unknown;
  /** Name — Process name, e.g. 'Gift Card Order' */
  name?: string;
  /** Tasks — 1:N -> stages of this task */
  tasks?: TqSubTaskDefinition[];
}

export const TQ_DEFINITION_APP_KEY = "aswathtestapp_6a67823a8fa7215710927dbc";

export type TqDefinitionSchema = { 'tq_definition': TqDefinition };

/**
 * Field-level validation declared in Phoenix for `tq_definition`.
 * Use as DEFAULT UI constraints when building a form for this entity
 * (mark required fields, set maxLength / min / max, apply regex / oneOf).
 * Only fields that are required or carry a constraint are listed.
 */
export const TQ_DEFINITION_FIELD_CONSTRAINTS = {
  id: { required: true },
} as const;
