// AUTO-GENERATED by scripts/fetch-entities.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/entity
// Tenant scope: see TENANT_ID used at generation time.

import type { TqInstance } from '@/types/entities/aswathtestapp_6a67823a8fa7215710927dbc/tq_instance';
import type { TqStateDefinition } from '@/types/entities/aswathtestapp_6a67823a8fa7215710927dbc/tq_state_definition';
import type { TqStateInstance } from '@/types/entities/aswathtestapp_6a67823a8fa7215710927dbc/tq_state_instance';
import type { TqSubTaskDefinition } from '@/types/entities/aswathtestapp_6a67823a8fa7215710927dbc/tq_sub_task_definition';

/**
 * TQ Sub Task Instance
 * [task-queue] A running sub-task, with its state history.
 */
export interface TqSubTaskInstance {
  /** Id — PK */
  id: string;
  /** Assignee — N:1 -> platform user who owns this stage */
  assignee?: unknown;
  /** Completed At — When reached final state */
  completed_at?: string;
  /** Created At */
  created_at?: string;
  /** Created By */
  created_by?: unknown;
  /** Current State — N:1 -> current state */
  current_state?: TqStateDefinition;
  /** Last Modified At */
  last_modified_at?: string;
  /** Last Modified By */
  last_modified_by?: unknown;
  /** Status History — 1:N -> state history */
  status_history?: TqStateInstance[];
  /** TQ Instance — N:1 -> TQ Instance */
  tq_instance?: TqInstance;
  /** TQ Sub Task Definition — N:1 -> Sub Task Definition */
  tq_sub_task_definition?: TqSubTaskDefinition;
}

export const TQ_SUB_TASK_INSTANCE_APP_KEY = "aswathtestapp_6a67823a8fa7215710927dbc";

export type TqSubTaskInstanceSchema = { 'tq_sub_task_instance': TqSubTaskInstance };

/**
 * Field-level validation declared in Phoenix for `tq_sub_task_instance`.
 * Use as DEFAULT UI constraints when building a form for this entity
 * (mark required fields, set maxLength / min / max, apply regex / oneOf).
 * Only fields that are required or carry a constraint are listed.
 */
export const TQ_SUB_TASK_INSTANCE_FIELD_CONSTRAINTS = {
  id: { required: true },
} as const;
