// AUTO-GENERATED by scripts/fetch-entities.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/entity
// Tenant scope: see TENANT_ID used at generation time.

import type { TqStateDefinition } from '@/types/entities/aswathtestapp_6a67823a8fa7215710927dbc/tq_state_definition';
import type { TqSubTaskInstance } from '@/types/entities/aswathtestapp_6a67823a8fa7215710927dbc/tq_sub_task_instance';

/**
 * TQ State Instance
 * [task-queue] History trail: one row per state entered.
 */
export interface TqStateInstance {
  /** Id — PK */
  id: string;
  /** Created At */
  created_at?: string;
  /** Created By */
  created_by?: unknown;
  /** Is Current — Whether current state */
  is_current?: boolean;
  /** Last Modified At */
  last_modified_at?: string;
  /** Last Modified By */
  last_modified_by?: unknown;
  /** TQ State Definition — N:1 -> state entered */
  tq_state_definition?: TqStateDefinition;
  /** TQ Sub Task Instance — N:1 -> Sub Task Instance */
  tq_sub_task_instance?: TqSubTaskInstance;
}

export const TQ_STATE_INSTANCE_APP_KEY = "aswathtestapp_6a67823a8fa7215710927dbc";

export type TqStateInstanceSchema = { 'tq_state_instance': TqStateInstance };

/**
 * Field-level validation declared in Phoenix for `tq_state_instance`.
 * Use as DEFAULT UI constraints when building a form for this entity
 * (mark required fields, set maxLength / min / max, apply regex / oneOf).
 * Only fields that are required or carry a constraint are listed.
 */
export const TQ_STATE_INSTANCE_FIELD_CONSTRAINTS = {
  id: { required: true },
} as const;
