// AUTO-GENERATED by scripts/fetch-saved-queries.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/saved-query
// Saved query: allocation_clear_order ("Clear allocations for an order")
// Type: dynamic  |  Single output: false  |  App: aswathtestapp_6a67823a8fa7215710927dbc
// Deletes every allocation and carve-out row for one order. Call this immediately before re-inserting the current set. Param: orderId.

import { apiManager } from '@/services/api-manager';
import { getDataHeaders } from '@/config/api-config';

/** Input parameters for `allocation_clear_order` (write — sent as a flat JSON body). */
export interface AllocationClearOrderInput {
  orderId: string;
}

/** Row returned by `allocation_clear_order` (write — the affected row's id). */
export interface AllocationClearOrderRow {
  id: string;
}

export const ALLOCATION_CLEAR_ORDER_NAME = "allocation_clear_order";
export const ALLOCATION_CLEAR_ORDER_IS_SINGLE = false as const;
export const ALLOCATION_CLEAR_ORDER_APP_KEY = "aswathtestapp_6a67823a8fa7215710927dbc";

/**
 * Execute the `allocation_clear_order` saved query. WRITE (delete).
 * Inputs are sent as a flat JSON body; returns the affected row(s).
 */
export async function executeAllocationClearOrder(
  input: AllocationClearOrderInput,
): Promise<AllocationClearOrderRow[]> {
  const headers = getDataHeaders(ALLOCATION_CLEAR_ORDER_APP_KEY || undefined);
  const response = await apiManager.post('data', "/saved-queries/allocation_clear_order/execute", input, headers);
  return response.data as AllocationClearOrderRow[];
}
