// AUTO-GENERATED by scripts/fetch-saved-queries.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/saved-query
// Saved query: card_variant_approve ("Approve or unapprove a variant")
// Type: dynamic  |  Single output: true  |  App: aswathtestapp_6a67823a8fa7215710927dbc
// Flips the approval flag on one variation. Send for quotes stays disabled until at least one is approved. Query-string params: variantId, approved (true or false), approvedAt.

import { apiManager } from '@/services/api-manager';
import { getDataHeaders } from '@/config/api-config';

/** Input parameters for `card_variant_approve` (write — sent as a flat JSON body). */
export interface CardVariantApproveInput {
  approved: string;
  approvedAt: string;
  variantId: string;
}

/** Row returned by `card_variant_approve` (write).
 *  (Unwrapped from the saved query's `card_variant` output.) */
export interface CardVariantApproveResult {
  /** ID */
  id: string;
  /** Approved */
  approved?: boolean;
  /** Approved At */
  approved_at?: string;
  /** Label */
  label?: string;
}

export const CARD_VARIANT_APPROVE_NAME = "card_variant_approve";
export const CARD_VARIANT_APPROVE_IS_SINGLE = true as const;
export const CARD_VARIANT_APPROVE_APP_KEY = "aswathtestapp_6a67823a8fa7215710927dbc";

/**
 * Execute the `card_variant_approve` saved query. WRITE (update).
 * Inputs are sent as a flat JSON body; returns the affected row(s).
 */
export async function executeCardVariantApprove(
  input: CardVariantApproveInput,
): Promise<CardVariantApproveResult[]> {
  const headers = getDataHeaders(CARD_VARIANT_APPROVE_APP_KEY || undefined);
  const response = await apiManager.post('data', "/saved-queries/card_variant_approve/execute", input, headers);
  return response.data as CardVariantApproveResult[];
}
