// AUTO-GENERATED by scripts/fetch-saved-queries.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/saved-query
// Saved query: card_spec_save ("Save card spec")
// Type: dynamic  |  Single output: true  |  App: aswathtestapp_6a67823a8fa7215710927dbc
// Updates one card_spec with the Specs attributes and the Fabric artwork. artworkPreview is now a JSON object shaped {front, back} holding PNG data URLs, because Text columns are capped at 255 characters and a data URL breaks that constraint. JSON body: cardSpecId, shape, substrate, thicknessMil, frontColorCode, backColorCode, finish, magStripe, magCoercivity, magTracks, sigPanel, scratchOff, cardBrand, spec, artworkFront, artworkBack, artworkPreview, artworkUpdatedAt.

import { apiManager } from '@/services/api-manager';
import { getDataHeaders } from '@/config/api-config';

/** Input parameters for `card_spec_save` (write — sent as a flat JSON body). */
export interface CardSpecSaveInput {
  artworkBack: string;
  artworkFront: string;
  artworkPreview: string;
  artworkUpdatedAt: string;
  backColorCode: string;
  cardBrand: string;
  cardSpecId: string;
  finish: string;
  frontColorCode: string;
  magCoercivity: string;
  magStripe: string;
  magTracks: string;
  scratchOff: string;
  shape: string;
  sigPanel: string;
  spec: string;
  substrate: string;
  thicknessMil: string;
}

/** Row returned by `card_spec_save` (write).
 *  (Unwrapped from the saved query's `card_spec` output.) */
export interface CardSpecSaveResult {
  /** Id */
  id?: string;
  /** Artwork Updated At */
  artwork_updated_at?: string;
  /** Finish */
  finish?: string;
  /** Shape */
  shape?: string;
  /** Substrate */
  substrate?: string;
  /** Thickness Mil */
  thickness_mil?: number;
}

export const CARD_SPEC_SAVE_NAME = "card_spec_save";
export const CARD_SPEC_SAVE_IS_SINGLE = true as const;
export const CARD_SPEC_SAVE_APP_KEY = "aswathtestapp_6a67823a8fa7215710927dbc";

/**
 * Execute the `card_spec_save` saved query. WRITE (update).
 * Inputs are sent as a flat JSON body; returns the affected row(s).
 */
export async function executeCardSpecSave(
  input: CardSpecSaveInput,
): Promise<CardSpecSaveResult[]> {
  const headers = getDataHeaders(CARD_SPEC_SAVE_APP_KEY || undefined);
  const response = await apiManager.post('data', "/saved-queries/card_spec_save/execute", input, headers);
  return response.data as CardSpecSaveResult[];
}
