// AUTO-GENERATED by scripts/fetch-saved-queries.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/saved-query
// Saved query: card_spec_create_v2 ("card_spec_create_v2")
// Type: common_table_expression  |  Single output: true  |  App: aswathtestapp_6a67823a8fa7215710927dbc
// JSON-BODY variant of card_spec_create — call with useSavedQueryMutation (flat JSON body), exactly like order_create, so free-text cardDescription containing commas is safe. Body: orderId, buyerPartyId, itemRevId (caller-generated UUID), cardName, cardDescription, qty.

import { apiManager } from '@/services/api-manager';
import { getDataHeaders } from '@/config/api-config';

/** Input parameters for `card_spec_create_v2` (write — sent as a flat JSON body). */
export interface CardSpecCreateV2Input {
  buyerPartyId: string;
  cardDescription: string;
  cardName: string;
  it: string;
  itemRevId: string;
  orderId: string;
  qty: string;
}

/** Row returned by `card_spec_create_v2` (write — the affected row's id). */
export interface CardSpecCreateV2Result {
  id: string;
}

export const CARD_SPEC_CREATE_V2_NAME = "card_spec_create_v2";
export const CARD_SPEC_CREATE_V2_IS_SINGLE = true as const;
export const CARD_SPEC_CREATE_V2_APP_KEY = "aswathtestapp_6a67823a8fa7215710927dbc";

/**
 * Execute the `card_spec_create_v2` saved query. WRITE (insert).
 * Inputs are sent as a flat JSON body; returns the affected row(s).
 */
export async function executeCardSpecCreateV2(
  input: CardSpecCreateV2Input,
): Promise<CardSpecCreateV2Result> {
  const headers = getDataHeaders(CARD_SPEC_CREATE_V2_APP_KEY || undefined);
  const response = await apiManager.post('data', "/saved-queries/card_spec_create_v2/execute", input, headers);
  return response.data as CardSpecCreateV2Result;
}
