// AUTO-GENERATED by scripts/fetch-saved-queries.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/saved-query
// Saved query: card_spec_pdf_save ("Save exported PDF reference")
// Type: dynamic  |  Single output: true  |  App: aswathtestapp_6a67823a8fa7215710927dbc
// Stores the Jiffy Drive file id of the exported print PDF against the card spec, after the browser has POSTed the PDF to /drive/internal/api/v1/files. JSON body: cardSpecId, pdfFileId, pdfName, pdfAt.

import { apiManager } from '@/services/api-manager';
import { getDataHeaders } from '@/config/api-config';

/** Input parameters for `card_spec_pdf_save` (write — sent as a flat JSON body). */
export interface CardSpecPdfSaveInput {
  cardSpecId: string;
  pdfAt: string;
  pdfFileId: string;
  pdfName: string;
}

/** Row returned by `card_spec_pdf_save` (write).
 *  (Unwrapped from the saved query's `card_spec` output.) */
export interface CardSpecPdfSaveResult {
  /** Id */
  id?: string;
  /** Artwork Pdf At */
  artwork_pdf_at?: string;
  /** Artwork Pdf File Id */
  artwork_pdf_file_id?: string;
  /** Artwork Pdf Name */
  artwork_pdf_name?: string;
}

export const CARD_SPEC_PDF_SAVE_NAME = "card_spec_pdf_save";
export const CARD_SPEC_PDF_SAVE_IS_SINGLE = true as const;
export const CARD_SPEC_PDF_SAVE_APP_KEY = "aswathtestapp_6a67823a8fa7215710927dbc";

/**
 * Execute the `card_spec_pdf_save` saved query. WRITE (update).
 * Inputs are sent as a flat JSON body; returns the affected row(s).
 */
export async function executeCardSpecPdfSave(
  input: CardSpecPdfSaveInput,
): Promise<CardSpecPdfSaveResult[]> {
  const headers = getDataHeaders(CARD_SPEC_PDF_SAVE_APP_KEY || undefined);
  const response = await apiManager.post('data', "/saved-queries/card_spec_pdf_save/execute", input, headers);
  return response.data as CardSpecPdfSaveResult[];
}
