// AUTO-GENERATED by scripts/fetch-saved-queries.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/saved-query
// Saved query: card_add ("Add a card")
// Type: dynamic  |  Single output: true  |  App: aswathtestapp_6a67823a8fa7215710927dbc
// Creates a new card in one call: the item, its revision 1, and an empty card_spec row ready for the Specs studio. The caller generates all three UUIDs so the ids are known without a read-back. component_role is always card, which the old card_spec_create_v2 failed to set. JSON body: cardSpecId, itemRevId, itemId, name, ownerPartyId.

import { apiManager } from '@/services/api-manager';
import { getDataHeaders } from '@/config/api-config';

/** Input parameters for `card_add` (write — sent as a flat JSON body). */
export interface CardAddInput {
  cardSpecId: string;
  itemId: string;
  itemRevId: string;
  name: string;
  ownerPartyId: string;
}

/** Row returned by `card_add` (write).
 *  (Unwrapped from the saved query's `card_spec` output.) */
export interface CardAddResult {
  /** Id */
  id?: string;
}

export const CARD_ADD_NAME = "card_add";
export const CARD_ADD_IS_SINGLE = true as const;
export const CARD_ADD_APP_KEY = "aswathtestapp_6a67823a8fa7215710927dbc";

/**
 * Execute the `card_add` saved query. WRITE (insert).
 * Inputs are sent as a flat JSON body; returns the affected row(s).
 */
export async function executeCardAdd(
  input: CardAddInput,
): Promise<CardAddResult> {
  const headers = getDataHeaders(CARD_ADD_APP_KEY || undefined);
  const response = await apiManager.post('data', "/saved-queries/card_add/execute", input, headers);
  return response.data as CardAddResult;
}
