// AUTO-GENERATED by scripts/fetch-saved-queries.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/saved-query
// Saved query: card_templates ("Card templates")
// Type: dynamic  |  Single output: false  |  App: aswathtestapp_6a67823a8fa7215710927dbc
// Active card artwork templates for the picker at the top of the design studio. No params.

import { apiManager } from '@/services/api-manager';
import { getDataHeaders } from '@/config/api-config';
import { parseSortExpression } from '@/hooks/saved-query-request';

/** Input parameters for `card_templates` (none declared). */
export type CardTemplatesInput = Record<string, never>;

/** Single row in the `card_templates` result set.
 *  (Unwrapped from the saved query's `card_template_list` output array.) */
export interface CardTemplatesRow {
  /** ID */
  id: string;
  /** Artwork Back */
  artwork_back?: Record<string, unknown>;
  /** Artwork Front */
  artwork_front?: Record<string, unknown>;
  /** Category */
  category?: string;
  /** Created At */
  created_at?: string;
  /** Description */
  description?: string;
  /** Name */
  name?: string;
  /** Spec — build parameters, keyed by card_spec column name. */
  spec?: Record<string, unknown>;
  /** Thumbnail */
  thumbnail?: string;
}

export const CARD_TEMPLATES_NAME = "card_templates";
export const CARD_TEMPLATES_IS_SINGLE = false as const;
export const CARD_TEMPLATES_APP_KEY = "aswathtestapp_6a67823a8fa7215710927dbc";

export interface ExecuteCardTemplatesOptions {
  /** Zero-based page index (body `page`, offset mode). */
  page?: number;
  /** Page size (body `page.size`). */
  pageSize?: number;
  /** Sort: comma-separated, `-` prefix for descending (e.g. 'status,-balance'). Body `sort`. */
  sort?: string;
  /** CEL filter expression (body `filterExpression`). */
  filter?: string;
}

/**
 * Execute the `card_templates` saved query. Read-only.
 */
export async function executeCardTemplates(
  input?: CardTemplatesInput,
  options?: ExecuteCardTemplatesOptions,
): Promise<CardTemplatesRow[]> {
  const headers = getDataHeaders(CARD_TEMPLATES_APP_KEY || undefined);
  const params = new URLSearchParams();
  if (input) {
    for (const [k, v] of Object.entries(input)) {
      if (v === undefined || v === null) continue;
      if (k === '_page' || k === '_size' || k === '_sort' || k === '_filter') continue;
      params.set(k, String(v));
    }
  }
  const body: Record<string, unknown> = {};
  if (options?.page !== undefined || options?.pageSize !== undefined || options?.sort || options?.filter) {
    const size = options?.pageSize ?? 50;
    body.page = { mode: 'offset', position: String((options?.page ?? 0) * size), size };
    const sortRules = parseSortExpression(options?.sort);
    if (sortRules.length > 0) body.sort = sortRules;
    if (options?.filter) body.filterExpression = options.filter;
  }
  const qs = params.toString();
  const url = qs ? `/saved-queries/card_templates/execute?${qs}` : "/saved-queries/card_templates/execute";
  const response = await apiManager.post('data', url, body, headers);
  const data = response.data;
  if (Array.isArray(data)) return data as CardTemplatesRow[];
  if (data && typeof data === 'object') {
    const obj = data as Record<string, unknown>;
    if (Array.isArray(obj.data)) return obj.data as CardTemplatesRow[];
    const keys = Object.keys(obj);
    if (keys.length === 1 && Array.isArray(obj[keys[0]])) {
      return obj[keys[0]] as CardTemplatesRow[];
    }
  }
  return [] as CardTemplatesRow[];
}
