// AUTO-GENERATED by scripts/fetch-saved-queries.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/saved-query
// Saved query: card_spec_approve ("card_spec_approve")
// Type: common_table_expression  |  Single output: true  |  App: aswathtestapp_6a67823a8fa7215710927dbc
// Approve a card spec: sets item_revision.status = 'Approved' for the given revision. Param: itemRevId. Writes ONLY a plain text column - no JSON - so it is immune to the param-substitution quoting/comma-splitting defects. Does NOT touch the task-queue instance; stage advancement is owned by the workflow.

import { apiManager } from '@/services/api-manager';
import { getDataHeaders } from '@/config/api-config';

/** Input parameters for `card_spec_approve` (write — sent as a flat JSON body). */
export interface CardSpecApproveInput {
  itemRevId: string;
}

/** Row returned by `card_spec_approve` (write — the affected row's id). */
export interface CardSpecApproveResult {
  id: string;
}

export const CARD_SPEC_APPROVE_NAME = "card_spec_approve";
export const CARD_SPEC_APPROVE_IS_SINGLE = true as const;
export const CARD_SPEC_APPROVE_APP_KEY = "aswathtestapp_6a67823a8fa7215710927dbc";

/**
 * Execute the `card_spec_approve` saved query. WRITE (update).
 * Inputs are sent as a flat JSON body; returns the affected row(s).
 */
export async function executeCardSpecApprove(
  input: CardSpecApproveInput,
): Promise<CardSpecApproveResult[]> {
  const headers = getDataHeaders(CARD_SPEC_APPROVE_APP_KEY || undefined);
  const response = await apiManager.post('data', "/saved-queries/card_spec_approve/execute", input, headers);
  return response.data as CardSpecApproveResult[];
}
