// AUTO-GENERATED by scripts/fetch-saved-queries.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/saved-query
// Saved query: component_line_create ("Component Line Create")
// Type: dynamic  |  Single output: true  |  App: aswathtestapp_6a67823a8fa7215710927dbc
// Step 3 of 3 for adding a component line. Creates the order_line pointing at the component revision. JSON body: orderId, itemRevId, name, description, qty. The item column is jsonb, same shape the card path writes.

import { apiManager } from '@/services/api-manager';
import { getDataHeaders } from '@/config/api-config';

/** Input parameters for `component_line_create` (write — sent as a flat JSON body). */
export interface ComponentLineCreateInput {
  description: string;
  itemRevId: string;
  name: string;
  orderId: string;
  qty: string;
}

/** Row returned by `component_line_create` (write).
 *  (Unwrapped from the saved query's `order_line` output.) */
export interface ComponentLineCreateResult {
  /** Id */
  id?: string;
  /** Qty */
  qty?: number;
}

export const COMPONENT_LINE_CREATE_NAME = "component_line_create";
export const COMPONENT_LINE_CREATE_IS_SINGLE = true as const;
export const COMPONENT_LINE_CREATE_APP_KEY = "aswathtestapp_6a67823a8fa7215710927dbc";

/**
 * Execute the `component_line_create` saved query. WRITE (insert).
 * Inputs are sent as a flat JSON body; returns the affected row(s).
 */
export async function executeComponentLineCreate(
  input: ComponentLineCreateInput,
): Promise<ComponentLineCreateResult> {
  const headers = getDataHeaders(COMPONENT_LINE_CREATE_APP_KEY || undefined);
  const response = await apiManager.post('data', "/saved-queries/component_line_create/execute", input, headers);
  return response.data as ComponentLineCreateResult;
}
