// AUTO-GENERATED by scripts/fetch-saved-queries.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/saved-query
// Saved query: margin_override_create ("Create margin override")
// Type: dynamic  |  Single output: true  |  App: aswathtestapp_6a67823a8fa7215710927dbc
// Inserts one per-order margin override with its mandatory reason. Reason is free text so all params go in the JSON body: orderId, componentRole, marginBps, fromBps, scenario, reason, createdAt. Call margin_override_supersede for the same order and role first.

import { apiManager } from '@/services/api-manager';
import { getDataHeaders } from '@/config/api-config';

/** Input parameters for `margin_override_create` (write — sent as a flat JSON body). */
export interface MarginOverrideCreateInput {
  componentRole: string;
  createdAt: string;
  fromBps: string;
  marginBps: string;
  orderId: string;
  reason: string;
  scenario: string;
}

/** Row returned by `margin_override_create` (write).
 *  (Unwrapped from the saved query's `margin_override` output.) */
export interface MarginOverrideCreateResult {
  /** ID */
  id: string;
  /** Active */
  active?: boolean;
  /** Component Role */
  component_role?: string;
  /** Created At */
  created_at?: string;
  /** From Bps */
  from_bps?: number;
  /** Margin Bps */
  margin_bps?: number;
  /** Reason */
  reason?: string;
  /** Scenario */
  scenario?: string;
}

export const MARGIN_OVERRIDE_CREATE_NAME = "margin_override_create";
export const MARGIN_OVERRIDE_CREATE_IS_SINGLE = true as const;
export const MARGIN_OVERRIDE_CREATE_APP_KEY = "aswathtestapp_6a67823a8fa7215710927dbc";

/**
 * Execute the `margin_override_create` saved query. WRITE (insert).
 * Inputs are sent as a flat JSON body; returns the affected row(s).
 */
export async function executeMarginOverrideCreate(
  input: MarginOverrideCreateInput,
): Promise<MarginOverrideCreateResult> {
  const headers = getDataHeaders(MARGIN_OVERRIDE_CREATE_APP_KEY || undefined);
  const response = await apiManager.post('data', "/saved-queries/margin_override_create/execute", input, headers);
  return response.data as MarginOverrideCreateResult;
}
