// AUTO-GENERATED by scripts/fetch-saved-queries.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/saved-query
// Saved query: margin_override_supersede ("Supersede margin overrides")
// Type: dynamic  |  Single output: false  |  App: aswathtestapp_6a67823a8fa7215710927dbc
// Marks every existing active override for one order and component role inactive. Call before inserting a new override, or on its own to revert the row to the template value. Params: orderId, componentRole.

import { apiManager } from '@/services/api-manager';
import { getDataHeaders } from '@/config/api-config';

/** Input parameters for `margin_override_supersede` (write — sent as a flat JSON body). */
export interface MarginOverrideSupersedeInput {
  componentRole: string;
  orderId: string;
}

/** Row returned by `margin_override_supersede` (write — the affected row's id). */
export interface MarginOverrideSupersedeRow {
  id: string;
}

export const MARGIN_OVERRIDE_SUPERSEDE_NAME = "margin_override_supersede";
export const MARGIN_OVERRIDE_SUPERSEDE_IS_SINGLE = false as const;
export const MARGIN_OVERRIDE_SUPERSEDE_APP_KEY = "aswathtestapp_6a67823a8fa7215710927dbc";

/**
 * Execute the `margin_override_supersede` saved query. WRITE (update).
 * Inputs are sent as a flat JSON body; returns the affected row(s).
 */
export async function executeMarginOverrideSupersede(
  input: MarginOverrideSupersedeInput,
): Promise<MarginOverrideSupersedeRow[]> {
  const headers = getDataHeaders(MARGIN_OVERRIDE_SUPERSEDE_APP_KEY || undefined);
  const response = await apiManager.post('data', "/saved-queries/margin_override_supersede/execute", input, headers);
  return response.data as MarginOverrideSupersedeRow[];
}
