// AUTO-GENERATED by scripts/fetch-saved-queries.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/saved-query
// Saved query: order_detail ("Order Detail")
// Type: dynamic  |  Single output: true  |  App: aswathtestapp_6a67823a8fa7215710927dbc
// Single-order read for the Order Details page, scoped to THIS app's own LOCAL orders entity. NO entityAppKey/target app param. Param: orderId — filter "id == $orderId" (the URL query param name is `orderId`, matching what OrderDetailPage's useSavedQuerySingle("order_detail", { input: { orderId } }) call already sends). Returns id, order_code, order_brief, order_kind, order_type, status (raw JSON), requested_delivery (the order's TARGET/requested delivery date, shown as "Target <date>" on the header), created_at, created_by{id, full_name} (shown as "Created <relative time> by <full_name>" on the header), tq_instance (nested id), buyer_party_id (nested id, name).

import { apiManager } from '@/services/api-manager';
import { getDataHeaders } from '@/config/api-config';
import { parseSortExpression } from '@/hooks/saved-query-request';

/** Input parameters for `order_detail`. */
export interface OrderDetailInput {
  orderId: string;
}

/** Result for `order_detail` (single output).
 *  (Unwrapped from the saved query's `orders` output.) */
export interface OrderDetailResult {
  /** Id */
  id?: string;
  /** Created At */
  created_at?: string;
  /** Order Brief */
  order_brief?: string;
  /** Order Code */
  order_code?: string;
  /** Order Kind */
  order_kind?: string;
  /** Order Type */
  order_type?: string;
  /** Requested Delivery */
  requested_delivery?: string;
  /** Status */
  status?: Record<string, unknown>;
  /** Buyer Party Id */
  buyer_party_id?: {
      /** Id */
      id?: string;
      /** Name */
      name?: string;
    };
  /** Created By */
  created_by?: {
      id?: string;
      full_name?: string;
    };
  /** TQ Instance */
  tq_instance?: {
      /** Id */
      id?: string;
    };
}

export const ORDER_DETAIL_NAME = "order_detail";
export const ORDER_DETAIL_IS_SINGLE = true as const;
export const ORDER_DETAIL_APP_KEY = "aswathtestapp_6a67823a8fa7215710927dbc";

export interface ExecuteOrderDetailOptions {
  /** Sort: comma-separated, `-` prefix for descending (e.g. 'status,-balance'). Body `sort`. */
  sort?: string;
  /** CEL filter expression (body `filterExpression`). */
  filter?: string;
}

/**
 * Execute the `order_detail` saved query. Read-only.
 * Returns `null` when the server reports NO_RESULTS_FOUND (HTTP 404).
 */
export async function executeOrderDetail(
  input: OrderDetailInput,
  options?: ExecuteOrderDetailOptions,
): Promise<OrderDetailResult | null> {
  const headers = getDataHeaders(ORDER_DETAIL_APP_KEY || undefined);
  const params = new URLSearchParams();
  if (input) {
    for (const [k, v] of Object.entries(input)) {
      if (v === undefined || v === null) continue;
      if (k === '_page' || k === '_size' || k === '_sort' || k === '_filter') continue;
      params.set(k, String(v));
    }
  }
  const body: Record<string, unknown> = {};
  if (options?.sort || options?.filter) {
    body.page = { mode: 'offset', position: '0', size: 1 };
    const sortRules = parseSortExpression(options?.sort);
    if (sortRules.length > 0) body.sort = sortRules;
    if (options?.filter) body.filterExpression = options.filter;
  }
  const qs = params.toString();
  const url = qs ? `/saved-queries/order_detail/execute?${qs}` : "/saved-queries/order_detail/execute";
  try {
    const response = await apiManager.post('data', url, body, headers);
    const data = response.data;
    if (data == null) return null;
    if (Array.isArray(data)) return (data.length ? data[0] : null) as OrderDetailResult | null;
    if (typeof data === 'object') {
      const obj = data as Record<string, unknown>;
      if (Array.isArray(obj.data)) return (obj.data.length ? obj.data[0] : null) as OrderDetailResult | null;
      if (obj.data && typeof obj.data === 'object') return obj.data as OrderDetailResult | null;
      const keys = Object.keys(obj);
      if (keys.length === 1 && Array.isArray(obj[keys[0]])) {
        const arr = obj[keys[0]] as unknown[];
        return (arr.length ? arr[0] : null) as OrderDetailResult | null;
      }
      return obj as unknown as OrderDetailResult | null;
    }
    return data as OrderDetailResult | null;
  } catch (err: unknown) {
    // Map server 404 NO_RESULTS_FOUND → null so callers can render
    // "no data" without branching on errors.
    const status = (err as { response?: { status?: number } })?.response?.status;
    if (status === 404) return null;
    throw err;
  }
}
