// AUTO-GENERATED by scripts/fetch-saved-queries.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/saved-query
// Saved query: order_cards ("order_cards")
// Type: dynamic  |  Single output: false  |  App: aswathtestapp_6a67823a8fa7215710927dbc
// Card specs (order_lines) for one order. Param: orderId.

import { apiManager } from '@/services/api-manager';
import { getDataHeaders } from '@/config/api-config';
import { parseSortExpression } from '@/hooks/saved-query-request';

/** Input parameters for `order_cards`. */
export interface OrderCardsInput {
  orderId: string;
}

/** Single row in the `order_cards` result set. */
export interface OrderCardsRow {
  [key: string]: unknown;
}

export const ORDER_CARDS_NAME = "order_cards";
export const ORDER_CARDS_IS_SINGLE = false as const;
export const ORDER_CARDS_APP_KEY = "aswathtestapp_6a67823a8fa7215710927dbc";

export interface ExecuteOrderCardsOptions {
  /** Zero-based page index (body `page`, offset mode). */
  page?: number;
  /** Page size (body `page.size`). */
  pageSize?: number;
  /** Sort: comma-separated, `-` prefix for descending (e.g. 'status,-balance'). Body `sort`. */
  sort?: string;
  /** CEL filter expression (body `filterExpression`). */
  filter?: string;
}

/**
 * Execute the `order_cards` saved query. Read-only.
 */
export async function executeOrderCards(
  input: OrderCardsInput,
  options?: ExecuteOrderCardsOptions,
): Promise<OrderCardsRow[]> {
  const headers = getDataHeaders(ORDER_CARDS_APP_KEY || undefined);
  const params = new URLSearchParams();
  if (input) {
    for (const [k, v] of Object.entries(input)) {
      if (v === undefined || v === null) continue;
      if (k === '_page' || k === '_size' || k === '_sort' || k === '_filter') continue;
      params.set(k, String(v));
    }
  }
  const body: Record<string, unknown> = {};
  if (options?.page !== undefined || options?.pageSize !== undefined || options?.sort || options?.filter) {
    const size = options?.pageSize ?? 50;
    body.page = { mode: 'offset', position: String((options?.page ?? 0) * size), size };
    const sortRules = parseSortExpression(options?.sort);
    if (sortRules.length > 0) body.sort = sortRules;
    if (options?.filter) body.filterExpression = options.filter;
  }
  const qs = params.toString();
  const url = qs ? `/saved-queries/order_cards/execute?${qs}` : "/saved-queries/order_cards/execute";
  const response = await apiManager.post('data', url, body, headers);
  const data = response.data;
  if (Array.isArray(data)) return data as OrderCardsRow[];
  if (data && typeof data === 'object') {
    const obj = data as Record<string, unknown>;
    if (Array.isArray(obj.data)) return obj.data as OrderCardsRow[];
    const keys = Object.keys(obj);
    if (keys.length === 1 && Array.isArray(obj[keys[0]])) {
      return obj[keys[0]] as OrderCardsRow[];
    }
  }
  return [] as OrderCardsRow[];
}
