// AUTO-GENERATED by scripts/fetch-saved-queries.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/saved-query
// Saved query: pricing_template_update ("Pricing Template Update")
// Type: dynamic  |  Single output: true  |  App: aswathtestapp_6a67823a8fa7215710927dbc
// Update a pricing template header. JSON body: templateId, name, model, basis, scenario, floorBps, effectiveFrom, effectiveTo, active.

import { apiManager } from '@/services/api-manager';
import { getDataHeaders } from '@/config/api-config';

/** Input parameters for `pricing_template_update` (write — sent as a flat JSON body). */
export interface PricingTemplateUpdateInput {
  active: string;
  basis: string;
  effectiveFrom: string;
  effectiveTo: string;
  floorBps: string;
  model: string;
  name: string;
  scenario: string;
  templateId: string;
}

/** Row returned by `pricing_template_update` (write).
 *  (Unwrapped from the saved query's `pricing_template` output.) */
export interface PricingTemplateUpdateResult {
  /** ID */
  id: string;
  /** Active */
  active?: boolean;
  /** Floor Bps */
  floor_bps?: number;
  /** Name */
  name?: string;
  /** Scenario */
  scenario?: string;
}

export const PRICING_TEMPLATE_UPDATE_NAME = "pricing_template_update";
export const PRICING_TEMPLATE_UPDATE_IS_SINGLE = true as const;
export const PRICING_TEMPLATE_UPDATE_APP_KEY = "aswathtestapp_6a67823a8fa7215710927dbc";

/**
 * Execute the `pricing_template_update` saved query. WRITE (update).
 * Inputs are sent as a flat JSON body; returns the affected row(s).
 */
export async function executePricingTemplateUpdate(
  input: PricingTemplateUpdateInput,
): Promise<PricingTemplateUpdateResult[]> {
  const headers = getDataHeaders(PRICING_TEMPLATE_UPDATE_APP_KEY || undefined);
  const response = await apiManager.post('data', "/saved-queries/pricing_template_update/execute", input, headers);
  return response.data as PricingTemplateUpdateResult[];
}
