// AUTO-GENERATED by scripts/fetch-saved-queries.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/saved-query
// Saved query: pricing_template_create ("Pricing Template Create")
// Type: dynamic  |  Single output: true  |  App: aswathtestapp_6a67823a8fa7215710927dbc
// Create a pricing template for a client. JSON body: name, clientId, model, basis, scenario, floorBps, effectiveFrom, effectiveTo. Body transport because name is free text.

import { apiManager } from '@/services/api-manager';
import { getDataHeaders } from '@/config/api-config';

/** Input parameters for `pricing_template_create` (write — sent as a flat JSON body). */
export interface PricingTemplateCreateInput {
  basis: string;
  clientId: string;
  effectiveFrom: string;
  effectiveTo: string;
  floorBps: string;
  model: string;
  name: string;
  scenario: string;
}

/** Row returned by `pricing_template_create` (write).
 *  (Unwrapped from the saved query's `pricing_template` output.) */
export interface PricingTemplateCreateResult {
  /** ID */
  id: string;
  /** Floor Bps */
  floor_bps?: number;
  /** Name */
  name?: string;
}

export const PRICING_TEMPLATE_CREATE_NAME = "pricing_template_create";
export const PRICING_TEMPLATE_CREATE_IS_SINGLE = true as const;
export const PRICING_TEMPLATE_CREATE_APP_KEY = "aswathtestapp_6a67823a8fa7215710927dbc";

/**
 * Execute the `pricing_template_create` saved query. WRITE (insert).
 * Inputs are sent as a flat JSON body; returns the affected row(s).
 */
export async function executePricingTemplateCreate(
  input: PricingTemplateCreateInput,
): Promise<PricingTemplateCreateResult> {
  const headers = getDataHeaders(PRICING_TEMPLATE_CREATE_APP_KEY || undefined);
  const response = await apiManager.post('data', "/saved-queries/pricing_template_create/execute", input, headers);
  return response.data as PricingTemplateCreateResult;
}
