// AUTO-GENERATED by scripts/fetch-saved-queries.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/saved-query
// Saved query: rfe_line_create ("RFE Line Create")
// Type: common_table_expression  |  Single output: true  |  App: aswathtestapp_6a67823a8fa7215710927dbc
// Add one bid line to an RFE. All params are UUIDs/ints - call with query-string params.

import { apiManager } from '@/services/api-manager';
import { getDataHeaders } from '@/config/api-config';

/** Input parameters for `rfe_line_create` (write — sent as a flat JSON body). */
export interface RfeLineCreateInput {
  itemRevId: string;
  orderLineId: string;
  qty: string;
  rfeId: string;
}

/** Row returned by `rfe_line_create` (write — the affected row's id). */
export interface RfeLineCreateResult {
  id: string;
}

export const RFE_LINE_CREATE_NAME = "rfe_line_create";
export const RFE_LINE_CREATE_IS_SINGLE = true as const;
export const RFE_LINE_CREATE_APP_KEY = "aswathtestapp_6a67823a8fa7215710927dbc";

/**
 * Execute the `rfe_line_create` saved query. WRITE (insert).
 * Inputs are sent as a flat JSON body; returns the affected row(s).
 */
export async function executeRfeLineCreate(
  input: RfeLineCreateInput,
): Promise<RfeLineCreateResult> {
  const headers = getDataHeaders(RFE_LINE_CREATE_APP_KEY || undefined);
  const response = await apiManager.post('data', "/saved-queries/rfe_line_create/execute", input, headers);
  return response.data as RfeLineCreateResult;
}
