// AUTO-GENERATED by scripts/fetch-saved-queries.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/saved-query
// Saved query: tq_sub_task_add ("tq_sub_task_add")
// Type: common_table_expression  |  Single output: true  |  App: aswathtestapp_6a67823a8fa7215710927dbc
// Advance a tq_instance to a new sub-task (stage): clears is_current on ALL prior state instances of the instance (flipprev) so exactly one state instance is current across the whole instance, then creates the new sub-task via sub_task_history + its initial state via status_history, and repoints current_task/current_status. Params: instanceId, subTaskName, stateName. Single-row reads use limit 1 with newest-first ordering so duplicate rows cannot break the CTE. This is the SINGLE owner of stage creation — tq_create only creates the bare instance.

import { apiManager } from '@/services/api-manager';
import { getDataHeaders } from '@/config/api-config';

/** Input parameters for `tq_sub_task_add` (write — sent as a flat JSON body). */
export interface TqSubTaskAddInput {
  instanceId: string;
  stateDef: string;
  stateName: string;
  stins: string;
  sub: string;
  subTaskDef: string;
  subTaskName: string;
}

/** Row returned by `tq_sub_task_add` (write).
 *  (Unwrapped from the saved query's `tq_instance` output.) */
export interface TqSubTaskAddResult {
  /** Id */
  id?: string;
}

export const TQ_SUB_TASK_ADD_NAME = "tq_sub_task_add";
export const TQ_SUB_TASK_ADD_IS_SINGLE = true as const;
export const TQ_SUB_TASK_ADD_APP_KEY = "aswathtestapp_6a67823a8fa7215710927dbc";

/**
 * Execute the `tq_sub_task_add` saved query. WRITE (update).
 * Inputs are sent as a flat JSON body; returns the affected row(s).
 */
export async function executeTqSubTaskAdd(
  input: TqSubTaskAddInput,
): Promise<TqSubTaskAddResult[]> {
  const headers = getDataHeaders(TQ_SUB_TASK_ADD_APP_KEY || undefined);
  const response = await apiManager.post('data', "/saved-queries/tq_sub_task_add/execute", input, headers);
  return response.data as TqSubTaskAddResult[];
}
