// AUTO-GENERATED by scripts/fetch-saved-queries.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/saved-query
// Saved query: tq_sub_task_assign ("TQ Sub Task Assign")
// Type: dynamic  |  Single output: false  |  App: aswathtestapp_6a67823a8fa7215710927dbc
// Assign a platform user to one named stage of a task instance. Updates tq_sub_task_instance.assignee ONLY - never current_state or status_history, which the workflow owns. Params: taskInstanceId, subTaskName (e.g. Specs, Quote, Award), userId.

import { apiManager } from '@/services/api-manager';
import { getDataHeaders } from '@/config/api-config';

/** Input parameters for `tq_sub_task_assign` (write — sent as a flat JSON body). */
export interface TqSubTaskAssignInput {
  subTaskName: string;
  taskInstanceId: string;
  userId: string;
}

/** Row returned by `tq_sub_task_assign` (write — the affected row's id). */
export interface TqSubTaskAssignRow {
  id: string;
}

export const TQ_SUB_TASK_ASSIGN_NAME = "tq_sub_task_assign";
export const TQ_SUB_TASK_ASSIGN_IS_SINGLE = false as const;
export const TQ_SUB_TASK_ASSIGN_APP_KEY = "aswathtestapp_6a67823a8fa7215710927dbc";

/**
 * Execute the `tq_sub_task_assign` saved query. WRITE (update).
 * Inputs are sent as a flat JSON body; returns the affected row(s).
 */
export async function executeTqSubTaskAssign(
  input: TqSubTaskAssignInput,
): Promise<TqSubTaskAssignRow[]> {
  const headers = getDataHeaders(TQ_SUB_TASK_ASSIGN_APP_KEY || undefined);
  const response = await apiManager.post('data', "/saved-queries/tq_sub_task_assign/execute", input, headers);
  return response.data as TqSubTaskAssignRow[];
}
