// AUTO-GENERATED by scripts/fetch-saved-queries.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/saved-query
// Saved query: card_line_add ("Add a card order line")
// Type: dynamic  |  Single output: true  |  App: aswathtestapp_6a67823a8fa7215710927dbc
// Adds one order line for a card created by card_add. order_line.item is a jsonb snapshot, not a link. IMPORTANT: pass the whole snapshot as one object in body.item, shaped {item_rev_id, name, status}. Do not put $body params inside the jsonb literal, they get wrapped in single quotes and the join then fails. JSON body: orderLineId, orderId, qty, item.

import { apiManager } from '@/services/api-manager';
import { getDataHeaders } from '@/config/api-config';

/** Input parameters for `card_line_add` (write — sent as a flat JSON body). */
export interface CardLineAddInput {
  item: string;
  orderId: string;
  orderLineId: string;
  qty: string;
}

/** Row returned by `card_line_add` (write).
 *  (Unwrapped from the saved query's `order_line` output.) */
export interface CardLineAddResult {
  /** Id */
  id?: string;
  /** Item */
  item?: Record<string, unknown>;
  /** Qty */
  qty?: number;
  /** Uom */
  uom?: string;
}

export const CARD_LINE_ADD_NAME = "card_line_add";
export const CARD_LINE_ADD_IS_SINGLE = true as const;
export const CARD_LINE_ADD_APP_KEY = "aswathtestapp_6a67823a8fa7215710927dbc";

/**
 * Execute the `card_line_add` saved query. WRITE (insert).
 * Inputs are sent as a flat JSON body; returns the affected row(s).
 */
export async function executeCardLineAdd(
  input: CardLineAddInput,
): Promise<CardLineAddResult> {
  const headers = getDataHeaders(CARD_LINE_ADD_APP_KEY || undefined);
  const response = await apiManager.post('data', "/saved-queries/card_line_add/execute", input, headers);
  return response.data as CardLineAddResult;
}
