// AUTO-GENERATED by scripts/fetch-saved-queries.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/saved-query
// Saved query: component_rev_create ("Component Revision Create")
// Type: dynamic  |  Single output: true  |  App: aswathtestapp_6a67823a8fa7215710927dbc
// Step 2 of 3 for adding a component line. Creates revision 1 of the component item, already approved because a component carries no separate design review. Query-string params: itemRevId, itemId.

import { apiManager } from '@/services/api-manager';
import { getDataHeaders } from '@/config/api-config';

/** Input parameters for `component_rev_create` (write — sent as a flat JSON body). */
export interface ComponentRevCreateInput {
  itemId: string;
  itemRevId: string;
}

/** Row returned by `component_rev_create` (write).
 *  (Unwrapped from the saved query's `item_revision` output.) */
export interface ComponentRevCreateResult {
  /** Id */
  id?: string;
  /** Rev */
  rev?: number;
  /** Status */
  status?: string;
}

export const COMPONENT_REV_CREATE_NAME = "component_rev_create";
export const COMPONENT_REV_CREATE_IS_SINGLE = true as const;
export const COMPONENT_REV_CREATE_APP_KEY = "aswathtestapp_6a67823a8fa7215710927dbc";

/**
 * Execute the `component_rev_create` saved query. WRITE (insert).
 * Inputs are sent as a flat JSON body; returns the affected row(s).
 */
export async function executeComponentRevCreate(
  input: ComponentRevCreateInput,
): Promise<ComponentRevCreateResult> {
  const headers = getDataHeaders(COMPONENT_REV_CREATE_APP_KEY || undefined);
  const response = await apiManager.post('data', "/saved-queries/component_rev_create/execute", input, headers);
  return response.data as ComponentRevCreateResult;
}
