// AUTO-GENERATED by scripts/fetch-saved-queries.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/saved-query
// Saved query: order_create ("order_create")
// Type: common_table_expression  |  Single output: true  |  App: aswathtestapp_6a67823a8fa7215710927dbc
// Inserts a new order into THIS app's own LOCAL orders entity — NO entityAppKey/target app (never cross-app-targets domainmodel). Uses the standard $body.<field> JSON-body write contract (executed via useSavedQueryMutation, which POSTs a flat JSON body) rather than query-string params — free-text fields like order_brief can contain commas, which this tenant's query-string param substitution mis-parses as an array and 500s on. Fields: order_code ($body.orderCode), order_kind ($body.orderKind), order_type ($body.orderType), order_brief ($body.orderBrief), buyer_party_id (link, {id: $body.buyerPartyId}), requested_delivery ($body.requestedDelivery). Returns the new row's id.

import { apiManager } from '@/services/api-manager';
import { getDataHeaders } from '@/config/api-config';

/** Input parameters for `order_create` (write — sent as a flat JSON body). */
export interface OrderCreateInput {
  buyerPartyId: string;
  orderBrief: string;
  orderCode: string;
  orderKind: string;
  orderType: string;
  requestedDelivery: string;
}

/** Row returned by `order_create` (write).
 *  (Unwrapped from the saved query's `orders` output.) */
export interface OrderCreateResult {
  /** Id */
  id?: string;
}

export const ORDER_CREATE_NAME = "order_create";
export const ORDER_CREATE_IS_SINGLE = true as const;
export const ORDER_CREATE_APP_KEY = "aswathtestapp_6a67823a8fa7215710927dbc";

/**
 * Execute the `order_create` saved query. WRITE (insert).
 * Inputs are sent as a flat JSON body; returns the affected row(s).
 */
export async function executeOrderCreate(
  input: OrderCreateInput,
): Promise<OrderCreateResult> {
  const headers = getDataHeaders(ORDER_CREATE_APP_KEY || undefined);
  const response = await apiManager.post('data', "/saved-queries/order_create/execute", input, headers);
  return response.data as OrderCreateResult;
}
