// AUTO-GENERATED by scripts/fetch-saved-queries.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/saved-query
// Saved query: order_list ("order_list")
// Type: dynamic  |  Single output: false  |  App: aswathtestapp_6a67823a8fa7215710927dbc
// Orders for the Orders list screen AND the fallback source for Order Details (client-side find by id). Dynamic read on THIS app's own LOCAL orders entity — NO entityAppKey/target app param. Sorted by requested_delivery ascending. Columns: id, order_code, order_kind, order_type, status (jsonb snapshot written by order_link_tq at workflow start, e.g. {"state":"Order Received"}), requested_delivery (target/requested delivery date), created_at, created_by{id, full_name} (order creator, shown as "Created <relative time> by <name>" on Order Details), order_brief, buyer_party_id{id,name}, tq_instance{id, current_status{tq_state_definition{state}}}. The tq_instance.current_status.tq_state_definition.state path is a 3-level-deep nested projection attempting to surface the LIVE current TQ state directly (Plan A) — this tenant's saved-query output layer sometimes strips 2+-level-deep nested objects, so callers (resolveOrderStateLabel in orders-helpers.ts) treat it as best-effort and fall back to the status jsonb snapshot (Plan B) when it's absent, and to "Pending" only when tq_instance itself is null.

import { apiManager } from '@/services/api-manager';
import { getDataHeaders } from '@/config/api-config';
import { parseSortExpression } from '@/hooks/saved-query-request';

/** Input parameters for `order_list` (none declared). */
export type OrderListInput = Record<string, never>;

/** Single row in the `order_list` result set.
 *  (Unwrapped from the saved query's `orders_list` output array.) */
export interface OrderListRow {
  /** Id */
  id?: string;
  /** Created At */
  created_at?: string;
  /** Order Brief */
  order_brief?: string;
  /** Order Code */
  order_code?: string;
  /** Order Kind */
  order_kind?: string;
  /** Order Type */
  order_type?: string;
  /** Requested Delivery */
  requested_delivery?: string;
  /** Status */
  status?: Record<string, unknown>;
  /** Buyer Party Id */
  buyer_party_id?: {
      /** Id */
      id?: string;
      /** Name */
      name?: string;
    };
  /** Created By */
  created_by?: {
      id?: string;
      full_name?: string;
    };
  /** TQ Instance */
  tq_instance?: {
      /** Id */
      id?: string;
      /** Current Status */
      current_status?: {
        /** TQ State Definition */
        tq_state_definition?: {
          /** State */
          state?: string;
        };
      };
    };
}

export const ORDER_LIST_NAME = "order_list";
export const ORDER_LIST_IS_SINGLE = false as const;
export const ORDER_LIST_APP_KEY = "aswathtestapp_6a67823a8fa7215710927dbc";

export interface ExecuteOrderListOptions {
  /** Zero-based page index (body `page`, offset mode). */
  page?: number;
  /** Page size (body `page.size`). */
  pageSize?: number;
  /** Sort: comma-separated, `-` prefix for descending (e.g. 'status,-balance'). Body `sort`. */
  sort?: string;
  /** CEL filter expression (body `filterExpression`). */
  filter?: string;
}

/**
 * Execute the `order_list` saved query. Read-only.
 */
export async function executeOrderList(
  input?: OrderListInput,
  options?: ExecuteOrderListOptions,
): Promise<OrderListRow[]> {
  const headers = getDataHeaders(ORDER_LIST_APP_KEY || undefined);
  const params = new URLSearchParams();
  if (input) {
    for (const [k, v] of Object.entries(input)) {
      if (v === undefined || v === null) continue;
      if (k === '_page' || k === '_size' || k === '_sort' || k === '_filter') continue;
      params.set(k, String(v));
    }
  }
  const body: Record<string, unknown> = {};
  if (options?.page !== undefined || options?.pageSize !== undefined || options?.sort || options?.filter) {
    const size = options?.pageSize ?? 50;
    body.page = { mode: 'offset', position: String((options?.page ?? 0) * size), size };
    const sortRules = parseSortExpression(options?.sort);
    if (sortRules.length > 0) body.sort = sortRules;
    if (options?.filter) body.filterExpression = options.filter;
  }
  const qs = params.toString();
  const url = qs ? `/saved-queries/order_list/execute?${qs}` : "/saved-queries/order_list/execute";
  const response = await apiManager.post('data', url, body, headers);
  const data = response.data;
  if (Array.isArray(data)) return data as OrderListRow[];
  if (data && typeof data === 'object') {
    const obj = data as Record<string, unknown>;
    if (Array.isArray(obj.data)) return obj.data as OrderListRow[];
    const keys = Object.keys(obj);
    if (keys.length === 1 && Array.isArray(obj[keys[0]])) {
      return obj[keys[0]] as OrderListRow[];
    }
  }
  return [] as OrderListRow[];
}
