// AUTO-GENERATED by scripts/fetch-saved-queries.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/saved-query
// Saved query: order_card_variants ("Order card variants")
// Type: dynamic  |  Single output: false  |  App: aswathtestapp_6a67823a8fa7215710927dbc
// All variations on one order, with their delta, quantity, due date and approval state. Param: orderId.

import { apiManager } from '@/services/api-manager';
import { getDataHeaders } from '@/config/api-config';
import { parseSortExpression } from '@/hooks/saved-query-request';

/** Input parameters for `order_card_variants`. */
export interface OrderCardVariantsInput {
  orderId: string;
}

/** Single row in the `order_card_variants` result set.
 *  (Unwrapped from the saved query's `card_variant_list` output array.) */
export interface OrderCardVariantsRow {
  /** ID */
  id: string;
  /** Approved */
  approved?: boolean;
  /** Approved At */
  approved_at?: string;
  /** Created At */
  created_at?: string;
  /** Delta */
  delta?: Record<string, unknown>;
  /** Due Date */
  due_date?: string;
  /** Label */
  label?: string;
  /** Qty */
  qty?: number;
  /** Card Spec Ref */
  card_spec_ref?: {
      /** Id */
      id?: string;
    };
}

export const ORDER_CARD_VARIANTS_NAME = "order_card_variants";
export const ORDER_CARD_VARIANTS_IS_SINGLE = false as const;
export const ORDER_CARD_VARIANTS_APP_KEY = "aswathtestapp_6a67823a8fa7215710927dbc";

export interface ExecuteOrderCardVariantsOptions {
  /** Zero-based page index (body `page`, offset mode). */
  page?: number;
  /** Page size (body `page.size`). */
  pageSize?: number;
  /** Sort: comma-separated, `-` prefix for descending (e.g. 'status,-balance'). Body `sort`. */
  sort?: string;
  /** CEL filter expression (body `filterExpression`). */
  filter?: string;
}

/**
 * Execute the `order_card_variants` saved query. Read-only.
 */
export async function executeOrderCardVariants(
  input: OrderCardVariantsInput,
  options?: ExecuteOrderCardVariantsOptions,
): Promise<OrderCardVariantsRow[]> {
  const headers = getDataHeaders(ORDER_CARD_VARIANTS_APP_KEY || undefined);
  const params = new URLSearchParams();
  if (input) {
    for (const [k, v] of Object.entries(input)) {
      if (v === undefined || v === null) continue;
      if (k === '_page' || k === '_size' || k === '_sort' || k === '_filter') continue;
      params.set(k, String(v));
    }
  }
  const body: Record<string, unknown> = {};
  if (options?.page !== undefined || options?.pageSize !== undefined || options?.sort || options?.filter) {
    const size = options?.pageSize ?? 50;
    body.page = { mode: 'offset', position: String((options?.page ?? 0) * size), size };
    const sortRules = parseSortExpression(options?.sort);
    if (sortRules.length > 0) body.sort = sortRules;
    if (options?.filter) body.filterExpression = options.filter;
  }
  const qs = params.toString();
  const url = qs ? `/saved-queries/order_card_variants/execute?${qs}` : "/saved-queries/order_card_variants/execute";
  const response = await apiManager.post('data', url, body, headers);
  const data = response.data;
  if (Array.isArray(data)) return data as OrderCardVariantsRow[];
  if (data && typeof data === 'object') {
    const obj = data as Record<string, unknown>;
    if (Array.isArray(obj.data)) return obj.data as OrderCardVariantsRow[];
    const keys = Object.keys(obj);
    if (keys.length === 1 && Array.isArray(obj[keys[0]])) {
      return obj[keys[0]] as OrderCardVariantsRow[];
    }
  }
  return [] as OrderCardVariantsRow[];
}
