// AUTO-GENERATED by scripts/fetch-saved-queries.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/saved-query
// Saved query: party_list ("party_list")
// Type: dynamic  |  Single output: false  |  App: aswathtestapp_6a67823a8fa7215710927dbc
// Buyer/Client picker for the Create Order dialog. Dynamic read on THIS app's own LOCAL party entity — deliberately created with NO entityAppKey/target app param at all (this is the third time a local read/write on this app silently resolved against the cross-app domainmodel entity of the same name after entityAppKey was set to a value equal to this app's own key; omitting the param entirely, as done for order_create/order_link_tq, is the reliable fix). Returns id, name, kind, status, ordered by name ascending. This tenant's local party table has exactly 2 rows: Sephora (9c10b3ba-7bb5-4b65-987d-6ac5f1f951dd) and Williams-Sonoma (92b62af3-2ebe-42a5-97dd-fddb53e6bda3) — the dropdown must show exactly those 2, nothing else.

import { apiManager } from '@/services/api-manager';
import { getDataHeaders } from '@/config/api-config';
import { parseSortExpression } from '@/hooks/saved-query-request';

/** Input parameters for `party_list` (none declared). */
export type PartyListInput = Record<string, never>;

/** Single row in the `party_list` result set.
 *  (Unwrapped from the saved query's `party_list` output array.) */
export interface PartyListRow {
  /** Id */
  id?: string;
  /** Kind */
  kind?: string;
  /** Name */
  name?: string;
  /** Status */
  status?: string;
}

export const PARTY_LIST_NAME = "party_list";
export const PARTY_LIST_IS_SINGLE = false as const;
export const PARTY_LIST_APP_KEY = "aswathtestapp_6a67823a8fa7215710927dbc";

export interface ExecutePartyListOptions {
  /** Zero-based page index (body `page`, offset mode). */
  page?: number;
  /** Page size (body `page.size`). */
  pageSize?: number;
  /** Sort: comma-separated, `-` prefix for descending (e.g. 'status,-balance'). Body `sort`. */
  sort?: string;
  /** CEL filter expression (body `filterExpression`). */
  filter?: string;
}

/**
 * Execute the `party_list` saved query. Read-only.
 */
export async function executePartyList(
  input?: PartyListInput,
  options?: ExecutePartyListOptions,
): Promise<PartyListRow[]> {
  const headers = getDataHeaders(PARTY_LIST_APP_KEY || undefined);
  const params = new URLSearchParams();
  if (input) {
    for (const [k, v] of Object.entries(input)) {
      if (v === undefined || v === null) continue;
      if (k === '_page' || k === '_size' || k === '_sort' || k === '_filter') continue;
      params.set(k, String(v));
    }
  }
  const body: Record<string, unknown> = {};
  if (options?.page !== undefined || options?.pageSize !== undefined || options?.sort || options?.filter) {
    const size = options?.pageSize ?? 50;
    body.page = { mode: 'offset', position: String((options?.page ?? 0) * size), size };
    const sortRules = parseSortExpression(options?.sort);
    if (sortRules.length > 0) body.sort = sortRules;
    if (options?.filter) body.filterExpression = options.filter;
  }
  const qs = params.toString();
  const url = qs ? `/saved-queries/party_list/execute?${qs}` : "/saved-queries/party_list/execute";
  const response = await apiManager.post('data', url, body, headers);
  const data = response.data;
  if (Array.isArray(data)) return data as PartyListRow[];
  if (data && typeof data === 'object') {
    const obj = data as Record<string, unknown>;
    if (Array.isArray(obj.data)) return obj.data as PartyListRow[];
    const keys = Object.keys(obj);
    if (keys.length === 1 && Array.isArray(obj[keys[0]])) {
      return obj[keys[0]] as PartyListRow[];
    }
  }
  return [] as PartyListRow[];
}
