// AUTO-GENERATED by scripts/fetch-saved-queries.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/saved-query
// Saved query: pricing_template_role_update ("Pricing Template Role Update")
// Type: dynamic  |  Single output: true  |  App: aswathtestapp_6a67823a8fa7215710927dbc
// Change one component-role margin. Query-string params: roleId, marginBps.

import { apiManager } from '@/services/api-manager';
import { getDataHeaders } from '@/config/api-config';

/** Input parameters for `pricing_template_role_update` (write — sent as a flat JSON body). */
export interface PricingTemplateRoleUpdateInput {
  marginBps: string;
  roleId: string;
}

/** Row returned by `pricing_template_role_update` (write).
 *  (Unwrapped from the saved query's `pricing_template_role` output.) */
export interface PricingTemplateRoleUpdateResult {
  /** ID */
  id: string;
  /** Component Role */
  component_role?: string;
  /** Margin Bps */
  margin_bps?: number;
}

export const PRICING_TEMPLATE_ROLE_UPDATE_NAME = "pricing_template_role_update";
export const PRICING_TEMPLATE_ROLE_UPDATE_IS_SINGLE = true as const;
export const PRICING_TEMPLATE_ROLE_UPDATE_APP_KEY = "aswathtestapp_6a67823a8fa7215710927dbc";

/**
 * Execute the `pricing_template_role_update` saved query. WRITE (update).
 * Inputs are sent as a flat JSON body; returns the affected row(s).
 */
export async function executePricingTemplateRoleUpdate(
  input: PricingTemplateRoleUpdateInput,
): Promise<PricingTemplateRoleUpdateResult[]> {
  const headers = getDataHeaders(PRICING_TEMPLATE_ROLE_UPDATE_APP_KEY || undefined);
  const response = await apiManager.post('data', "/saved-queries/pricing_template_role_update/execute", input, headers);
  return response.data as PricingTemplateRoleUpdateResult[];
}
