// AUTO-GENERATED by scripts/fetch-saved-queries.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/saved-query
// Saved query: rfe_response_start ("rfe_response_start")
// Type: dynamic  |  Single output: true  |  App: aswathtestapp_6a67823a8fa7215710927dbc
// Open a draft response for an RFE round. Query-string params: rfeId, round. Returns the response id the line writes hang off. Round 1 for the first answer; a returned RFE opens round 2 rather than overwriting.

import { apiManager } from '@/services/api-manager';
import { getDataHeaders } from '@/config/api-config';

/** Input parameters for `rfe_response_start` (write — sent as a flat JSON body). */
export interface RfeResponseStartInput {
  rfeId: string;
  round: string;
}

/** Row returned by `rfe_response_start` (write).
 *  (Unwrapped from the saved query's `rfe_response` output.) */
export interface RfeResponseStartResult {
  /** ID */
  id: string;
  /** Round */
  round?: number;
  /** Status */
  status?: string;
}

export const RFE_RESPONSE_START_NAME = "rfe_response_start";
export const RFE_RESPONSE_START_IS_SINGLE = true as const;
export const RFE_RESPONSE_START_APP_KEY = "aswathtestapp_6a67823a8fa7215710927dbc";

/**
 * Execute the `rfe_response_start` saved query. WRITE (insert).
 * Inputs are sent as a flat JSON body; returns the affected row(s).
 */
export async function executeRfeResponseStart(
  input: RfeResponseStartInput,
): Promise<RfeResponseStartResult> {
  const headers = getDataHeaders(RFE_RESPONSE_START_APP_KEY || undefined);
  const response = await apiManager.post('data', "/saved-queries/rfe_response_start/execute", input, headers);
  return response.data as RfeResponseStartResult;
}
