// AUTO-GENERATED by scripts/fetch-saved-queries.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/saved-query
// Saved query: rfe_tier_create ("rfe_tier_create")
// Type: dynamic  |  Single output: true  |  App: aswathtestapp_6a67823a8fa7215710927dbc
// Add one quantity tier to an RFE line. Query-string params: rfeLineId, tierQty. Call once per tier when the RFE is created - at minimum one tier at the order line qty.

import { apiManager } from '@/services/api-manager';
import { getDataHeaders } from '@/config/api-config';

/** Input parameters for `rfe_tier_create` (write — sent as a flat JSON body). */
export interface RfeTierCreateInput {
  rfeLineId: string;
  tierQty: string;
}

/** Row returned by `rfe_tier_create` (write).
 *  (Unwrapped from the saved query's `rfe_line_tier` output.) */
export interface RfeTierCreateResult {
  /** ID */
  id: string;
  /** Tier Qty */
  tier_qty?: number;
}

export const RFE_TIER_CREATE_NAME = "rfe_tier_create";
export const RFE_TIER_CREATE_IS_SINGLE = true as const;
export const RFE_TIER_CREATE_APP_KEY = "aswathtestapp_6a67823a8fa7215710927dbc";

/**
 * Execute the `rfe_tier_create` saved query. WRITE (insert).
 * Inputs are sent as a flat JSON body; returns the affected row(s).
 */
export async function executeRfeTierCreate(
  input: RfeTierCreateInput,
): Promise<RfeTierCreateResult> {
  const headers = getDataHeaders(RFE_TIER_CREATE_APP_KEY || undefined);
  const response = await apiManager.post('data', "/saved-queries/rfe_tier_create/execute", input, headers);
  return response.data as RfeTierCreateResult;
}
