// AUTO-GENERATED by scripts/fetch-saved-queries.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/saved-query
// Saved query: task_board ("Task Board")
// Type: multi_query  |  Single output: false  |  App: aswathtestapp_6a67823a8fa7215710927dbc
// ONE multi_query backing the whole Task page: my_tasks + unassigned_tasks as two keyed lists. Param: userId. Rows carry order_code, order_brief, requested_delivery, buyer name, current stage name and current status state.

import { apiManager } from '@/services/api-manager';
import { getDataHeaders } from '@/config/api-config';

/** Input parameters for `task_board` (none declared). */
export type TaskBoardInput = Record<string, never>;

// TODO: multi_query saved queries return a map keyed by sub-query name
//       (multi_query) or the last sub-query's result (CTE). Codegen
//       for composite shapes is not implemented yet — the wrapper
//       returns `unknown` until typed by hand.
export type TaskBoardRow = unknown;

export const TASK_BOARD_NAME = "task_board";
export const TASK_BOARD_IS_SINGLE = false as const;
export const TASK_BOARD_APP_KEY = "aswathtestapp_6a67823a8fa7215710927dbc";

export interface ExecuteTaskBoardOptions {
  /** Maps to `_page` URL query param. */
  page?: number;
  /** Maps to `_size` URL query param. */
  pageSize?: number;
  /** Maps to `_sort` URL query param (e.g. 'status,-balance'). */
  sort?: string;
  /** Maps to `_filter` URL param (CEL expression). */
  filter?: string;
}

/**
 * Execute the `task_board` saved query. Read-only.
 */
export async function executeTaskBoard(
  input?: TaskBoardInput,
  options?: ExecuteTaskBoardOptions,
): Promise<unknown> {
  const headers = getDataHeaders(TASK_BOARD_APP_KEY || undefined);
  const params = new URLSearchParams();
  if (input) {
    for (const [k, v] of Object.entries(input)) {
      if (v === undefined || v === null) continue;
      if (k === '_page' || k === '_size' || k === '_sort' || k === '_filter') continue;
      params.set(k, String(v));
    }
  }
  if (options?.page !== undefined) params.set('_page', String(options.page));
  if (options?.pageSize !== undefined) params.set('_size', String(options.pageSize));
  if (options?.sort) params.set('_sort', options.sort);
  if (options?.filter) params.set('_filter', options.filter);
  const body = {};
  const qs = params.toString();
  const url = qs ? `/saved-queries/task_board/execute?${qs}` : "/saved-queries/task_board/execute";
  const response = await apiManager.post('data', url, body, headers);
  return response.data as unknown;
}
