// AUTO-GENERATED by scripts/fetch-saved-queries.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/saved-query
// Saved query: tq_assign ("TQ Assign")
// Type: dynamic  |  Single output: true  |  App: aswathtestapp_6a67823a8fa7215710927dbc
// Assign a platform user as owner of a task instance (the whole order). Updates tq_instance.assignee ONLY - never current_task or current_status, which the workflow owns. Params: taskInstanceId, userId (both UUIDs, query-string safe).

import { apiManager } from '@/services/api-manager';
import { getDataHeaders } from '@/config/api-config';

/** Input parameters for `tq_assign` (write — sent as a flat JSON body). */
export interface TqAssignInput {
  taskInstanceId: string;
  userId: string;
}

/** Row returned by `tq_assign` (write).
 *  (Unwrapped from the saved query's `tq_instance` output.) */
export interface TqAssignResult {
  /** Id */
  id?: string;
  /** Assignee */
  assignee?: {
      id?: string;
      email?: string;
      full_name?: string;
    };
}

export const TQ_ASSIGN_NAME = "tq_assign";
export const TQ_ASSIGN_IS_SINGLE = true as const;
export const TQ_ASSIGN_APP_KEY = "aswathtestapp_6a67823a8fa7215710927dbc";

/**
 * Execute the `tq_assign` saved query. WRITE (update).
 * Inputs are sent as a flat JSON body; returns the affected row(s).
 */
export async function executeTqAssign(
  input: TqAssignInput,
): Promise<TqAssignResult[]> {
  const headers = getDataHeaders(TQ_ASSIGN_APP_KEY || undefined);
  const response = await apiManager.post('data', "/saved-queries/tq_assign/execute", input, headers);
  return response.data as TqAssignResult[];
}
