// AUTO-GENERATED by scripts/fetch-saved-queries.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/saved-query
// Saved query: tq_create ("tq_create")
// Type: common_table_expression  |  Single output: true  |  App: aswathtestapp_6a67823a8fa7215710927dbc
// Creates ONLY the tq_instance for the named task definition and returns its id. Param: taskName (subTaskName/stateName are accepted but IGNORED, kept for caller backward-compatibility). Stage creation is deliberately NOT done here: tq_sub_task_add is the single owner of creating sub-task instances + their initial state, so the first stage and every later stage go through one identical code path. Call tq_create then tq_sub_task_add(instanceId, subTaskName, stateName) to start a workflow.

import { apiManager } from '@/services/api-manager';
import { getDataHeaders } from '@/config/api-config';

/** Input parameters for `tq_create` (write — sent as a flat JSON body). */
export interface TqCreateInput {
  taskDef: string;
  taskName: string;
}

/** Row returned by `tq_create` (write).
 *  (Unwrapped from the saved query's `tq_instance` output.) */
export interface TqCreateResult {
  /** Id */
  id?: string;
}

export const TQ_CREATE_NAME = "tq_create";
export const TQ_CREATE_IS_SINGLE = true as const;
export const TQ_CREATE_APP_KEY = "aswathtestapp_6a67823a8fa7215710927dbc";

/**
 * Execute the `tq_create` saved query. WRITE (insert).
 * Inputs are sent as a flat JSON body; returns the affected row(s).
 */
export async function executeTqCreate(
  input: TqCreateInput,
): Promise<TqCreateResult> {
  const headers = getDataHeaders(TQ_CREATE_APP_KEY || undefined);
  const response = await apiManager.post('data', "/saved-queries/tq_create/execute", input, headers);
  return response.data as TqCreateResult;
}
