// AUTO-GENERATED by scripts/fetch-saved-queries.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/saved-query
// Saved query: tq_state_add ("tq_state_add")
// Type: common_table_expression  |  Single output: true  |  App: aswathtestapp_6a67823a8fa7215710927dbc
// Flip old is_current; create new state via status_history (junction+FK); set current_state + current_status. Params: instanceId, stateName. The 'stins' single-row read uses limit 1 with newest-first ordering so duplicate current state instances cannot break the CTE.

import { apiManager } from '@/services/api-manager';
import { getDataHeaders } from '@/config/api-config';

/** Input parameters for `tq_state_add` (write — sent as a flat JSON body). */
export interface TqStateAddInput {
  curtask: string;
  inst: string;
  instanceId: string;
  stateDef: string;
  stateName: string;
  stins: string;
  subDef: string;
}

/** Row returned by `tq_state_add` (write).
 *  (Unwrapped from the saved query's `tq_instance` output.) */
export interface TqStateAddResult {
  /** Id */
  id?: string;
}

export const TQ_STATE_ADD_NAME = "tq_state_add";
export const TQ_STATE_ADD_IS_SINGLE = true as const;
export const TQ_STATE_ADD_APP_KEY = "aswathtestapp_6a67823a8fa7215710927dbc";

/**
 * Execute the `tq_state_add` saved query. WRITE (update).
 * Inputs are sent as a flat JSON body; returns the affected row(s).
 */
export async function executeTqStateAdd(
  input: TqStateAddInput,
): Promise<TqStateAddResult[]> {
  const headers = getDataHeaders(TQ_STATE_ADD_APP_KEY || undefined);
  const response = await apiManager.post('data', "/saved-queries/tq_state_add/execute", input, headers);
  return response.data as TqStateAddResult[];
}
