// AUTO-GENERATED by scripts/fetch-saved-queries.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/saved-query
// Saved query: tq_stage_list ("TQ Stage List")
// Type: dynamic  |  Single output: false  |  App: aswathtestapp_6a67823a8fa7215710927dbc
// Reads the local aswathtestapp task-queue STAGE definitions (tq_sub_task_definition) for the "Gift Card Order" process, with their allowed states: id, name, is_initial, is_final, next_task{id}, previous_task{id}, and states[] (id, state, is_initial, is_final). Deliberately created with NO entityAppKey/target app param at all (a matching-value entityAppKey previously caused a same-named local query to silently resolve against the cross-app domainmodel entity instead). No filter — this tenant has exactly one process (9 stages: Order, Specs, Quote, Award, Produce, Proof, Ship, Bill, Order Close), so the full unfiltered list is unambiguous. Stage order is reconstructed client-side by following previous_task/next_task starting from the is_initial=true stage. Used by: (1) the Create Order flow to resolve the first stage/state name before calling tq_create, and (2) the Order Details page's Order Progress stepper to render all 9 stages in order.

import { apiManager } from '@/services/api-manager';
import { getDataHeaders } from '@/config/api-config';
import { parseSortExpression } from '@/hooks/saved-query-request';

/** Input parameters for `tq_stage_list` (none declared). */
export type TqStageListInput = Record<string, never>;

/** Single row in the `tq_stage_list` result set.
 *  (Unwrapped from the saved query's `tq_sub_task_definition_list` output array.) */
export interface TqStageListRow {
  /** Id */
  id?: string;
  /** Is Final */
  is_final?: boolean;
  /** Is Initial */
  is_initial?: boolean;
  /** Name */
  name?: string;
  /** Next Task */
  next_task?: {
      /** Id */
      id?: string;
    };
  /** Previous Task */
  previous_task?: {
      /** Id */
      id?: string;
    };
  /** States */
  states?: {
      /** Id */
      id?: string;
      /** Is Final */
      is_final?: boolean;
      /** Is Initial */
      is_initial?: boolean;
      /** State */
      state?: string;
    }[];
}

export const TQ_STAGE_LIST_NAME = "tq_stage_list";
export const TQ_STAGE_LIST_IS_SINGLE = false as const;
export const TQ_STAGE_LIST_APP_KEY = "aswathtestapp_6a67823a8fa7215710927dbc";

export interface ExecuteTqStageListOptions {
  /** Zero-based page index (body `page`, offset mode). */
  page?: number;
  /** Page size (body `page.size`). */
  pageSize?: number;
  /** Sort: comma-separated, `-` prefix for descending (e.g. 'status,-balance'). Body `sort`. */
  sort?: string;
  /** CEL filter expression (body `filterExpression`). */
  filter?: string;
}

/**
 * Execute the `tq_stage_list` saved query. Read-only.
 */
export async function executeTqStageList(
  input?: TqStageListInput,
  options?: ExecuteTqStageListOptions,
): Promise<TqStageListRow[]> {
  const headers = getDataHeaders(TQ_STAGE_LIST_APP_KEY || undefined);
  const params = new URLSearchParams();
  if (input) {
    for (const [k, v] of Object.entries(input)) {
      if (v === undefined || v === null) continue;
      if (k === '_page' || k === '_size' || k === '_sort' || k === '_filter') continue;
      params.set(k, String(v));
    }
  }
  const body: Record<string, unknown> = {};
  if (options?.page !== undefined || options?.pageSize !== undefined || options?.sort || options?.filter) {
    const size = options?.pageSize ?? 50;
    body.page = { mode: 'offset', position: String((options?.page ?? 0) * size), size };
    const sortRules = parseSortExpression(options?.sort);
    if (sortRules.length > 0) body.sort = sortRules;
    if (options?.filter) body.filterExpression = options.filter;
  }
  const qs = params.toString();
  const url = qs ? `/saved-queries/tq_stage_list/execute?${qs}` : "/saved-queries/tq_stage_list/execute";
  const response = await apiManager.post('data', url, body, headers);
  const data = response.data;
  if (Array.isArray(data)) return data as TqStageListRow[];
  if (data && typeof data === 'object') {
    const obj = data as Record<string, unknown>;
    if (Array.isArray(obj.data)) return obj.data as TqStageListRow[];
    const keys = Object.keys(obj);
    if (keys.length === 1 && Array.isArray(obj[keys[0]])) {
      return obj[keys[0]] as TqStageListRow[];
    }
  }
  return [] as TqStageListRow[];
}
