// AUTO-GENERATED by scripts/fetch-saved-queries.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/saved-query
// Saved query: zz_lead_probe ("zz lead probe")
// Type: dynamic  |  Single output: false  |  App: aswathtestapp_6a67823a8fa7215710927dbc
// Probe step 2: does an UPDATE to a saved query take effect at execution?

import { apiManager } from '@/services/api-manager';
import { getDataHeaders } from '@/config/api-config';
import { parseSortExpression } from '@/hooks/saved-query-request';

/** Input parameters for `zz_lead_probe` (none declared). */
export type ZzLeadProbeInput = Record<string, never>;

/** Single row in the `zz_lead_probe` result set.
 *  (Unwrapped from the saved query's `rfe_response_list` output array.) */
export interface ZzLeadProbeRow {
  /** ID */
  id: string;
  /** Round */
  round?: number;
}

export const ZZ_LEAD_PROBE_NAME = "zz_lead_probe";
export const ZZ_LEAD_PROBE_IS_SINGLE = false as const;
export const ZZ_LEAD_PROBE_APP_KEY = "aswathtestapp_6a67823a8fa7215710927dbc";

export interface ExecuteZzLeadProbeOptions {
  /** Zero-based page index (body `page`, offset mode). */
  page?: number;
  /** Page size (body `page.size`). */
  pageSize?: number;
  /** Sort: comma-separated, `-` prefix for descending (e.g. 'status,-balance'). Body `sort`. */
  sort?: string;
  /** CEL filter expression (body `filterExpression`). */
  filter?: string;
}

/**
 * Execute the `zz_lead_probe` saved query. Read-only.
 */
export async function executeZzLeadProbe(
  input?: ZzLeadProbeInput,
  options?: ExecuteZzLeadProbeOptions,
): Promise<ZzLeadProbeRow[]> {
  const headers = getDataHeaders(ZZ_LEAD_PROBE_APP_KEY || undefined);
  const params = new URLSearchParams();
  if (input) {
    for (const [k, v] of Object.entries(input)) {
      if (v === undefined || v === null) continue;
      if (k === '_page' || k === '_size' || k === '_sort' || k === '_filter') continue;
      params.set(k, String(v));
    }
  }
  const body: Record<string, unknown> = {};
  if (options?.page !== undefined || options?.pageSize !== undefined || options?.sort || options?.filter) {
    const size = options?.pageSize ?? 50;
    body.page = { mode: 'offset', position: String((options?.page ?? 0) * size), size };
    const sortRules = parseSortExpression(options?.sort);
    if (sortRules.length > 0) body.sort = sortRules;
    if (options?.filter) body.filterExpression = options.filter;
  }
  const qs = params.toString();
  const url = qs ? `/saved-queries/zz_lead_probe/execute?${qs}` : "/saved-queries/zz_lead_probe/execute";
  const response = await apiManager.post('data', url, body, headers);
  const data = response.data;
  if (Array.isArray(data)) return data as ZzLeadProbeRow[];
  if (data && typeof data === 'object') {
    const obj = data as Record<string, unknown>;
    if (Array.isArray(obj.data)) return obj.data as ZzLeadProbeRow[];
    const keys = Object.keys(obj);
    if (keys.length === 1 && Array.isArray(obj[keys[0]])) {
      return obj[keys[0]] as ZzLeadProbeRow[];
    }
  }
  return [] as ZzLeadProbeRow[];
}
