// AUTO-GENERATED by scripts/fetch-entities.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/entity
// Tenant scope: see TENANT_ID used at generation time.

/**
 * Card Template
 * A reusable card artwork template. Holds Fabric.js canvas documents for the front and back faces plus a thumbnail. Thumbnail is Json because a PNG data URL exceeds the 255 character check constraint on Text columns.
 */
export interface CardTemplate {
  /** ID */
  id: string;
  /** Active */
  active?: boolean;
  /** Artwork Back — Fabric.js canvas document for the back face. */
  artwork_back?: Record<string, unknown>;
  /** Artwork Front — Fabric.js canvas document for the front face. */
  artwork_front?: Record<string, unknown>;
  /** Category — Grouping shown in the picker, for example seasonal, loyalty or corporate. */
  category?: string;
  /** Created At */
  created_at?: string;
  /** Description */
  description?: string;
  /** Name */
  name?: string;
  /** Spec — Build parameters this template reproduces, keyed by card_spec column
   *  name. Never carries bin/ica/preprint_bin: those identify the issuer, not the
   *  card build. */
  spec?: Record<string, unknown>;
  /** Thumbnail — PNG data URL for the picker, shaped {dataUrl}. Json because Text is capped at 255 characters. */
  thumbnail?: Record<string, unknown>;
}

export const CARD_TEMPLATE_APP_KEY = "aswathtestapp_6a67823a8fa7215710927dbc";

export type CardTemplateSchema = { 'card_template': CardTemplate };

/**
 * Field-level validation declared in Phoenix for `card_template`.
 * Use as DEFAULT UI constraints when building a form for this entity
 * (mark required fields, set maxLength / min / max, apply regex / oneOf).
 * Only fields that are required or carry a constraint are listed.
 */
export const CARD_TEMPLATE_FIELD_CONSTRAINTS = {
  id: { required: true },
} as const;
