// AUTO-GENERATED by scripts/fetch-entities.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/entity
// Tenant scope: see TENANT_ID used at generation time.

import type { Party } from '@/types/entities/aswathtestapp_6a67823a8fa7215710927dbc/party';
import type { TqInstance } from '@/types/entities/aswathtestapp_6a67823a8fa7215710927dbc/tq_instance';

/**
 * Orders
 * The central order table (merchant or supplier order, same table).
 */
export interface Orders {
  /** Id — PK */
  id: string;
  /** Bill From Id */
  bill_from_id?: Party;
  /** Bill To Id */
  bill_to_id?: Party;
  /** Bill When Shipped */
  bill_when_shipped?: boolean;
  /** Buyer Party Id */
  buyer_party_id?: Party;
  /** Created At */
  created_at?: string;
  /** Created By */
  created_by?: unknown;
  /** Last Modified At */
  last_modified_at?: string;
  /** Last Modified By */
  last_modified_by?: unknown;
  /** Order Brief */
  order_brief?: string;
  /** Order Code */
  order_code?: string;
  /** Order Kind */
  order_kind?: string;
  /** Order Type */
  order_type?: string;
  /** Po Required */
  po_required?: boolean;
  /** Requested Delivery */
  requested_delivery?: string;
  /** Rev */
  rev?: number;
  /** Seller Party Id */
  seller_party_id?: Party;
  /** Source Order Id */
  source_order_id?: Orders;
  /** Status */
  status?: Record<string, unknown>;
  /** TQ Instance */
  tq_instance?: TqInstance;
}

export const ORDERS_APP_KEY = "aswathtestapp_6a67823a8fa7215710927dbc";

export type OrdersSchema = { 'orders': Orders };

/**
 * Field-level validation declared in Phoenix for `orders`.
 * Use as DEFAULT UI constraints when building a form for this entity
 * (mark required fields, set maxLength / min / max, apply regex / oneOf).
 * Only fields that are required or carry a constraint are listed.
 */
export const ORDERS_FIELD_CONSTRAINTS = {
  id: { required: true },
} as const;
