// AUTO-GENERATED by scripts/fetch-entities.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/entity
// Tenant scope: see TENANT_ID used at generation time.

import type { Orders } from '@/types/entities/aswathtestapp_6a67823a8fa7215710927dbc/orders';

/**
 * Order Line
 * One line of an order: item snapshot, qty, agreed unit price.
 */
export interface OrderLine {
  /** Id — PK */
  id: string;
  /** Item — Item snapshot (JSON) at line creation */
  item?: Record<string, unknown>;
  /** Order Id — FK -> Order */
  order_id?: Orders;
  /** Qty — Ordered quantity */
  qty?: number;
  /** Unit Price — Unit price */
  unit_price?: number;
  /** Uom — Unit of measure */
  uom?: string;
}

export const ORDER_LINE_APP_KEY = "aswathtestapp_6a67823a8fa7215710927dbc";

export type OrderLineSchema = { 'order_line': OrderLine };

/**
 * Field-level validation declared in Phoenix for `order_line`.
 * Use as DEFAULT UI constraints when building a form for this entity
 * (mark required fields, set maxLength / min / max, apply regex / oneOf).
 * Only fields that are required or carry a constraint are listed.
 */
export const ORDER_LINE_FIELD_CONSTRAINTS = {
  id: { required: true },
} as const;
