// AUTO-GENERATED by scripts/fetch-entities.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/entity
// Tenant scope: see TENANT_ID used at generation time.

import type { Party } from '@/types/entities/aswathtestapp_6a67823a8fa7215710927dbc/party';

/**
 * Party Role
 * A party's role in a context (e.g. sourcing:responder).
 */
export interface PartyRole {
  /** Id — PK */
  id: string;
  /** Party — FK -> Party */
  party?: Party;
  /** Role — e.g. sourcing:responder */
  role?: string;
  /** Scope — Optional scoping note */
  scope?: string;
}

export const PARTY_ROLE_APP_KEY = "aswathtestapp_6a67823a8fa7215710927dbc";

export type PartyRoleSchema = { 'party_role': PartyRole };

/**
 * Field-level validation declared in Phoenix for `party_role`.
 * Use as DEFAULT UI constraints when building a form for this entity
 * (mark required fields, set maxLength / min / max, apply regex / oneOf).
 * Only fields that are required or carry a constraint are listed.
 */
export const PARTY_ROLE_FIELD_CONSTRAINTS = {
  id: { required: true },
} as const;
