// AUTO-GENERATED by scripts/fetch-entities.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/entity
// Tenant scope: see TENANT_ID used at generation time.

import type { PricingTemplate } from '@/types/entities/aswathtestapp_6a67823a8fa7215710927dbc/pricing_template';

/**
 * Pricing Template Role
 * One margin row per component role within a pricing template.
 */
export interface PricingTemplateRole {
  /** ID */
  id: string;
  /** Component Role — card, carrier, features or setup */
  component_role?: string;
  /** Margin Bps — Margin for this role in basis points. 1500 = 15%. */
  margin_bps?: number;
  /** Template — FK -> Pricing Template */
  template?: PricingTemplate;
}

export const PRICING_TEMPLATE_ROLE_APP_KEY = "aswathtestapp_6a67823a8fa7215710927dbc";

export type PricingTemplateRoleSchema = { 'pricing_template_role': PricingTemplateRole };

/**
 * Field-level validation declared in Phoenix for `pricing_template_role`.
 * Use as DEFAULT UI constraints when building a form for this entity
 * (mark required fields, set maxLength / min / max, apply regex / oneOf).
 * Only fields that are required or carry a constraint are listed.
 */
export const PRICING_TEMPLATE_ROLE_FIELD_CONSTRAINTS = {
  id: { required: true },
} as const;
