// AUTO-GENERATED by scripts/fetch-entities.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/entity
// Tenant scope: see TENANT_ID used at generation time.

import type { Orders } from '@/types/entities/aswathtestapp_6a67823a8fa7215710927dbc/orders';
import type { Party } from '@/types/entities/aswathtestapp_6a67823a8fa7215710927dbc/party';

/**
 * RFE
 * An RFE to one supplier.
 */
export interface Rfe {
  /** Id — PK */
  id: string;
  /** Demand Order — FK -> Orders */
  demand_order?: Orders;
  /** Respond By — The quotes-due date */
  respond_by?: string;
  /** Sent At — When the RFE was sent */
  sent_at?: string;
  /** Setup Instructions — Snapshot from order RFE setup */
  setup_instructions?: string;
  /** Status — draft / sent / responded / returned / outdated / cancelled */
  status?: string;
  /** Supplier — FK -> Party */
  supplier?: Party;
}

export const RFE_APP_KEY = "aswathtestapp_6a67823a8fa7215710927dbc";

export type RfeSchema = { 'rfe': Rfe };

/**
 * Field-level validation declared in Phoenix for `rfe`.
 * Use as DEFAULT UI constraints when building a form for this entity
 * (mark required fields, set maxLength / min / max, apply regex / oneOf).
 * Only fields that are required or carry a constraint are listed.
 */
export const RFE_FIELD_CONSTRAINTS = {
  id: { required: true },
} as const;
