// AUTO-GENERATED by scripts/fetch-entities.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/entity
// Tenant scope: see TENANT_ID used at generation time.

import type { RfeLineTier } from '@/types/entities/aswathtestapp_6a67823a8fa7215710927dbc/rfe_line_tier';
import type { RfeResponse } from '@/types/entities/aswathtestapp_6a67823a8fa7215710927dbc/rfe_response';

/**
 * RFE Response Line
 */
export interface RfeResponseLine {
  /** ID */
  id: string;
  /** Cost Micros */
  cost_micros?: number;
  /** Declined */
  declined?: boolean;
  /** Note */
  note?: string;
  /** Response */
  response?: RfeResponse;
  /** Tier */
  tier?: RfeLineTier;
  /** Uncosted */
  uncosted?: boolean;
}

export const RFE_RESPONSE_LINE_APP_KEY = "aswathtestapp_6a67823a8fa7215710927dbc";

export type RfeResponseLineSchema = { 'rfe_response_line': RfeResponseLine };

/**
 * Field-level validation declared in Phoenix for `rfe_response_line`.
 * Use as DEFAULT UI constraints when building a form for this entity
 * (mark required fields, set maxLength / min / max, apply regex / oneOf).
 * Only fields that are required or carry a constraint are listed.
 */
export const RFE_RESPONSE_LINE_FIELD_CONSTRAINTS = {
  id: { required: true },
} as const;
