// AUTO-GENERATED by scripts/fetch-entities.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/entity
// Tenant scope: see TENANT_ID used at generation time.

import type { Party } from '@/types/entities/aswathtestapp_6a67823a8fa7215710927dbc/party';

/**
 * Supplier Capacity
 * A supplier's declared monthly capacity.
 */
export interface SupplierCapacity {
  /** Id — PK */
  id: string;
  /** Committed — Already committed units */
  committed?: number;
  /** Declared — Declared units for the period */
  declared?: number;
  /** Period — Period key e.g. 2026-08 */
  period?: string;
  /** Supplier — FK -> Party */
  supplier?: Party;
}

export const SUPPLIER_CAPACITY_APP_KEY = "aswathtestapp_6a67823a8fa7215710927dbc";

export type SupplierCapacitySchema = { 'supplier_capacity': SupplierCapacity };

/**
 * Field-level validation declared in Phoenix for `supplier_capacity`.
 * Use as DEFAULT UI constraints when building a form for this entity
 * (mark required fields, set maxLength / min / max, apply regex / oneOf).
 * Only fields that are required or carry a constraint are listed.
 */
export const SUPPLIER_CAPACITY_FIELD_CONSTRAINTS = {
  id: { required: true },
} as const;
