// AUTO-GENERATED by scripts/fetch-entities.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/entity
// Tenant scope: see TENANT_ID used at generation time.

import type { Party } from '@/types/entities/aswathtestapp_6a67823a8fa7215710927dbc/party';

/**
 * Supplier Cert
 * Certifications driving sourcing eligibility.
 */
export interface SupplierCert {
  /** Id — PK */
  id: string;
  /** Certification — Certification name */
  certification?: string;
  /** Supplier — FK -> Party */
  supplier?: Party;
  /** Valid Until — Expiry date */
  valid_until?: string;
}

export const SUPPLIER_CERT_APP_KEY = "aswathtestapp_6a67823a8fa7215710927dbc";

export type SupplierCertSchema = { 'supplier_cert': SupplierCert };

/**
 * Field-level validation declared in Phoenix for `supplier_cert`.
 * Use as DEFAULT UI constraints when building a form for this entity
 * (mark required fields, set maxLength / min / max, apply regex / oneOf).
 * Only fields that are required or carry a constraint are listed.
 */
export const SUPPLIER_CERT_FIELD_CONSTRAINTS = {
  id: { required: true },
} as const;
