// AUTO-GENERATED by scripts/fetch-entities.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/entity
// Tenant scope: see TENANT_ID used at generation time.

import type { TqStateDefinition } from '@/types/entities/aswathtestapp_6a67823a8fa7215710927dbc/tq_state_definition';

/**
 * TQ Sub Task Definition
 * [task-queue] A sub-task (stage). Order via previous_task/next_task.
 */
export interface TqSubTaskDefinition {
  /** Id — PK */
  id: string;
  /** Created At */
  created_at?: string;
  /** Created By */
  created_by?: unknown;
  /** Is Final — Ending stage */
  is_final?: boolean;
  /** Is Initial — Entry stage */
  is_initial?: boolean;
  /** Last Modified At */
  last_modified_at?: string;
  /** Last Modified By */
  last_modified_by?: unknown;
  /** Name — Sub-task name */
  name?: string;
  /** Next Task — N:1 -> next stage */
  next_task?: TqSubTaskDefinition;
  /** Previous Task — N:1 -> prior stage */
  previous_task?: TqSubTaskDefinition;
  /** States — 1:N -> allowed states */
  states?: TqStateDefinition[];
}

export const TQ_SUB_TASK_DEFINITION_APP_KEY = "aswathtestapp_6a67823a8fa7215710927dbc";

export type TqSubTaskDefinitionSchema = { 'tq_sub_task_definition': TqSubTaskDefinition };

/**
 * Field-level validation declared in Phoenix for `tq_sub_task_definition`.
 * Use as DEFAULT UI constraints when building a form for this entity
 * (mark required fields, set maxLength / min / max, apply regex / oneOf).
 * Only fields that are required or carry a constraint are listed.
 */
export const TQ_SUB_TASK_DEFINITION_FIELD_CONSTRAINTS = {
  id: { required: true },
} as const;
