/**
 * Pure helpers for the skills catalog codegen (`scripts/fetch-skills.ts`).
 *
 * "Skills" are the platform's AGENTS — the `skill-definition` component type.
 * The script makes ONE call to
 * `/api/internal/component-definitions-all/skill-definition` (tenant-wide,
 * every app's skill-definitions in a single response) and turns the raw rows
 * into:
 *   - `src/types/catalogs/skills.catalog.md`  — the agent-facing menu of the
 *     agents/skills available on the platform, grouped by app.
 *   - `src/types/skills.generated.ts` — a typed registry for app code
 *     (`SkillName` union + `SKILLS` / `SKILLS_BY_NAME` consts).
 *
 * These functions are kept free of `fs` / `fetch` so they can be unit-tested
 * with raw fixtures (the repo rule: extract + test pure logic). This mirrors
 * `related-screens-codegen.ts` exactly.
 */

/** Raw skill-definition row from `component-definitions-all/skill-definition`. */
export interface RawSkill {
  app_definition_key?: string;
  /** DTO variant of the app key (some endpoints send this instead). */
  target_app_definition_key?: string;
  app_definition?: string;
  name?: string;
  label?: string;
  description?: string;
  component_type?: string;
  sub_type?: string;
  tags?: string[] | null;
  [key: string]: unknown;
}

/** A normalized platform skill (agent). */
export interface Skill {
  appKey: string;
  appDefinition: string;
  /** Skill name = the identifier used to reference/invoke the agent. */
  name: string;
  label: string;
  description: string;
  subType: string;
  tags: string[];
}

/** All skills for one app. */
export interface SkillApp {
  appKey: string;
  appDefinition: string;
  skills: Skill[];
}

/** Prefer the DTO app key when present, else the internal-endpoint field. */
function skillAppKey(raw: RawSkill): string {
  return (raw.target_app_definition_key ?? raw.app_definition_key ?? '').trim();
}

/**
 * Normalize one raw skill-definition row. Returns `null` when the row isn't a
 * usable skill (no app key or no name → can't be referenced).
 */
export function normalizeSkill(raw: RawSkill | null | undefined): Skill | null {
  if (!raw) return null;
  const appKey = skillAppKey(raw);
  const name = (raw.name ?? '').trim();
  if (!appKey || !name) return null;

  return {
    appKey,
    appDefinition: (raw.app_definition ?? '').trim(),
    name,
    label: (raw.label ?? name).trim(),
    description: (raw.description ?? '').trim(),
    subType: (raw.sub_type ?? '').trim(),
    tags: Array.isArray(raw.tags) ? raw.tags.filter((t): t is string => typeof t === 'string') : [],
  };
}

/**
 * Build the grouped skills registry from raw skill-definition rows.
 *
 * @param rows       every skill from `component-definitions-all/skill-definition`
 * @param appKeys    the app_definition_keys to KEEP. When omitted/empty, all
 *   apps are kept.
 */
export function buildSkillApps(rows: RawSkill[], appKeys: string[] = []): SkillApp[] {
  const keep = new Set(appKeys.filter(Boolean));

  const byApp = new Map<string, SkillApp>();
  for (const row of rows) {
    const skill = normalizeSkill(row);
    if (!skill) continue;
    if (keep.size > 0 && !keep.has(skill.appKey)) continue;

    let app = byApp.get(skill.appKey);
    if (!app) {
      app = { appKey: skill.appKey, appDefinition: skill.appDefinition, skills: [] };
      byApp.set(skill.appKey, app);
    }
    app.skills.push(skill);
  }

  // Deterministic output: sort apps by key, skills by name; dedupe skills.
  const apps = [...byApp.values()].sort((a, b) => a.appKey.localeCompare(b.appKey));
  for (const app of apps) {
    const seen = new Set<string>();
    app.skills = app.skills
      .filter((s) => (seen.has(s.name) ? false : (seen.add(s.name), true)))
      .sort((a, b) => a.name.localeCompare(b.name));
  }
  return apps;
}

/** Flatten grouped apps back into a name-sorted skill list. */
export function flattenSkills(apps: SkillApp[]): Skill[] {
  return apps
    .flatMap((a) => a.skills)
    .sort((a, b) => a.name.localeCompare(b.name) || a.appKey.localeCompare(b.appKey));
}

/** Escape a cell value for a Markdown table. */
function mdCell(value: string): string {
  return value.replace(/\|/g, '\\|').replace(/\n/g, ' ').trim() || '—';
}

/** Render the agent-facing catalog markdown. */
export function renderSkillsCatalog(apps: SkillApp[]): string {
  const lines: string[] = [];
  lines.push('# Platform skills (agents)');
  lines.push('');
  lines.push('<!-- AUTO-GENERATED by scripts/fetch-skills.ts — do not edit by hand. -->');
  lines.push(
    '<!-- Source: Phoenix GET /api/internal/component-definitions-all/skill-definition -->',
  );
  lines.push('');
  lines.push(
    'Agents (skill-definitions) configured on the platform for this tenant,',
    'grouped by application. Names + types come from the typed registry at',
    '`src/types/skills.generated.ts` (`SkillName`, `SKILLS`, `SKILLS_BY_NAME`).',
  );
  lines.push('');

  if (apps.length === 0) {
    lines.push('_No platform skills found._');
    lines.push('');
    return lines.join('\n');
  }

  for (const app of apps) {
    lines.push(`## ${app.appDefinition || app.appKey}`);
    lines.push('');
    lines.push(`- appKey: \`${app.appKey}\``);
    lines.push('');
    lines.push('| Skill | Label | Description | Type | Tags |');
    lines.push('|-------|-------|-------------|------|------|');
    for (const s of app.skills) {
      const tags = s.tags.length === 0 ? '—' : s.tags.join(', ');
      lines.push(
        `| \`${mdCell(s.name)}\` | ${mdCell(s.label)} | ${mdCell(s.description)} | ${mdCell(s.subType)} | ${mdCell(tags)} |`,
      );
    }
    lines.push('');
  }
  return lines.join('\n');
}

/** Render the typed registry app code imports (`SkillName`, `SKILLS`, …). */
export function renderSkillsGenerated(apps: SkillApp[]): string {
  const skills = flattenSkills(apps);
  const lines: string[] = [];
  lines.push('/* eslint-disable */');
  lines.push('// AUTO-GENERATED by scripts/fetch-skills.ts - do not edit by hand.');
  lines.push('// Source: Phoenix GET /api/internal/component-definitions-all/skill-definition');
  lines.push('// Regenerated on every workspace bootstrap.');
  lines.push('');
  lines.push('export interface SkillEntry {');
  lines.push('  appKey: string;');
  lines.push('  appDefinition: string;');
  lines.push('  name: string;');
  lines.push('  label: string;');
  lines.push('  description: string;');
  lines.push('  subType: string;');
  lines.push('  tags: string[];');
  lines.push('}');
  lines.push('');

  if (skills.length === 0) {
    lines.push('/** All known skill names (typed union). */');
    lines.push('export type SkillName = never;');
    lines.push('');
    lines.push('/** Every platform skill (agent) for this tenant. */');
    lines.push('export const SKILLS: SkillEntry[] = [];');
    lines.push('');
    lines.push('/** Map of skill name → its app_definition_key. */');
    lines.push('export const SKILL_APP_KEYS: Record<string, string> = {};');
    lines.push('');
    lines.push('/** Flat lookup: skill name → entry. */');
    lines.push('export const SKILLS_BY_NAME: Record<string, SkillEntry> = {};');
    lines.push('');
    return lines.join('\n');
  }

  const namesUnion = skills.map((s) => JSON.stringify(s.name)).join(' | ');
  lines.push('/** All known skill names (typed union). */');
  lines.push(`export type SkillName = ${namesUnion};`);
  lines.push('');
  lines.push('/** Every platform skill (agent) for this tenant. */');
  lines.push(`export const SKILLS: SkillEntry[] = ${JSON.stringify(skills, null, 2)};`);
  lines.push('');
  lines.push('/** Map of skill name → its app_definition_key. */');
  lines.push('export const SKILL_APP_KEYS: Record<SkillName, string> = {');
  // A skill `name` can exist in two apps (a cross-app collision). One object
  // key per name, or the emitted literal has duplicate keys (a TS error +
  // last-wins at runtime). Fold to the LAST occurrence — matching JS runtime
  // last-wins and SKILLS_BY_NAME below, which the loop overwrites in order.
  const lastAppKeyByName = new Map<string, string>();
  for (const s of skills) lastAppKeyByName.set(s.name, s.appKey);
  const emitted = new Set<string>();
  for (const s of skills) {
    if (emitted.has(s.name)) continue;
    emitted.add(s.name);
    const appKey = lastAppKeyByName.get(s.name) ?? s.appKey;
    lines.push(`  ${JSON.stringify(s.name)}: ${JSON.stringify(appKey)},`);
  }
  lines.push('};');
  lines.push('');
  lines.push('/** Flat lookup: skill name → entry. */');
  lines.push('export const SKILLS_BY_NAME: Record<string, SkillEntry> = {};');
  lines.push('for (const skill of SKILLS) {');
  lines.push('  SKILLS_BY_NAME[skill.name] = skill;');
  lines.push('}');
  lines.push('');
  return lines.join('\n');
}
