// AUTO-GENERATED by scripts/fetch-saved-queries.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/saved-query
// Saved query: allocation_create ("Create allocation row")
// Type: dynamic  |  Single output: true  |  App: aswathtestapp_6a67823a8fa7215710927dbc
// Inserts one allocation row. kind is line for a quantity allocation or carve_out for a component material awarded elsewhere. Free text in exceptionNote so all params go in the JSON body: orderId, orderLineId, supplierId, assemblerId, kind, qty, unitCostMicros, componentRole, exceptionNote, createdAt. Pass null for assemblerId and componentRole on a plain line row.

import { apiManager } from '@/services/api-manager';
import { getDataHeaders } from '@/config/api-config';

/** Input parameters for `allocation_create` (write — sent as a flat JSON body). */
export interface AllocationCreateInput {
  assemblerId: string;
  componentRole: string;
  createdAt: string;
  exceptionNote: string;
  kind: string;
  orderId: string;
  orderLineId: string;
  qty: string;
  supplierId: string;
  unitCostMicros: string;
}

/** Row returned by `allocation_create` (write).
 *  (Unwrapped from the saved query's `line_allocation` output.) */
export interface AllocationCreateResult {
  /** ID */
  id: string;
  /** Component Role */
  component_role?: string;
  /** Exception Note */
  exception_note?: string;
  /** Kind */
  kind?: string;
  /** Qty */
  qty?: number;
  /** Unit Cost Micros */
  unit_cost_micros?: number;
}

export const ALLOCATION_CREATE_NAME = "allocation_create";
export const ALLOCATION_CREATE_IS_SINGLE = true as const;
export const ALLOCATION_CREATE_APP_KEY = "aswathtestapp_6a67823a8fa7215710927dbc";

/**
 * Execute the `allocation_create` saved query. WRITE (insert).
 * Inputs are sent as a flat JSON body; returns the affected row(s).
 */
export async function executeAllocationCreate(
  input: AllocationCreateInput,
): Promise<AllocationCreateResult> {
  const headers = getDataHeaders(ALLOCATION_CREATE_APP_KEY || undefined);
  const response = await apiManager.post('data', "/saved-queries/allocation_create/execute", input, headers);
  return response.data as AllocationCreateResult;
}
