// AUTO-GENERATED by scripts/fetch-saved-queries.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/saved-query
// Saved query: card_variant_create ("Create card variant")
// Type: dynamic  |  Single output: true  |  App: aswathtestapp_6a67823a8fa7215710927dbc
// Adds one variation to an order. delta is a whole JSON object of only the fields that differ from the base card. JSON body: variantId, orderId, cardSpecId, label, delta, qty, dueDate, createdAt.

import { apiManager } from '@/services/api-manager';
import { getDataHeaders } from '@/config/api-config';

/** Input parameters for `card_variant_create` (write — sent as a flat JSON body). */
export interface CardVariantCreateInput {
  cardSpecId: string;
  createdAt: string;
  delta: string;
  dueDate: string;
  label: string;
  orderId: string;
  qty: string;
  variantId: string;
}

/** Row returned by `card_variant_create` (write).
 *  (Unwrapped from the saved query's `card_variant` output.) */
export interface CardVariantCreateResult {
  /** ID */
  id: string;
  /** Approved */
  approved?: boolean;
  /** Label */
  label?: string;
  /** Qty */
  qty?: number;
}

export const CARD_VARIANT_CREATE_NAME = "card_variant_create";
export const CARD_VARIANT_CREATE_IS_SINGLE = true as const;
export const CARD_VARIANT_CREATE_APP_KEY = "aswathtestapp_6a67823a8fa7215710927dbc";

/**
 * Execute the `card_variant_create` saved query. WRITE (insert).
 * Inputs are sent as a flat JSON body; returns the affected row(s).
 */
export async function executeCardVariantCreate(
  input: CardVariantCreateInput,
): Promise<CardVariantCreateResult> {
  const headers = getDataHeaders(CARD_VARIANT_CREATE_APP_KEY || undefined);
  const response = await apiManager.post('data', "/saved-queries/card_variant_create/execute", input, headers);
  return response.data as CardVariantCreateResult;
}
