// AUTO-GENERATED by scripts/fetch-saved-queries.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/saved-query
// Saved query: card_spec_create ("card_spec_create")
// Type: common_table_expression  |  Single output: true  |  App: aswathtestapp_6a67823a8fa7215710927dbc
// Design-a-card: creates the whole chain in ONE call — item (Card) -> item_revision (rev 1, draft) -> card_spec -> order_line linked to the order. The CALLER generates itemRevId (a UUID) and passes it in, so order_line.item's item_rev_id is written from a PLAIN param and lands as clean JSON (a CTE step-ref like $rev.id would be SQL-quoted inside a JSON value). Params: orderId, buyerPartyId, itemRevId, cardName, cardDescription, qty. Returns the order_line id.

import { apiManager } from '@/services/api-manager';
import { getDataHeaders } from '@/config/api-config';

/** Input parameters for `card_spec_create` (write — sent as a flat JSON body). */
export interface CardSpecCreateInput {
  buyerPartyId: string;
  cardDescription: string;
  cardName: string;
  it: string;
  itemRevId: string;
  orderId: string;
  qty: string;
}

/** Row returned by `card_spec_create` (write — the affected row's id). */
export interface CardSpecCreateResult {
  id: string;
}

export const CARD_SPEC_CREATE_NAME = "card_spec_create";
export const CARD_SPEC_CREATE_IS_SINGLE = true as const;
export const CARD_SPEC_CREATE_APP_KEY = "aswathtestapp_6a67823a8fa7215710927dbc";

/**
 * Execute the `card_spec_create` saved query. WRITE (insert).
 * Inputs are sent as a flat JSON body; returns the affected row(s).
 */
export async function executeCardSpecCreate(
  input: CardSpecCreateInput,
): Promise<CardSpecCreateResult> {
  const headers = getDataHeaders(CARD_SPEC_CREATE_APP_KEY || undefined);
  const response = await apiManager.post('data', "/saved-queries/card_spec_create/execute", input, headers);
  return response.data as CardSpecCreateResult;
}
