// AUTO-GENERATED by scripts/fetch-saved-queries.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/saved-query
// Saved query: card_template_create ("Create card template")
// Type: dynamic  |  Single output: true  |  App: aswathtestapp_6a67823a8fa7215710927dbc
// Saves the current canvas as a reusable template. thumbnail is a JSON object shaped {dataUrl} because Text is capped at 255 characters. Pass whole JSON objects for thumbnail, artworkFront and artworkBack, never $body params nested inside a jsonb literal. JSON body: templateId, name, description, category, thumbnail, artworkFront, artworkBack, createdAt.

import { apiManager } from '@/services/api-manager';
import { getDataHeaders } from '@/config/api-config';

/** Input parameters for `card_template_create` (write — sent as a flat JSON body). */
export interface CardTemplateCreateInput {
  artworkBack: string;
  artworkFront: string;
  category: string;
  createdAt: string;
  description: string;
  name: string;
  spec: Record<string, unknown>;
  templateId: string;
  thumbnail: string;
}

/** Row returned by `card_template_create` (write).
 *  (Unwrapped from the saved query's `card_template` output.) */
export interface CardTemplateCreateResult {
  /** ID */
  id: string;
  /** Category */
  category?: string;
  /** Name */
  name?: string;
}

export const CARD_TEMPLATE_CREATE_NAME = "card_template_create";
export const CARD_TEMPLATE_CREATE_IS_SINGLE = true as const;
export const CARD_TEMPLATE_CREATE_APP_KEY = "aswathtestapp_6a67823a8fa7215710927dbc";

/**
 * Execute the `card_template_create` saved query. WRITE (insert).
 * Inputs are sent as a flat JSON body; returns the affected row(s).
 */
export async function executeCardTemplateCreate(
  input: CardTemplateCreateInput,
): Promise<CardTemplateCreateResult> {
  const headers = getDataHeaders(CARD_TEMPLATE_CREATE_APP_KEY || undefined);
  const response = await apiManager.post('data', "/saved-queries/card_template_create/execute", input, headers);
  return response.data as CardTemplateCreateResult;
}
