// AUTO-GENERATED by scripts/fetch-saved-queries.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/saved-query
// Saved query: card_revs ("card_revs")
// Type: dynamic  |  Single output: false  |  App: aswathtestapp_6a67823a8fa7215710927dbc
// Live card revision status/name for the Specs table. Param: revIds (comma-separated item_revision ids - the platform splits a comma-separated query param into an array, which is what includes() needs). Returns id, rev, status and the parent item's name. Use with order_cards: order_cards gives the rows + item_rev_id, this gives the LIVE status/name so the UI never depends on the order_line.item JSON snapshot.

import { apiManager } from '@/services/api-manager';
import { getDataHeaders } from '@/config/api-config';
import { parseSortExpression } from '@/hooks/saved-query-request';

/** Input parameters for `card_revs`. */
export interface CardRevsInput {
  revIds: string;
}

/** Single row in the `card_revs` result set. */
export interface CardRevsRow {
  [key: string]: unknown;
}

export const CARD_REVS_NAME = "card_revs";
export const CARD_REVS_IS_SINGLE = false as const;
export const CARD_REVS_APP_KEY = "aswathtestapp_6a67823a8fa7215710927dbc";

export interface ExecuteCardRevsOptions {
  /** Zero-based page index (body `page`, offset mode). */
  page?: number;
  /** Page size (body `page.size`). */
  pageSize?: number;
  /** Sort: comma-separated, `-` prefix for descending (e.g. 'status,-balance'). Body `sort`. */
  sort?: string;
  /** CEL filter expression (body `filterExpression`). */
  filter?: string;
}

/**
 * Execute the `card_revs` saved query. Read-only.
 */
export async function executeCardRevs(
  input: CardRevsInput,
  options?: ExecuteCardRevsOptions,
): Promise<CardRevsRow[]> {
  const headers = getDataHeaders(CARD_REVS_APP_KEY || undefined);
  const params = new URLSearchParams();
  if (input) {
    for (const [k, v] of Object.entries(input)) {
      if (v === undefined || v === null) continue;
      if (k === '_page' || k === '_size' || k === '_sort' || k === '_filter') continue;
      params.set(k, String(v));
    }
  }
  const body: Record<string, unknown> = {};
  if (options?.page !== undefined || options?.pageSize !== undefined || options?.sort || options?.filter) {
    const size = options?.pageSize ?? 50;
    body.page = { mode: 'offset', position: String((options?.page ?? 0) * size), size };
    const sortRules = parseSortExpression(options?.sort);
    if (sortRules.length > 0) body.sort = sortRules;
    if (options?.filter) body.filterExpression = options.filter;
  }
  const qs = params.toString();
  const url = qs ? `/saved-queries/card_revs/execute?${qs}` : "/saved-queries/card_revs/execute";
  const response = await apiManager.post('data', url, body, headers);
  const data = response.data;
  if (Array.isArray(data)) return data as CardRevsRow[];
  if (data && typeof data === 'object') {
    const obj = data as Record<string, unknown>;
    if (Array.isArray(obj.data)) return obj.data as CardRevsRow[];
    const keys = Object.keys(obj);
    if (keys.length === 1 && Array.isArray(obj[keys[0]])) {
      return obj[keys[0]] as CardRevsRow[];
    }
  }
  return [] as CardRevsRow[];
}
