// AUTO-GENERATED by scripts/fetch-saved-queries.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/saved-query
// Saved query: component_item_create ("Component Item Create")
// Type: dynamic  |  Single output: true  |  App: aswathtestapp_6a67823a8fa7215710927dbc
// Step 1 of 3 for adding a component line. Creates the item carrying the component role. JSON body: name, componentRole, itemType, ownerPartyId. Body transport because name is free text.

import { apiManager } from '@/services/api-manager';
import { getDataHeaders } from '@/config/api-config';

/** Input parameters for `component_item_create` (write — sent as a flat JSON body). */
export interface ComponentItemCreateInput {
  componentRole: string;
  itemType: string;
  name: string;
  ownerPartyId: string;
}

/** Row returned by `component_item_create` (write).
 *  (Unwrapped from the saved query's `item` output.) */
export interface ComponentItemCreateResult {
  /** Id */
  id?: string;
  /** Component Role */
  component_role?: string;
  /** Name */
  name?: string;
}

export const COMPONENT_ITEM_CREATE_NAME = "component_item_create";
export const COMPONENT_ITEM_CREATE_IS_SINGLE = true as const;
export const COMPONENT_ITEM_CREATE_APP_KEY = "aswathtestapp_6a67823a8fa7215710927dbc";

/**
 * Execute the `component_item_create` saved query. WRITE (insert).
 * Inputs are sent as a flat JSON body; returns the affected row(s).
 */
export async function executeComponentItemCreate(
  input: ComponentItemCreateInput,
): Promise<ComponentItemCreateResult> {
  const headers = getDataHeaders(COMPONENT_ITEM_CREATE_APP_KEY || undefined);
  const response = await apiManager.post('data', "/saved-queries/component_item_create/execute", input, headers);
  return response.data as ComponentItemCreateResult;
}
