// AUTO-GENERATED by scripts/fetch-saved-queries.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/saved-query
// Saved query: order_rfes ("Order RFEs")
// Type: dynamic  |  Single output: false  |  App: aswathtestapp_6a67823a8fa7215710927dbc
// RFEs already sent for an order, with supplier name and status. Param: orderId.

import { apiManager } from '@/services/api-manager';
import { getDataHeaders } from '@/config/api-config';
import { parseSortExpression } from '@/hooks/saved-query-request';

/** Input parameters for `order_rfes`. */
export interface OrderRfesInput {
  orderId: string;
}

/** Single row in the `order_rfes` result set.
 *  (Unwrapped from the saved query's `rfe_list` output array.) */
export interface OrderRfesRow {
  /** Id */
  id?: string;
  /** Respond By */
  respond_by?: string;
  /** Sent At */
  sent_at?: string;
  /** Setup Instructions */
  setup_instructions?: string;
  /** Status */
  status?: string;
  /** Supplier */
  supplier?: {
      /** Id */
      id?: string;
      /** Name */
      name?: string;
    };
}

export const ORDER_RFES_NAME = "order_rfes";
export const ORDER_RFES_IS_SINGLE = false as const;
export const ORDER_RFES_APP_KEY = "aswathtestapp_6a67823a8fa7215710927dbc";

export interface ExecuteOrderRfesOptions {
  /** Zero-based page index (body `page`, offset mode). */
  page?: number;
  /** Page size (body `page.size`). */
  pageSize?: number;
  /** Sort: comma-separated, `-` prefix for descending (e.g. 'status,-balance'). Body `sort`. */
  sort?: string;
  /** CEL filter expression (body `filterExpression`). */
  filter?: string;
}

/**
 * Execute the `order_rfes` saved query. Read-only.
 */
export async function executeOrderRfes(
  input: OrderRfesInput,
  options?: ExecuteOrderRfesOptions,
): Promise<OrderRfesRow[]> {
  const headers = getDataHeaders(ORDER_RFES_APP_KEY || undefined);
  const params = new URLSearchParams();
  if (input) {
    for (const [k, v] of Object.entries(input)) {
      if (v === undefined || v === null) continue;
      if (k === '_page' || k === '_size' || k === '_sort' || k === '_filter') continue;
      params.set(k, String(v));
    }
  }
  const body: Record<string, unknown> = {};
  if (options?.page !== undefined || options?.pageSize !== undefined || options?.sort || options?.filter) {
    const size = options?.pageSize ?? 50;
    body.page = { mode: 'offset', position: String((options?.page ?? 0) * size), size };
    const sortRules = parseSortExpression(options?.sort);
    if (sortRules.length > 0) body.sort = sortRules;
    if (options?.filter) body.filterExpression = options.filter;
  }
  const qs = params.toString();
  const url = qs ? `/saved-queries/order_rfes/execute?${qs}` : "/saved-queries/order_rfes/execute";
  const response = await apiManager.post('data', url, body, headers);
  const data = response.data;
  if (Array.isArray(data)) return data as OrderRfesRow[];
  if (data && typeof data === 'object') {
    const obj = data as Record<string, unknown>;
    if (Array.isArray(obj.data)) return obj.data as OrderRfesRow[];
    const keys = Object.keys(obj);
    if (keys.length === 1 && Array.isArray(obj[keys[0]])) {
      return obj[keys[0]] as OrderRfesRow[];
    }
  }
  return [] as OrderRfesRow[];
}
