// AUTO-GENERATED by scripts/fetch-saved-queries.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/saved-query
// Saved query: order_link_tq ("order_link_tq")
// Type: common_table_expression  |  Single output: true  |  App: aswathtestapp_6a67823a8fa7215710927dbc
// Links a Task Queue (TQ) instance back to its order on THIS app's own LOCAL orders entity — NO entityAppKey/target app. $body.<field> JSON-body write contract via useSavedQueryMutation. Updates tq_instance = {id: $body.instanceId} AND status = $body.status (a jsonb snapshot of the workflow's initial state, e.g. {"state":"Order Received"} — written here because this tenant's saved-query output layer sometimes strips the deep nested tq_instance.current_status.tq_state_definition.state projection on reads, so the Orders list's Status column needs a guaranteed-present fallback) where id == $body.orderId. Called from the Orders screen's Create Order dialog right after order_create + tq_create succeed, passing { orderId, instanceId, status: { state: <initial state name> } }.

import { apiManager } from '@/services/api-manager';
import { getDataHeaders } from '@/config/api-config';

/** Input parameters for `order_link_tq` (write — sent as a flat JSON body). */
export interface OrderLinkTqInput {
  instanceId: string;
  orderId: string;
  status: string;
}

/** Row returned by `order_link_tq` (write).
 *  (Unwrapped from the saved query's `orders` output.) */
export interface OrderLinkTqResult {
  /** Id */
  id?: string;
}

export const ORDER_LINK_TQ_NAME = "order_link_tq";
export const ORDER_LINK_TQ_IS_SINGLE = true as const;
export const ORDER_LINK_TQ_APP_KEY = "aswathtestapp_6a67823a8fa7215710927dbc";

/**
 * Execute the `order_link_tq` saved query. WRITE (update).
 * Inputs are sent as a flat JSON body; returns the affected row(s).
 */
export async function executeOrderLinkTq(
  input: OrderLinkTqInput,
): Promise<OrderLinkTqResult[]> {
  const headers = getDataHeaders(ORDER_LINK_TQ_APP_KEY || undefined);
  const response = await apiManager.post('data', "/saved-queries/order_link_tq/execute", input, headers);
  return response.data as OrderLinkTqResult[];
}
