// AUTO-GENERATED by scripts/fetch-saved-queries.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/saved-query
// Saved query: order_margin_overrides ("Order margin overrides")
// Type: dynamic  |  Single output: false  |  App: aswathtestapp_6a67823a8fa7215710927dbc
// Active per-order margin overrides for one order. Param: orderId.

import { apiManager } from '@/services/api-manager';
import { getDataHeaders } from '@/config/api-config';
import { parseSortExpression } from '@/hooks/saved-query-request';

/** Input parameters for `order_margin_overrides`. */
export interface OrderMarginOverridesInput {
  orderId: string;
}

/** Single row in the `order_margin_overrides` result set.
 *  (Unwrapped from the saved query's `margin_override_list` output array.) */
export interface OrderMarginOverridesRow {
  /** ID */
  id: string;
  /** Component Role */
  component_role?: string;
  /** Created At */
  created_at?: string;
  /** From Bps */
  from_bps?: number;
  /** Margin Bps */
  margin_bps?: number;
  /** Reason */
  reason?: string;
  /** Scenario */
  scenario?: string;
}

export const ORDER_MARGIN_OVERRIDES_NAME = "order_margin_overrides";
export const ORDER_MARGIN_OVERRIDES_IS_SINGLE = false as const;
export const ORDER_MARGIN_OVERRIDES_APP_KEY = "aswathtestapp_6a67823a8fa7215710927dbc";

export interface ExecuteOrderMarginOverridesOptions {
  /** Zero-based page index (body `page`, offset mode). */
  page?: number;
  /** Page size (body `page.size`). */
  pageSize?: number;
  /** Sort: comma-separated, `-` prefix for descending (e.g. 'status,-balance'). Body `sort`. */
  sort?: string;
  /** CEL filter expression (body `filterExpression`). */
  filter?: string;
}

/**
 * Execute the `order_margin_overrides` saved query. Read-only.
 */
export async function executeOrderMarginOverrides(
  input: OrderMarginOverridesInput,
  options?: ExecuteOrderMarginOverridesOptions,
): Promise<OrderMarginOverridesRow[]> {
  const headers = getDataHeaders(ORDER_MARGIN_OVERRIDES_APP_KEY || undefined);
  const params = new URLSearchParams();
  if (input) {
    for (const [k, v] of Object.entries(input)) {
      if (v === undefined || v === null) continue;
      if (k === '_page' || k === '_size' || k === '_sort' || k === '_filter') continue;
      params.set(k, String(v));
    }
  }
  const body: Record<string, unknown> = {};
  if (options?.page !== undefined || options?.pageSize !== undefined || options?.sort || options?.filter) {
    const size = options?.pageSize ?? 50;
    body.page = { mode: 'offset', position: String((options?.page ?? 0) * size), size };
    const sortRules = parseSortExpression(options?.sort);
    if (sortRules.length > 0) body.sort = sortRules;
    if (options?.filter) body.filterExpression = options.filter;
  }
  const qs = params.toString();
  const url = qs ? `/saved-queries/order_margin_overrides/execute?${qs}` : "/saved-queries/order_margin_overrides/execute";
  const response = await apiManager.post('data', url, body, headers);
  const data = response.data;
  if (Array.isArray(data)) return data as OrderMarginOverridesRow[];
  if (data && typeof data === 'object') {
    const obj = data as Record<string, unknown>;
    if (Array.isArray(obj.data)) return obj.data as OrderMarginOverridesRow[];
    const keys = Object.keys(obj);
    if (keys.length === 1 && Array.isArray(obj[keys[0]])) {
      return obj[keys[0]] as OrderMarginOverridesRow[];
    }
  }
  return [] as OrderMarginOverridesRow[];
}
