// AUTO-GENERATED by scripts/fetch-saved-queries.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/saved-query
// Saved query: pricing_template_editor ("Pricing Template Editor")
// Type: multi_query  |  Single output: true  |  App: aswathtestapp_6a67823a8fa7215710927dbc
// Everything the pricing-template editor screen needs: all templates including inactive, all role margin rows, and the merchant clients a template can bind to.

import { apiManager } from '@/services/api-manager';
import { getDataHeaders } from '@/config/api-config';

/** Input parameters for `pricing_template_editor` (none declared). */
export type PricingTemplateEditorInput = Record<string, never>;

// TODO: multi_query saved queries return a map keyed by sub-query name
//       (multi_query) or the last sub-query's result (CTE). Codegen
//       for composite shapes is not implemented yet — the wrapper
//       returns `unknown` until typed by hand.
export type PricingTemplateEditorResult = unknown;

export const PRICING_TEMPLATE_EDITOR_NAME = "pricing_template_editor";
export const PRICING_TEMPLATE_EDITOR_IS_SINGLE = true as const;
export const PRICING_TEMPLATE_EDITOR_APP_KEY = "aswathtestapp_6a67823a8fa7215710927dbc";

export interface ExecutePricingTemplateEditorOptions {
  /** Maps to `_sort` URL query param (e.g. 'status,-balance'). */
  sort?: string;
  /** Maps to `_filter` URL param (CEL expression). */
  filter?: string;
}

/**
 * Execute the `pricing_template_editor` saved query. Read-only.
 * Returns `null` when the server reports NO_RESULTS_FOUND (HTTP 404).
 */
export async function executePricingTemplateEditor(
  input?: PricingTemplateEditorInput,
  options?: ExecutePricingTemplateEditorOptions,
): Promise<unknown> {
  const headers = getDataHeaders(PRICING_TEMPLATE_EDITOR_APP_KEY || undefined);
  const params = new URLSearchParams();
  if (input) {
    for (const [k, v] of Object.entries(input)) {
      if (v === undefined || v === null) continue;
      if (k === '_page' || k === '_size' || k === '_sort' || k === '_filter') continue;
      params.set(k, String(v));
    }
  }
  if (options?.sort) params.set('_sort', options.sort);
  if (options?.filter) params.set('_filter', options.filter);
  const body = {};
  const qs = params.toString();
  const url = qs ? `/saved-queries/pricing_template_editor/execute?${qs}` : "/saved-queries/pricing_template_editor/execute";
  try {
    const response = await apiManager.post('data', url, body, headers);
    const data = response.data;
    if (data == null) return null;
    if (Array.isArray(data)) return (data.length ? data[0] : null) as unknown;
    if (typeof data === 'object') {
      const obj = data as Record<string, unknown>;
      if (Array.isArray(obj.data)) return (obj.data.length ? obj.data[0] : null) as unknown;
      if (obj.data && typeof obj.data === 'object') return obj.data as unknown;
      const keys = Object.keys(obj);
      if (keys.length === 1 && Array.isArray(obj[keys[0]])) {
        const arr = obj[keys[0]] as unknown[];
        return (arr.length ? arr[0] : null) as unknown;
      }
      return obj as unknown as unknown;
    }
    return data as unknown;
  } catch (err: unknown) {
    // Map server 404 NO_RESULTS_FOUND → null so callers can render
    // "no data" without branching on errors.
    const status = (err as { response?: { status?: number } })?.response?.status;
    if (status === 404) return null;
    throw err;
  }
}
