// AUTO-GENERATED by scripts/fetch-saved-queries.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/saved-query
// Saved query: pricing_template_role_create ("Pricing Template Role Create")
// Type: dynamic  |  Single output: true  |  App: aswathtestapp_6a67823a8fa7215710927dbc
// Add a component-role margin row to a template. Query-string params: templateId, componentRole, marginBps. Query string is safe here because all three are UUIDs or short enum/integer values.

import { apiManager } from '@/services/api-manager';
import { getDataHeaders } from '@/config/api-config';

/** Input parameters for `pricing_template_role_create` (write — sent as a flat JSON body). */
export interface PricingTemplateRoleCreateInput {
  componentRole: string;
  marginBps: string;
  templateId: string;
}

/** Row returned by `pricing_template_role_create` (write).
 *  (Unwrapped from the saved query's `pricing_template_role` output.) */
export interface PricingTemplateRoleCreateResult {
  /** ID */
  id: string;
  /** Component Role */
  component_role?: string;
  /** Margin Bps */
  margin_bps?: number;
}

export const PRICING_TEMPLATE_ROLE_CREATE_NAME = "pricing_template_role_create";
export const PRICING_TEMPLATE_ROLE_CREATE_IS_SINGLE = true as const;
export const PRICING_TEMPLATE_ROLE_CREATE_APP_KEY = "aswathtestapp_6a67823a8fa7215710927dbc";

/**
 * Execute the `pricing_template_role_create` saved query. WRITE (insert).
 * Inputs are sent as a flat JSON body; returns the affected row(s).
 */
export async function executePricingTemplateRoleCreate(
  input: PricingTemplateRoleCreateInput,
): Promise<PricingTemplateRoleCreateResult> {
  const headers = getDataHeaders(PRICING_TEMPLATE_ROLE_CREATE_APP_KEY || undefined);
  const response = await apiManager.post('data', "/saved-queries/pricing_template_role_create/execute", input, headers);
  return response.data as PricingTemplateRoleCreateResult;
}
