// AUTO-GENERATED by scripts/fetch-saved-queries.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/saved-query
// Saved query: rfe_mark_responded ("rfe_mark_responded")
// Type: dynamic  |  Single output: true  |  App: aswathtestapp_6a67823a8fa7215710927dbc
// Flip an RFE from sent to responded once its response is submitted. Query-string param: rfeId. Called straight after rfe_response_submit - kept separate because a CTE spanning two entities cannot be saved through the MCP tool.

import { apiManager } from '@/services/api-manager';
import { getDataHeaders } from '@/config/api-config';

/** Input parameters for `rfe_mark_responded` (write — sent as a flat JSON body). */
export interface RfeMarkRespondedInput {
  rfeId: string;
}

/** Row returned by `rfe_mark_responded` (write).
 *  (Unwrapped from the saved query's `rfe` output.) */
export interface RfeMarkRespondedResult {
  /** Id */
  id?: string;
  /** Status */
  status?: string;
}

export const RFE_MARK_RESPONDED_NAME = "rfe_mark_responded";
export const RFE_MARK_RESPONDED_IS_SINGLE = true as const;
export const RFE_MARK_RESPONDED_APP_KEY = "aswathtestapp_6a67823a8fa7215710927dbc";

/**
 * Execute the `rfe_mark_responded` saved query. WRITE (update).
 * Inputs are sent as a flat JSON body; returns the affected row(s).
 */
export async function executeRfeMarkResponded(
  input: RfeMarkRespondedInput,
): Promise<RfeMarkRespondedResult[]> {
  const headers = getDataHeaders(RFE_MARK_RESPONDED_APP_KEY || undefined);
  const response = await apiManager.post('data', "/saved-queries/rfe_mark_responded/execute", input, headers);
  return response.data as RfeMarkRespondedResult[];
}
