// AUTO-GENERATED by scripts/fetch-saved-queries.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/saved-query
// Saved query: rfe_response_submit ("rfe_response_submit")
// Type: dynamic  |  Single output: true  |  App: aswathtestapp_6a67823a8fa7215710927dbc
// Write the supplier header fields and submit the response. JSON body: responseId, supplierQuoteNo, validityUntil, commitsToDelivery, leadTimeWeeks, submittedAt. Body transport because supplierQuoteNo is free text and query-string params split on commas. Caller must block submit while any line is uncosted and not declined.

import { apiManager } from '@/services/api-manager';
import { getDataHeaders } from '@/config/api-config';

/** Input parameters for `rfe_response_submit` (write — sent as a flat JSON body). */
export interface RfeResponseSubmitInput {
  commitsToDelivery: string;
  leadTimeWeeks: string;
  responseId: string;
  submittedAt: string;
  supplierQuoteNo: string;
  validityUntil: string;
}

/** Row returned by `rfe_response_submit` (write).
 *  (Unwrapped from the saved query's `rfe_response` output.) */
export interface RfeResponseSubmitResult {
  /** ID */
  id: string;
  /** Commits To Delivery */
  commits_to_delivery?: boolean;
  /** Lead Time Weeks */
  lead_time_weeks?: number;
  /** Round */
  round?: number;
  /** Status */
  status?: string;
  /** Submitted At */
  submitted_at?: string;
  /** Supplier Quote No */
  supplier_quote_no?: string;
  /** Validity Until */
  validity_until?: string;
}

export const RFE_RESPONSE_SUBMIT_NAME = "rfe_response_submit";
export const RFE_RESPONSE_SUBMIT_IS_SINGLE = true as const;
export const RFE_RESPONSE_SUBMIT_APP_KEY = "aswathtestapp_6a67823a8fa7215710927dbc";

/**
 * Execute the `rfe_response_submit` saved query. WRITE (update).
 * Inputs are sent as a flat JSON body; returns the affected row(s).
 */
export async function executeRfeResponseSubmit(
  input: RfeResponseSubmitInput,
): Promise<RfeResponseSubmitResult[]> {
  const headers = getDataHeaders(RFE_RESPONSE_SUBMIT_APP_KEY || undefined);
  const response = await apiManager.post('data', "/saved-queries/rfe_response_submit/execute", input, headers);
  return response.data as RfeResponseSubmitResult[];
}
