// AUTO-GENERATED by scripts/fetch-saved-queries.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/saved-query
// Saved query: rfe_response_line_update ("rfe_response_line_update")
// Type: dynamic  |  Single output: true  |  App: aswathtestapp_6a67823a8fa7215710927dbc
// Change an existing cost entry. Query-string params: lineId, costMicros, uncosted, declined. Same micro-unit convention as rfe_response_line_create.

import { apiManager } from '@/services/api-manager';
import { getDataHeaders } from '@/config/api-config';

/** Input parameters for `rfe_response_line_update` (write — sent as a flat JSON body). */
export interface RfeResponseLineUpdateInput {
  costMicros: string;
  declined: string;
  lineId: string;
  uncosted: string;
}

/** Row returned by `rfe_response_line_update` (write).
 *  (Unwrapped from the saved query's `rfe_response_line` output.) */
export interface RfeResponseLineUpdateResult {
  /** ID */
  id: string;
  /** Cost Micros */
  cost_micros?: number;
  /** Declined */
  declined?: boolean;
  /** Uncosted */
  uncosted?: boolean;
}

export const RFE_RESPONSE_LINE_UPDATE_NAME = "rfe_response_line_update";
export const RFE_RESPONSE_LINE_UPDATE_IS_SINGLE = true as const;
export const RFE_RESPONSE_LINE_UPDATE_APP_KEY = "aswathtestapp_6a67823a8fa7215710927dbc";

/**
 * Execute the `rfe_response_line_update` saved query. WRITE (update).
 * Inputs are sent as a flat JSON body; returns the affected row(s).
 */
export async function executeRfeResponseLineUpdate(
  input: RfeResponseLineUpdateInput,
): Promise<RfeResponseLineUpdateResult[]> {
  const headers = getDataHeaders(RFE_RESPONSE_LINE_UPDATE_APP_KEY || undefined);
  const response = await apiManager.post('data', "/saved-queries/rfe_response_line_update/execute", input, headers);
  return response.data as RfeResponseLineUpdateResult[];
}
