// AUTO-GENERATED by scripts/fetch-saved-queries.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/saved-query
// Saved query: rfe_create ("RFE Create")
// Type: common_table_expression  |  Single output: true  |  App: aswathtestapp_6a67823a8fa7215710927dbc
// Create one RFE (Inquiry) to one supplier for an order. Call with a JSON body: orderId, supplierId, setupInstructions, respondBy.

import { apiManager } from '@/services/api-manager';
import { getDataHeaders } from '@/config/api-config';

/** Input parameters for `rfe_create` (write — sent as a flat JSON body). */
export interface RfeCreateInput {
  orderId: string;
  respondBy: string;
  setupInstructions: string;
  supplierId: string;
}

/** Row returned by `rfe_create` (write — the affected row's id). */
export interface RfeCreateResult {
  id: string;
}

export const RFE_CREATE_NAME = "rfe_create";
export const RFE_CREATE_IS_SINGLE = true as const;
export const RFE_CREATE_APP_KEY = "aswathtestapp_6a67823a8fa7215710927dbc";

/**
 * Execute the `rfe_create` saved query. WRITE (insert).
 * Inputs are sent as a flat JSON body; returns the affected row(s).
 */
export async function executeRfeCreate(
  input: RfeCreateInput,
): Promise<RfeCreateResult> {
  const headers = getDataHeaders(RFE_CREATE_APP_KEY || undefined);
  const response = await apiManager.post('data', "/saved-queries/rfe_create/execute", input, headers);
  return response.data as RfeCreateResult;
}
