// AUTO-GENERATED by scripts/fetch-saved-queries.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/saved-query
// Saved query: rfe_response_line_create ("rfe_response_line_create")
// Type: dynamic  |  Single output: true  |  App: aswathtestapp_6a67823a8fa7215710927dbc
// First cost entry for a tier. Query-string params: responseId, tierId, costMicros, uncosted, declined. costMicros is millionths of a currency unit - 0.049 is 49000 - because Currency is numeric(15,2) and cannot hold sub-cent card costs. Use rfe_response_line_update if a line already exists for the tier.

import { apiManager } from '@/services/api-manager';
import { getDataHeaders } from '@/config/api-config';

/** Input parameters for `rfe_response_line_create` (write — sent as a flat JSON body). */
export interface RfeResponseLineCreateInput {
  costMicros: string;
  declined: string;
  responseId: string;
  tierId: string;
  uncosted: string;
}

/** Row returned by `rfe_response_line_create` (write).
 *  (Unwrapped from the saved query's `rfe_response_line` output.) */
export interface RfeResponseLineCreateResult {
  /** ID */
  id: string;
  /** Cost Micros */
  cost_micros?: number;
  /** Declined */
  declined?: boolean;
  /** Uncosted */
  uncosted?: boolean;
}

export const RFE_RESPONSE_LINE_CREATE_NAME = "rfe_response_line_create";
export const RFE_RESPONSE_LINE_CREATE_IS_SINGLE = true as const;
export const RFE_RESPONSE_LINE_CREATE_APP_KEY = "aswathtestapp_6a67823a8fa7215710927dbc";

/**
 * Execute the `rfe_response_line_create` saved query. WRITE (insert).
 * Inputs are sent as a flat JSON body; returns the affected row(s).
 */
export async function executeRfeResponseLineCreate(
  input: RfeResponseLineCreateInput,
): Promise<RfeResponseLineCreateResult> {
  const headers = getDataHeaders(RFE_RESPONSE_LINE_CREATE_APP_KEY || undefined);
  const response = await apiManager.post('data', "/saved-queries/rfe_response_line_create/execute", input, headers);
  return response.data as RfeResponseLineCreateResult;
}
