// AUTO-GENERATED by scripts/fetch-saved-queries.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/saved-query
// Saved query: supplier_list ("Supplier List")
// Type: dynamic  |  Single output: false  |  App: aswathtestapp_6a67823a8fa7215710927dbc
// Active supplier parties, sorted by name. Backs the Send-for-quotes supplier chooser.

import { apiManager } from '@/services/api-manager';
import { getDataHeaders } from '@/config/api-config';
import { parseSortExpression } from '@/hooks/saved-query-request';

/** Input parameters for `supplier_list` (none declared). */
export type SupplierListInput = Record<string, never>;

/** Single row in the `supplier_list` result set.
 *  (Unwrapped from the saved query's `party_list` output array.) */
export interface SupplierListRow {
  /** Id */
  id?: string;
  /** Legal Name */
  legal_name?: string;
  /** Name */
  name?: string;
  /** Status */
  status?: string;
}

export const SUPPLIER_LIST_NAME = "supplier_list";
export const SUPPLIER_LIST_IS_SINGLE = false as const;
export const SUPPLIER_LIST_APP_KEY = "aswathtestapp_6a67823a8fa7215710927dbc";

export interface ExecuteSupplierListOptions {
  /** Zero-based page index (body `page`, offset mode). */
  page?: number;
  /** Page size (body `page.size`). */
  pageSize?: number;
  /** Sort: comma-separated, `-` prefix for descending (e.g. 'status,-balance'). Body `sort`. */
  sort?: string;
  /** CEL filter expression (body `filterExpression`). */
  filter?: string;
}

/**
 * Execute the `supplier_list` saved query. Read-only.
 */
export async function executeSupplierList(
  input?: SupplierListInput,
  options?: ExecuteSupplierListOptions,
): Promise<SupplierListRow[]> {
  const headers = getDataHeaders(SUPPLIER_LIST_APP_KEY || undefined);
  const params = new URLSearchParams();
  if (input) {
    for (const [k, v] of Object.entries(input)) {
      if (v === undefined || v === null) continue;
      if (k === '_page' || k === '_size' || k === '_sort' || k === '_filter') continue;
      params.set(k, String(v));
    }
  }
  const body: Record<string, unknown> = {};
  if (options?.page !== undefined || options?.pageSize !== undefined || options?.sort || options?.filter) {
    const size = options?.pageSize ?? 50;
    body.page = { mode: 'offset', position: String((options?.page ?? 0) * size), size };
    const sortRules = parseSortExpression(options?.sort);
    if (sortRules.length > 0) body.sort = sortRules;
    if (options?.filter) body.filterExpression = options.filter;
  }
  const qs = params.toString();
  const url = qs ? `/saved-queries/supplier_list/execute?${qs}` : "/saved-queries/supplier_list/execute";
  const response = await apiManager.post('data', url, body, headers);
  const data = response.data;
  if (Array.isArray(data)) return data as SupplierListRow[];
  if (data && typeof data === 'object') {
    const obj = data as Record<string, unknown>;
    if (Array.isArray(obj.data)) return obj.data as SupplierListRow[];
    const keys = Object.keys(obj);
    if (keys.length === 1 && Array.isArray(obj[keys[0]])) {
      return obj[keys[0]] as SupplierListRow[];
    }
  }
  return [] as SupplierListRow[];
}
