// AUTO-GENERATED by scripts/fetch-saved-queries.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/saved-query
// Saved query: task_list ("Task List")
// Type: dynamic  |  Single output: false  |  App: aswathtestapp_6a67823a8fa7215710927dbc
// ONE call backing both toggles on the Task page: every order whose task instance is either assigned to this user OR unassigned. Param: userId. Split client-side - a row is MINE when tq_instance.assignee.id == userId, UNASSIGNED when tq_instance.assignee is null. Includes buyer, current stage name and current status state.

import { apiManager } from '@/services/api-manager';
import { getDataHeaders } from '@/config/api-config';
import { parseSortExpression } from '@/hooks/saved-query-request';

/** Input parameters for `task_list`. */
export interface TaskListInput {
  userId: string;
}

/** Single row in the `task_list` result set.
 *  (Unwrapped from the saved query's `orders_list` output array.) */
export interface TaskListRow {
  /** Id */
  id?: string;
  /** Created At */
  created_at?: string;
  /** Order Code */
  order_code?: string;
  /** Order Type */
  order_type?: string;
  /** Requested Delivery */
  requested_delivery?: string;
  /** Buyer Party Id */
  buyer_party_id?: {
      /** Id */
      id?: string;
      /** Name */
      name?: string;
    };
  /** TQ Instance */
  tq_instance?: {
      /** Id */
      id?: string;
      /** Assignee */
      assignee?: {
        id?: string;
        email?: string;
        full_name?: string;
      };
      /** Current Status */
      current_status?: {
        /** Id */
        id?: string;
        /** TQ State Definition */
        tq_state_definition?: {
          /** State */
          state?: string;
        };
      };
      /** Current Task */
      current_task?: {
        /** Id */
        id?: string;
        /** TQ Sub Task Definition */
        tq_sub_task_definition?: {
          /** Name */
          name?: string;
        };
      };
    };
}

export const TASK_LIST_NAME = "task_list";
export const TASK_LIST_IS_SINGLE = false as const;
export const TASK_LIST_APP_KEY = "aswathtestapp_6a67823a8fa7215710927dbc";

export interface ExecuteTaskListOptions {
  /** Zero-based page index (body `page`, offset mode). */
  page?: number;
  /** Page size (body `page.size`). */
  pageSize?: number;
  /** Sort: comma-separated, `-` prefix for descending (e.g. 'status,-balance'). Body `sort`. */
  sort?: string;
  /** CEL filter expression (body `filterExpression`). */
  filter?: string;
}

/**
 * Execute the `task_list` saved query. Read-only.
 */
export async function executeTaskList(
  input: TaskListInput,
  options?: ExecuteTaskListOptions,
): Promise<TaskListRow[]> {
  const headers = getDataHeaders(TASK_LIST_APP_KEY || undefined);
  const params = new URLSearchParams();
  if (input) {
    for (const [k, v] of Object.entries(input)) {
      if (v === undefined || v === null) continue;
      if (k === '_page' || k === '_size' || k === '_sort' || k === '_filter') continue;
      params.set(k, String(v));
    }
  }
  const body: Record<string, unknown> = {};
  if (options?.page !== undefined || options?.pageSize !== undefined || options?.sort || options?.filter) {
    const size = options?.pageSize ?? 50;
    body.page = { mode: 'offset', position: String((options?.page ?? 0) * size), size };
    const sortRules = parseSortExpression(options?.sort);
    if (sortRules.length > 0) body.sort = sortRules;
    if (options?.filter) body.filterExpression = options.filter;
  }
  const qs = params.toString();
  const url = qs ? `/saved-queries/task_list/execute?${qs}` : "/saved-queries/task_list/execute";
  const response = await apiManager.post('data', url, body, headers);
  const data = response.data;
  if (Array.isArray(data)) return data as TaskListRow[];
  if (data && typeof data === 'object') {
    const obj = data as Record<string, unknown>;
    if (Array.isArray(obj.data)) return obj.data as TaskListRow[];
    const keys = Object.keys(obj);
    if (keys.length === 1 && Array.isArray(obj[keys[0]])) {
      return obj[keys[0]] as TaskListRow[];
    }
  }
  return [] as TaskListRow[];
}
