// AUTO-GENERATED by scripts/fetch-saved-queries.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/saved-query
// Saved query: tq_status_history ("tq_status_history")
// Type: dynamic  |  Single output: false  |  App: aswathtestapp_6a67823a8fa7215710927dbc
// Full status trail of a tq_instance: every state entered, with its sub-task and definitions, ordered chronologically. Param: instanceId.

import { apiManager } from '@/services/api-manager';
import { getDataHeaders } from '@/config/api-config';
import { parseSortExpression } from '@/hooks/saved-query-request';

/** Input parameters for `tq_status_history`. */
export interface TqStatusHistoryInput {
  instanceId: string;
}

/** Single row in the `tq_status_history` result set.
 *  (Unwrapped from the saved query's `tq_state_instance_list` output array.) */
export interface TqStatusHistoryRow {
  /** Id */
  id?: string;
  /** Created At */
  created_at?: string;
  /** Is Current */
  is_current?: boolean;
  /** TQ State Definition */
  tq_state_definition?: {
      /** Is Final */
      is_final?: boolean;
      /** Is Initial */
      is_initial?: boolean;
      /** State */
      state?: string;
    };
  /** TQ Sub Task Instance */
  tq_sub_task_instance?: {
      /** Id */
      id?: string;
      /** Completed At */
      completed_at?: string;
      /** Created At */
      created_at?: string;
      /** TQ Sub Task Definition */
      tq_sub_task_definition?: {
        /** Name */
        name?: string;
      };
    };
}

export const TQ_STATUS_HISTORY_NAME = "tq_status_history";
export const TQ_STATUS_HISTORY_IS_SINGLE = false as const;
export const TQ_STATUS_HISTORY_APP_KEY = "aswathtestapp_6a67823a8fa7215710927dbc";

export interface ExecuteTqStatusHistoryOptions {
  /** Zero-based page index (body `page`, offset mode). */
  page?: number;
  /** Page size (body `page.size`). */
  pageSize?: number;
  /** Sort: comma-separated, `-` prefix for descending (e.g. 'status,-balance'). Body `sort`. */
  sort?: string;
  /** CEL filter expression (body `filterExpression`). */
  filter?: string;
}

/**
 * Execute the `tq_status_history` saved query. Read-only.
 */
export async function executeTqStatusHistory(
  input: TqStatusHistoryInput,
  options?: ExecuteTqStatusHistoryOptions,
): Promise<TqStatusHistoryRow[]> {
  const headers = getDataHeaders(TQ_STATUS_HISTORY_APP_KEY || undefined);
  const params = new URLSearchParams();
  if (input) {
    for (const [k, v] of Object.entries(input)) {
      if (v === undefined || v === null) continue;
      if (k === '_page' || k === '_size' || k === '_sort' || k === '_filter') continue;
      params.set(k, String(v));
    }
  }
  const body: Record<string, unknown> = {};
  if (options?.page !== undefined || options?.pageSize !== undefined || options?.sort || options?.filter) {
    const size = options?.pageSize ?? 50;
    body.page = { mode: 'offset', position: String((options?.page ?? 0) * size), size };
    const sortRules = parseSortExpression(options?.sort);
    if (sortRules.length > 0) body.sort = sortRules;
    if (options?.filter) body.filterExpression = options.filter;
  }
  const qs = params.toString();
  const url = qs ? `/saved-queries/tq_status_history/execute?${qs}` : "/saved-queries/tq_status_history/execute";
  const response = await apiManager.post('data', url, body, headers);
  const data = response.data;
  if (Array.isArray(data)) return data as TqStatusHistoryRow[];
  if (data && typeof data === 'object') {
    const obj = data as Record<string, unknown>;
    if (Array.isArray(obj.data)) return obj.data as TqStatusHistoryRow[];
    const keys = Object.keys(obj);
    if (keys.length === 1 && Array.isArray(obj[keys[0]])) {
      return obj[keys[0]] as TqStatusHistoryRow[];
    }
  }
  return [] as TqStatusHistoryRow[];
}
