// AUTO-GENERATED by scripts/fetch-saved-queries.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/saved-query
// Saved query: unassigned_tasks ("Unassigned Tasks")
// Type: dynamic  |  Single output: false  |  App: aswathtestapp_6a67823a8fa7215710927dbc
// Orders whose task instance has no assignee - claimable work. No params. Same row shape as my_tasks. Backs the Unassigned toggle on the Task page.

import { apiManager } from '@/services/api-manager';
import { getDataHeaders } from '@/config/api-config';
import { parseSortExpression } from '@/hooks/saved-query-request';

/** Input parameters for `unassigned_tasks` (none declared). */
export type UnassignedTasksInput = Record<string, never>;

/** Single row in the `unassigned_tasks` result set.
 *  (Unwrapped from the saved query's `orders_list` output array.) */
export interface UnassignedTasksRow {
  /** Id */
  id?: string;
  /** Created At */
  created_at?: string;
  /** Order Code */
  order_code?: string;
  /** Order Type */
  order_type?: string;
  /** Requested Delivery */
  requested_delivery?: string;
  /** Buyer Party Id */
  buyer_party_id?: {
      /** Id */
      id?: string;
      /** Name */
      name?: string;
    };
  /** TQ Instance */
  tq_instance?: {
      /** Id */
      id?: string;
      /** Assignee */
      assignee?: {
        id?: string;
        email?: string;
        full_name?: string;
      };
      /** Current Status */
      current_status?: {
        /** Id */
        id?: string;
        /** TQ State Definition */
        tq_state_definition?: {
          /** State */
          state?: string;
        };
      };
      /** Current Task */
      current_task?: {
        /** Id */
        id?: string;
        /** TQ Sub Task Definition */
        tq_sub_task_definition?: {
          /** Name */
          name?: string;
        };
      };
    };
}

export const UNASSIGNED_TASKS_NAME = "unassigned_tasks";
export const UNASSIGNED_TASKS_IS_SINGLE = false as const;
export const UNASSIGNED_TASKS_APP_KEY = "aswathtestapp_6a67823a8fa7215710927dbc";

export interface ExecuteUnassignedTasksOptions {
  /** Zero-based page index (body `page`, offset mode). */
  page?: number;
  /** Page size (body `page.size`). */
  pageSize?: number;
  /** Sort: comma-separated, `-` prefix for descending (e.g. 'status,-balance'). Body `sort`. */
  sort?: string;
  /** CEL filter expression (body `filterExpression`). */
  filter?: string;
}

/**
 * Execute the `unassigned_tasks` saved query. Read-only.
 */
export async function executeUnassignedTasks(
  input?: UnassignedTasksInput,
  options?: ExecuteUnassignedTasksOptions,
): Promise<UnassignedTasksRow[]> {
  const headers = getDataHeaders(UNASSIGNED_TASKS_APP_KEY || undefined);
  const params = new URLSearchParams();
  if (input) {
    for (const [k, v] of Object.entries(input)) {
      if (v === undefined || v === null) continue;
      if (k === '_page' || k === '_size' || k === '_sort' || k === '_filter') continue;
      params.set(k, String(v));
    }
  }
  const body: Record<string, unknown> = {};
  if (options?.page !== undefined || options?.pageSize !== undefined || options?.sort || options?.filter) {
    const size = options?.pageSize ?? 50;
    body.page = { mode: 'offset', position: String((options?.page ?? 0) * size), size };
    const sortRules = parseSortExpression(options?.sort);
    if (sortRules.length > 0) body.sort = sortRules;
    if (options?.filter) body.filterExpression = options.filter;
  }
  const qs = params.toString();
  const url = qs ? `/saved-queries/unassigned_tasks/execute?${qs}` : "/saved-queries/unassigned_tasks/execute";
  const response = await apiManager.post('data', url, body, headers);
  const data = response.data;
  if (Array.isArray(data)) return data as UnassignedTasksRow[];
  if (data && typeof data === 'object') {
    const obj = data as Record<string, unknown>;
    if (Array.isArray(obj.data)) return obj.data as UnassignedTasksRow[];
    const keys = Object.keys(obj);
    if (keys.length === 1 && Array.isArray(obj[keys[0]])) {
      return obj[keys[0]] as UnassignedTasksRow[];
    }
  }
  return [] as UnassignedTasksRow[];
}
