/**
 * Renderer for the saved-query catalog (`src/types/catalogs/saved-queries.catalog.md`).
 *
 * The catalog is the AGENT-FACING discovery surface for saved queries: one
 * greppable markdown file listing every saved query with its description,
 * hook to use, inputs, and outputs. The agent reads CLAUDE.md, which points
 * here; one grep by intent keyword surfaces the right entry, and the agent
 * then jumps to the typed module — its exact path is printed per entry as
 * **Module:** `src/types/saved-queries/<app_definition_key>/{name}.ts` (the
 * per-item modules are foldered by app, NOT flat).
 *
 * This helper is extracted from `scripts/fetch-saved-queries.ts` so it can
 * be unit-tested in the starter's vitest env (`scripts/` lives outside the
 * vitest include glob).
 */

import { appKeyDir } from '@/lib/codegen-collisions';

/** Minimal description of an input/output attribute that affects rendering. */
export interface SavedQueryCatalogField {
  name: string;
  required?: boolean;
}

/** What the catalog renderer needs to know about each saved query. */
export interface SavedQueryCatalogEntry {
  /** Canonical snake-or-kebab-case identifier (URL segment). */
  name: string;
  /** Human-readable label from the Phoenix definition. May be empty. */
  label: string;
  /** Description copied from the Phoenix UI. May be empty. */
  description: string;
  /** "dynamic" | "sql" | "multi_query" | "common_table_expression" */
  type: string;
  /**
   * Set for write queries (insert/update/delete). When present the entry is
   * a WRITE — rendered with the mutation hook + a WRITE note, never the read
   * table/list/single hooks.
   */
  operation?: 'insert' | 'update' | 'delete';
  /** Maps to `is_single_output` on the saved-query definition. */
  isSingle: boolean;
  /** True for `multi_query` / `common_table_expression`. */
  isComposite: boolean;
  /** App-definition key (may be empty for same-app queries). */
  appKey: string;
  /** Top-level input attributes (already stripped of `_page`/`_size`/...). */
  inputs: SavedQueryCatalogField[];
  /** Top-level output attribute names. */
  outputs: string[];
  /**
   * Name of a sibling count saved query (`<name>_count` convention)
   * matched by the codegen. Only set on list entries that have a
   * companion. Triggers a `useSavedQueryTable` invocation with paired
   * `countQuery`/`countSelector` instead of the plain list call.
   */
  countCompanion?: string;
  /**
   * Dotted path from the count companion's result to the numeric total
   * (e.g. `client_aggregate.ID`). Derived by codegen by picking the first
   * numeric leaf of the count companion's output schema. When set, the
   * catalog renders a ready-to-paste `countSelector` arrow function.
   * When undefined (companion shape ambiguous), the catalog renders a
   * placeholder selector with a TODO.
   */
  countSelectorPath?: string;
  /**
   * Heuristically-picked entity field names that the DataTable's
   * top-toolbar global search should match against. Surfaced in the
   * catalog as `searchColumns: [...]` inside the `useSavedQueryTable`
   * hook call so the agent can copy-paste without inventing the field
   * names. An empty array (or undefined) means no good text field was
   * detected — the catalog renders an explicit empty array with a TODO.
   *
   * Capped at one entry: only `searchColumns[0]` is used at runtime,
   * matching the saved-query backend's single-input search model.
   */
  searchColumns?: readonly string[];
  /**
   * Names of input attributes marked `required: true` in the saved
   * query's schema (minus reserved slots). The hook gates the network
   * request on these being non-empty: when any is missing, no API call
   * is made and the DataTable renders a "Provide: …" empty state.
   *
   * Surfaced in the catalog as `requiredInputs: [...]` inside the
   * `useSavedQueryTable` hook call so the agent can copy-paste it.
   */
  requiredInputs?: readonly string[];
}

const COMPOSITE_NOTE =
  '> ⚠ Composite — return type is `unknown` until typed by hand.';

const PATCH_NOTE =
  '> ✎ WRITE (patch) — mutates a record. Use `useSavedQueryMutation` ' +
  '(pass `{ id, ...fields }`); it returns the patched row. NOT a read.';

function writeNote(op: 'insert' | 'update' | 'delete'): string {
  return (
    `> ✎ WRITE (${op}) — mutates data, NOT a read. Use ` +
    '`useSavedQueryMutation("<name>")`; inputs are the `$body.<field>` values ' +
    '(passed as a flat JSON body). Returns the affected row id(s).'
  );
}

const NO_DESCRIPTION = '_(no description provided)_';

const CATALOG_HEADER = `# Saved Queries Catalog

Auto-generated by \`scripts/fetch-saved-queries.ts\`. One entry per saved
query exposed by the tenant.

**To find a saved query by intent, grep this file by keyword** (e.g.
"anomaly", "execution history", "account summary"). Each entry shows the
hook to use, the inputs to pass, and the description copied from the
Phoenix UI. For the precise TypeScript input/row shape, open the per-entry
**Module:** path — modules are foldered by app
(\`src/types/saved-queries/<app_definition_key>/{name}.ts\`), NOT flat, so
use the path shown rather than guessing.

Saved queries are the **only** data mechanism — reads and writes. Most are
reads; a **write** query (\`insert\` / \`update\` / \`delete\`, or legacy
\`type: patch\`) carries a \`✎ WRITE\` note and uses
\`useSavedQueryMutation("<name>")\`. There is no \`useEntityMutation\`.

`;

function formatInputs(inputs: SavedQueryCatalogField[]): string {
  if (inputs.length === 0) return '_(none)_';
  return inputs
    .map((f) => (f.required ? `\`${f.name}\` (required)` : `\`${f.name}\``))
    .join(', ');
}

function formatOutputs(outputs: string[]): string {
  if (outputs.length === 0) return '_(none)_';
  return outputs.map((o) => `\`${o}\``).join(', ');
}

/**
 * Build the dotted-path access expression. `client_aggregate.ID` becomes
 * `r?.client_aggregate?.ID`. Returns null for an empty / nonsense path so
 * callers can fall back to a placeholder.
 */
function buildCountSelectorBody(path: string | undefined): string | null {
  if (!path) return null;
  const segments = path.split('.').filter(Boolean);
  if (segments.length === 0) return null;
  return `r?.${segments.join('?.')}`;
}

/**
 * Render the searchColumns option fragment used inside the hook call.
 * Returns an empty string when there's nothing to surface (no field
 * detected at all and no array set). Returns `searchColumns: []` with a
 * TODO comment when the codegen ran but found no matching field — that
 * way the agent sees the option exists and knows to fill it in.
 */
function formatSearchColumnsFragment(
  entry: SavedQueryCatalogEntry,
): string {
  if (entry.searchColumns === undefined) return '';
  if (entry.searchColumns.length === 0) {
    return (
      `, searchColumns: [] /* TODO: pick entity text fields to enable ` +
      `toolbar search */`
    );
  }
  const list = entry.searchColumns.map((c) => JSON.stringify(c)).join(', ');
  return `, searchColumns: [${list}]`;
}

/**
 * Render the requiredInputs option fragment. Only emitted when the
 * saved query declares at least one required input — otherwise omitted
 * entirely (no TODO; the hook treats `undefined` as "no required
 * inputs", which is correct).
 */
function formatRequiredInputsFragment(
  entry: SavedQueryCatalogEntry,
): string {
  if (!entry.requiredInputs || entry.requiredInputs.length === 0) return '';
  const list = entry.requiredInputs.map((c) => JSON.stringify(c)).join(', ');
  return `, requiredInputs: [${list}]`;
}

function formatHookCall(entry: SavedQueryCatalogEntry): string {
  // Write (patch) saved queries are mutations — not reads. They use the
  // dedicated mutation hook, never useSavedQueryTable/List/Single.
  if (entry.operation || entry.type === 'patch') {
    return `\`useSavedQueryMutation(${JSON.stringify(entry.name)})\``;
  }

  // Single-output saved queries use the dedicated single hook for direct
  // access (e.g. a KPI card). They don't go through useSavedQueryTable.
  // This INCLUDES single-output composites: a multi_query result is one
  // object keyed by sub-query name — the list hook's normaliser would turn
  // that multi-key object into [].
  if (entry.isSingle) {
    return `\`useSavedQuerySingle(${JSON.stringify(entry.name)}, { input })\``;
  }

  // List-output composites: bare list hook, caller narrows the unknown.
  if (entry.isComposite) {
    return `\`useSavedQueryList(${JSON.stringify(entry.name)}, { input })\``;
  }

  // List saved queries — use the table-ready hook. It picks server-side
  // pagination when `countQuery` is provided, fetch-all (client-side
  // pagination) otherwise.
  const searchFragment = formatSearchColumnsFragment(entry);
  const requiredFragment = formatRequiredInputsFragment(entry);
  const trailingFragments = `${searchFragment}${requiredFragment}`;

  if (entry.countCompanion) {
    const selectorBody = buildCountSelectorBody(entry.countSelectorPath);
    const selector =
      selectorBody !== null
        ? `(r) => ${selectorBody}`
        : `(r) => undefined /* TODO: count companion shape unclear; ` +
          `inspect ${entry.countCompanion} and supply selector */`;
    return (
      `\`useSavedQueryTable(${JSON.stringify(entry.name)}, ` +
      `{ countQuery: ${JSON.stringify(entry.countCompanion)}, ` +
      `countSelector: ${selector}${trailingFragments} })\``
    );
  }

  if (trailingFragments) {
    // Strip the leading `, ` from whichever fragment came first so we
    // open the options object cleanly with a single space.
    return (
      `\`useSavedQueryTable(${JSON.stringify(entry.name)}, ` +
      `{${trailingFragments.replace(/^, /, ' ')} })\` ` +
      `_(fetch-all, no count companion in catalog)_`
    );
  }

  return `\`useSavedQueryTable(${JSON.stringify(entry.name)})\` ` +
    `_(fetch-all, no count companion in catalog)_`;
}

function formatDescription(desc: string): string {
  const trimmed = desc.replace(/\r?\n+/g, ' ').trim();
  return trimmed.length > 0 ? trimmed : NO_DESCRIPTION;
}

function renderEntry(entry: SavedQueryCatalogEntry): string {
  const lines: string[] = [];
  const heading = entry.label
    ? `### \`${entry.name}\` — "${entry.label}"`
    : `### \`${entry.name}\``;
  lines.push(heading);
  lines.push(`- **Hook:** ${formatHookCall(entry)}`);
  const singleLabel = entry.isSingle ? 'yes' : 'no';
  const appCol = entry.appKey ? `  ·  **App:** ${entry.appKey}` : '';
  lines.push(
    `- **Type:** ${entry.type}  ·  **Single output:** ${singleLabel}${appCol}`,
  );
  lines.push(
    `- **Module:** \`src/types/saved-queries/${appKeyDir(entry.appKey)}/${entry.name}.ts\``,
  );
  lines.push(`- **Inputs:** ${formatInputs(entry.inputs)}`);
  lines.push(`- **Outputs:** ${formatOutputs(entry.outputs)}`);
  if (entry.countCompanion) {
    lines.push(`- **Count companion:** \`${entry.countCompanion}\``);
  }
  if (entry.searchColumns && entry.searchColumns.length > 0) {
    lines.push(
      `- **Searchable columns (heuristic):** ${entry.searchColumns
        .map((c) => `\`${c}\``)
        .join(', ')}`,
    );
  }
  if (entry.requiredInputs && entry.requiredInputs.length > 0) {
    lines.push(
      `- **Required inputs (fetch gated until provided):** ${entry.requiredInputs
        .map((c) => `\`${c}\``)
        .join(', ')}`,
    );
  }
  lines.push(formatDescription(entry.description));
  if (entry.operation) {
    lines.push(writeNote(entry.operation));
  } else if (entry.type === 'patch') {
    lines.push(PATCH_NOTE);
  }
  if (entry.isComposite) {
    lines.push(COMPOSITE_NOTE);
  }
  return lines.join('\n');
}

/**
 * Render the markdown catalog as a single string. The entries are sorted
 * alphabetically by `name` so the file is deterministic across runs.
 */
export function renderSavedQueryCatalog(
  entries: SavedQueryCatalogEntry[],
): string {
  if (entries.length === 0) {
    return (
      CATALOG_HEADER +
      `_No saved queries available. Either the tenant has none defined, or\n` +
      `\`PHOENIX_API_URL\` / \`TENANT_ID\` were not set when the catalog was\n` +
      `regenerated. Run \`npm run fetch:saved-queries\` to refresh._\n`
    );
  }
  const sorted = [...entries].sort((a, b) => a.name.localeCompare(b.name));
  const body = sorted.map(renderEntry).join('\n\n');
  return `${CATALOG_HEADER}---\n\n${body}\n`;
}
