/* eslint-disable */
// AUTO-GENERATED by scripts/fetch-entities.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/entity
// Regenerated on every workspace bootstrap; in sync with src/types/entities/**.

// All known entity names (typed union).
export type EntityName = "card_spec" | "card_template" | "card_variant" | "inquiry" | "item" | "item_revision" | "line_allocation" | "margin_override" | "order_line" | "orders" | "party" | "party_role" | "price_history" | "pricing_template" | "pricing_template_role" | "rfe" | "rfe_line_row" | "rfe_line_tier" | "rfe_response" | "rfe_response_line" | "supplier_capacity" | "supplier_cert" | "tq_definition" | "tq_instance" | "tq_state_definition" | "tq_state_instance" | "tq_sub_task_definition" | "tq_sub_task_instance";

/** Fields on entity `card_spec` (Card Spec). */
export type CardSpecFieldName =
  | "id"
  | "item_rev_id"
  | "shape"
  | "substrate"
  | "thickness_mil"
  | "front_color_code"
  | "back_color_code"
  | "finish"
  | "mag_stripe"
  | "mag_coercivity"
  | "mag_tracks"
  | "sig_panel"
  | "scratch_off"
  | "bin"
  | "ica"
  | "preprint_bin"
  | "card_brand"
  | "spec"
  | "artwork_front"
  | "artwork_back"
  | "artwork_preview"
  | "artwork_updated_at"
  | "artwork_pdf_file_id"
  | "artwork_pdf_name"
  | "artwork_pdf_at"
  | "template_ref";

/** Fields on entity `card_template` (Card Template). */
export type CardTemplateFieldName =
  | "id"
  | "name"
  | "description"
  | "category"
  | "thumbnail"
  | "artwork_front"
  | "artwork_back"
  | "active"
  | "created_at";

/** Fields on entity `card_variant` (Card Variant). */
export type CardVariantFieldName =
  | "id"
  | "label"
  | "delta"
  | "qty"
  | "due_date"
  | "approved"
  | "approved_at"
  | "created_at"
  | "order_ref"
  | "card_spec_ref";

/** Fields on entity `inquiry` (Inquiry). */
export type InquiryFieldName =
  | "id"
  | "demand_order"
  | "supplier"
  | "setup_instructions"
  | "respond_by"
  | "status"
  | "sent_at";

/** Fields on entity `item` (Item). */
export type ItemFieldName =
  | "id"
  | "item_type"
  | "name"
  | "component_role"
  | "owner_party_id";

/** Fields on entity `item_revision` (Item Revision). */
export type ItemRevisionFieldName =
  | "id"
  | "item_id"
  | "rev"
  | "status";

/** Fields on entity `line_allocation` (Line Allocation). */
export type LineAllocationFieldName =
  | "id"
  | "kind"
  | "qty"
  | "unit_cost_micros"
  | "component_role"
  | "exception_note"
  | "created_at"
  | "order_ref"
  | "order_line_ref"
  | "supplier"
  | "assembler";

/** Fields on entity `margin_override` (Margin Override). */
export type MarginOverrideFieldName =
  | "id"
  | "component_role"
  | "margin_bps"
  | "from_bps"
  | "scenario"
  | "reason"
  | "active"
  | "created_at"
  | "order_ref";

/** Fields on entity `order_line` (Order Line). */
export type OrderLineFieldName =
  | "id"
  | "order_id"
  | "item"
  | "qty"
  | "unit_price"
  | "uom";

/** Fields on entity `orders` (Orders). */
export type OrdersFieldName =
  | "id"
  | "buyer_party_id"
  | "seller_party_id"
  | "bill_to_id"
  | "bill_from_id"
  | "source_order_id"
  | "tq_instance"
  | "order_code"
  | "order_kind"
  | "order_type"
  | "po_required"
  | "bill_when_shipped"
  | "rev"
  | "status"
  | "order_brief"
  | "requested_delivery"
  | "created_by"
  | "created_at"
  | "last_modified_by"
  | "last_modified_at";

/** Fields on entity `party` (Party). */
export type PartyFieldName =
  | "id"
  | "kind"
  | "name"
  | "legal_name"
  | "status";

/** Fields on entity `party_role` (Party Role). */
export type PartyRoleFieldName =
  | "id"
  | "party"
  | "role"
  | "scope";

/** Fields on entity `price_history` (Price History). */
export type PriceHistoryFieldName =
  | "id"
  | "party"
  | "signature_hash"
  | "tier_qty"
  | "unit_cost"
  | "observed_at";

/** Fields on entity `pricing_template` (Pricing Template). */
export type PricingTemplateFieldName =
  | "id"
  | "name"
  | "model"
  | "basis"
  | "scenario"
  | "floor_bps"
  | "effective_from"
  | "effective_to"
  | "active"
  | "client";

/** Fields on entity `pricing_template_role` (Pricing Template Role). */
export type PricingTemplateRoleFieldName =
  | "id"
  | "component_role"
  | "margin_bps"
  | "template";

/** Fields on entity `rfe` (RFE). */
export type RfeFieldName =
  | "id"
  | "demand_order"
  | "supplier"
  | "setup_instructions"
  | "respond_by"
  | "status"
  | "sent_at";

/** Fields on entity `rfe_line_row` (RFE Line Row). */
export type RfeLineRowFieldName =
  | "id"
  | "rfe_id"
  | "item_rev_id"
  | "order_line_id"
  | "qty";

/** Fields on entity `rfe_line_tier` (RFE Line Tier). */
export type RfeLineTierFieldName =
  | "id"
  | "tier_qty"
  | "rfe_line";

/** Fields on entity `rfe_response` (RFE Response). */
export type RfeResponseFieldName =
  | "id"
  | "round"
  | "supplier_quote_no"
  | "validity_until"
  | "commits_to_delivery"
  | "submitted_at"
  | "status"
  | "lead_time_weeks"
  | "rfe";

/** Fields on entity `rfe_response_line` (RFE Response Line). */
export type RfeResponseLineFieldName =
  | "id"
  | "cost_micros"
  | "uncosted"
  | "declined"
  | "note"
  | "response"
  | "tier";

/** Fields on entity `supplier_capacity` (Supplier Capacity). */
export type SupplierCapacityFieldName =
  | "id"
  | "supplier"
  | "period"
  | "declared"
  | "committed";

/** Fields on entity `supplier_cert` (Supplier Cert). */
export type SupplierCertFieldName =
  | "id"
  | "supplier"
  | "certification"
  | "valid_until";

/** Fields on entity `tq_definition` (TQ Definition). */
export type TqDefinitionFieldName =
  | "id"
  | "name"
  | "tasks"
  | "created_by"
  | "created_at"
  | "last_modified_by"
  | "last_modified_at";

/** Fields on entity `tq_instance` (TQ Instance). */
export type TqInstanceFieldName =
  | "id"
  | "tq_definition"
  | "current_task"
  | "current_status"
  | "sub_task_history"
  | "assignee"
  | "created_by"
  | "created_at"
  | "last_modified_by"
  | "last_modified_at";

/** Fields on entity `tq_state_definition` (TQ State Definition). */
export type TqStateDefinitionFieldName =
  | "id"
  | "state"
  | "is_initial"
  | "is_final"
  | "created_by"
  | "created_at"
  | "last_modified_by"
  | "last_modified_at";

/** Fields on entity `tq_state_instance` (TQ State Instance). */
export type TqStateInstanceFieldName =
  | "id"
  | "tq_sub_task_instance"
  | "tq_state_definition"
  | "is_current"
  | "created_by"
  | "created_at"
  | "last_modified_by"
  | "last_modified_at";

/** Fields on entity `tq_sub_task_definition` (TQ Sub Task Definition). */
export type TqSubTaskDefinitionFieldName =
  | "id"
  | "name"
  | "previous_task"
  | "next_task"
  | "is_initial"
  | "is_final"
  | "states"
  | "created_by"
  | "created_at"
  | "last_modified_by"
  | "last_modified_at";

/** Fields on entity `tq_sub_task_instance` (TQ Sub Task Instance). */
export type TqSubTaskInstanceFieldName =
  | "id"
  | "tq_instance"
  | "tq_sub_task_definition"
  | "current_state"
  | "status_history"
  | "completed_at"
  | "assignee"
  | "created_by"
  | "created_at"
  | "last_modified_by"
  | "last_modified_at";

/**
 * Master entity registry consumed by useEntityMutation (+ saved-query / DynQL typing).
 * fields:  union of valid field names (used to constrain select/where/data).
 * appKey:  app_definition_key the data API expects.
 * links:   map of link-field-name -> target entity (for nested selects).
 */
export interface EntitySchema {
  "card_spec": {
    fields: CardSpecFieldName;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    links: {
      "item_rev_id": { target: "item_revision"; cardinality: "oneToOne"; kind: "Link" };
      "template_ref": { target: "card_template"; cardinality: "manyToOne"; kind: "Link" };
    };
  };
  "card_template": {
    fields: CardTemplateFieldName;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    links: {};
  };
  "card_variant": {
    fields: CardVariantFieldName;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    links: {
      "order_ref": { target: "orders"; cardinality: "manyToOne"; kind: "Link" };
      "card_spec_ref": { target: "card_spec"; cardinality: "manyToOne"; kind: "Link" };
    };
  };
  "inquiry": {
    fields: InquiryFieldName;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    links: {
      "demand_order": { target: "orders"; cardinality: "manyToOne"; kind: "Link" };
      "supplier": { target: "party"; cardinality: "manyToOne"; kind: "Link" };
    };
  };
  "item": {
    fields: ItemFieldName;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    links: {
      "owner_party_id": { target: "party"; cardinality: "manyToOne"; kind: "Link" };
    };
  };
  "item_revision": {
    fields: ItemRevisionFieldName;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    links: {
      "item_id": { target: "item"; cardinality: "manyToOne"; kind: "Link" };
    };
  };
  "line_allocation": {
    fields: LineAllocationFieldName;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    links: {
      "order_ref": { target: "orders"; cardinality: "manyToOne"; kind: "Link" };
      "order_line_ref": { target: "order_line"; cardinality: "manyToOne"; kind: "Link" };
      "supplier": { target: "party"; cardinality: "manyToOne"; kind: "Link" };
      "assembler": { target: "party"; cardinality: "manyToOne"; kind: "Link" };
    };
  };
  "margin_override": {
    fields: MarginOverrideFieldName;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    links: {
      "order_ref": { target: "orders"; cardinality: "manyToOne"; kind: "Link" };
    };
  };
  "order_line": {
    fields: OrderLineFieldName;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    links: {
      "order_id": { target: "orders"; cardinality: "manyToOne"; kind: "Link" };
    };
  };
  "orders": {
    fields: OrdersFieldName;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    links: {
      "buyer_party_id": { target: "party"; cardinality: "manyToOne"; kind: "Link" };
      "seller_party_id": { target: "party"; cardinality: "manyToOne"; kind: "Link" };
      "bill_to_id": { target: "party"; cardinality: "manyToOne"; kind: "Link" };
      "bill_from_id": { target: "party"; cardinality: "manyToOne"; kind: "Link" };
      "source_order_id": { target: "orders"; cardinality: "manyToOne"; kind: "Link" };
      "tq_instance": { target: "tq_instance"; cardinality: "oneToOne"; kind: "Link" };
      "created_by": { target: "user"; cardinality: "manyToOne"; kind: "Link" };
      "last_modified_by": { target: "user"; cardinality: "manyToOne"; kind: "Link" };
    };
  };
  "party": {
    fields: PartyFieldName;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    links: {};
  };
  "party_role": {
    fields: PartyRoleFieldName;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    links: {
      "party": { target: "party"; cardinality: "manyToOne"; kind: "Link" };
    };
  };
  "price_history": {
    fields: PriceHistoryFieldName;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    links: {
      "party": { target: "party"; cardinality: "manyToOne"; kind: "Link" };
    };
  };
  "pricing_template": {
    fields: PricingTemplateFieldName;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    links: {
      "client": { target: "party"; cardinality: "manyToOne"; kind: "Link" };
    };
  };
  "pricing_template_role": {
    fields: PricingTemplateRoleFieldName;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    links: {
      "template": { target: "pricing_template"; cardinality: "manyToOne"; kind: "Link" };
    };
  };
  "rfe": {
    fields: RfeFieldName;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    links: {
      "demand_order": { target: "orders"; cardinality: "manyToOne"; kind: "Link" };
      "supplier": { target: "party"; cardinality: "manyToOne"; kind: "Link" };
    };
  };
  "rfe_line_row": {
    fields: RfeLineRowFieldName;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    links: {
      "item_rev_id": { target: "item_revision"; cardinality: "manyToOne"; kind: "Link" };
      "order_line_id": { target: "order_line"; cardinality: "manyToOne"; kind: "Link" };
    };
  };
  "rfe_line_tier": {
    fields: RfeLineTierFieldName;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    links: {
      "rfe_line": { target: "rfe_line_row"; cardinality: "manyToOne"; kind: "Link" };
    };
  };
  "rfe_response": {
    fields: RfeResponseFieldName;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    links: {
      "rfe": { target: "rfe"; cardinality: "manyToOne"; kind: "Link" };
    };
  };
  "rfe_response_line": {
    fields: RfeResponseLineFieldName;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    links: {
      "response": { target: "rfe_response"; cardinality: "manyToOne"; kind: "Link" };
      "tier": { target: "rfe_line_tier"; cardinality: "manyToOne"; kind: "Link" };
    };
  };
  "supplier_capacity": {
    fields: SupplierCapacityFieldName;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    links: {
      "supplier": { target: "party"; cardinality: "manyToOne"; kind: "Link" };
    };
  };
  "supplier_cert": {
    fields: SupplierCertFieldName;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    links: {
      "supplier": { target: "party"; cardinality: "manyToOne"; kind: "Link" };
    };
  };
  "tq_definition": {
    fields: TqDefinitionFieldName;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    links: {
      "tasks": { target: "tq_sub_task_definition"; cardinality: "oneToMany"; kind: "Link" };
      "created_by": { target: "user"; cardinality: "manyToOne"; kind: "Link" };
      "last_modified_by": { target: "user"; cardinality: "manyToOne"; kind: "Link" };
    };
  };
  "tq_instance": {
    fields: TqInstanceFieldName;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    links: {
      "tq_definition": { target: "tq_definition"; cardinality: "manyToOne"; kind: "Link" };
      "current_task": { target: "tq_sub_task_instance"; cardinality: "manyToOne"; kind: "Link" };
      "current_status": { target: "tq_state_instance"; cardinality: "manyToOne"; kind: "Link" };
      "sub_task_history": { target: "tq_sub_task_instance"; cardinality: "oneToMany"; kind: "Link" };
      "assignee": { target: "user"; cardinality: "manyToOne"; kind: "Link" };
      "created_by": { target: "user"; cardinality: "manyToOne"; kind: "Link" };
      "last_modified_by": { target: "user"; cardinality: "manyToOne"; kind: "Link" };
    };
  };
  "tq_state_definition": {
    fields: TqStateDefinitionFieldName;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    links: {
      "created_by": { target: "user"; cardinality: "manyToOne"; kind: "Link" };
      "last_modified_by": { target: "user"; cardinality: "manyToOne"; kind: "Link" };
    };
  };
  "tq_state_instance": {
    fields: TqStateInstanceFieldName;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    links: {
      "tq_sub_task_instance": { target: "tq_sub_task_instance"; cardinality: "manyToOne"; kind: "Link" };
      "tq_state_definition": { target: "tq_state_definition"; cardinality: "manyToOne"; kind: "Link" };
      "created_by": { target: "user"; cardinality: "manyToOne"; kind: "Link" };
      "last_modified_by": { target: "user"; cardinality: "manyToOne"; kind: "Link" };
    };
  };
  "tq_sub_task_definition": {
    fields: TqSubTaskDefinitionFieldName;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    links: {
      "previous_task": { target: "tq_sub_task_definition"; cardinality: "manyToOne"; kind: "Link" };
      "next_task": { target: "tq_sub_task_definition"; cardinality: "manyToOne"; kind: "Link" };
      "states": { target: "tq_state_definition"; cardinality: "oneToMany"; kind: "Link" };
      "created_by": { target: "user"; cardinality: "manyToOne"; kind: "Link" };
      "last_modified_by": { target: "user"; cardinality: "manyToOne"; kind: "Link" };
    };
  };
  "tq_sub_task_instance": {
    fields: TqSubTaskInstanceFieldName;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    links: {
      "tq_instance": { target: "tq_instance"; cardinality: "manyToOne"; kind: "Link" };
      "tq_sub_task_definition": { target: "tq_sub_task_definition"; cardinality: "manyToOne"; kind: "Link" };
      "current_state": { target: "tq_state_definition"; cardinality: "manyToOne"; kind: "Link" };
      "status_history": { target: "tq_state_instance"; cardinality: "oneToMany"; kind: "Link" };
      "assignee": { target: "user"; cardinality: "manyToOne"; kind: "Link" };
      "created_by": { target: "user"; cardinality: "manyToOne"; kind: "Link" };
      "last_modified_by": { target: "user"; cardinality: "manyToOne"; kind: "Link" };
    };
  };
}

/** Valid field names on a given entity. */
export type FieldOf<E extends EntityName> = EntitySchema[E]['fields'];

/** Names of Link/Backlink fields on a given entity. */
export type LinkOf<E extends EntityName> = keyof EntitySchema[E]['links'] & string;

/** App-definition-key constant for a given entity. */
export type AppKeyOf<E extends EntityName> = EntitySchema[E]['appKey'];

/** Shape of `select` argument when authoring a saved-query DynQL body. */
export type SelectFor<E extends EntityName> = Partial<{
  [K in FieldOf<E>]:
    | boolean
    | (K extends LinkOf<E>
        ? {
            select?: Partial<Record<string, unknown>>;
            where?: Record<string, unknown>;
            limit?: number;
            offset?: number;
          }
        : never);
}>;

/** Comparison conditions allowed inside a `where` clause. */
export interface WhereCondition {
  equals?: unknown;
  not?: unknown;
  in?: readonly unknown[];
  gt?: unknown;
  gte?: unknown;
  lt?: unknown;
  lte?: unknown;
  contains?: string;
  startsWith?: string;
  endsWith?: string;
}

/** Shape of `where` argument. Keys constrained to known field names. */
export type WhereFor<E extends EntityName> = Partial<Record<FieldOf<E>, WhereCondition>>;

/** Shape of `data` argument for create/update. */
export type DataFor<E extends EntityName> = Partial<Record<FieldOf<E>, unknown>>;
