/* eslint-disable */
// AUTO-GENERATED by scripts/fetch-tenant-refs.ts - do not edit by hand.
// Source: Phoenix /data/internal/query/org_level
// Tenant reference snapshot — regenerated on every workspace bootstrap.

/** One Org Levels record (shape is tenant-defined; keys are open). */
export interface OrgLevelsRecord { [key: string]: unknown }

/** All Org Levels for this tenant (snapshot at bootstrap). */
export const ORG_LEVELS: ReadonlyArray<OrgLevelsRecord> = [];

export const ORG_LEVELS_COUNT = 0;
