/* eslint-disable */
// AUTO-GENERATED by scripts/fetch-preferences.ts - do not edit by hand.
// Source: Phoenix GET /api/internal/preferences (Branding category, current app).
//
// Baked at workspace bootstrap so the tenant/app branding (favicon, logo, theme)
// can be applied on first paint — BEFORE the runtime merged-preferences fetch
// resolves. usePreferences() seeds these as placeholder data; the live fetch
// then overrides. Empty in the shipped starter (no tenant bound yet).

export interface GeneratedPreference {
  name: string;
  value: string;
  category?: string;
  app_definition_key?: string;
  org?: string | null;
  user?: string | null;
  disabled?: boolean;
  [key: string]: unknown;
}

export const PREFERENCES: GeneratedPreference[] = [];
