/* eslint-disable */
// AUTO-GENERATED by scripts/fetch-enumerations.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/enum

export type EnumerationName = never;

/** Lookup of enumeration values by name. Empty when the tenant has
 *  no enumerations defined in Phoenix. */
export const ENUMERATION_VALUES: Record<string, readonly string[]> = {};

export type EnumerationValuesOf<_N extends EnumerationName> = never;
