/* eslint-disable */
// AUTO-GENERATED by scripts/fetch-related-screens.ts - do not edit by hand.
// Source: Phoenix GET /api/internal/component-definitions-all/screen

export interface RelatedScreenNavVariable {
  param: string;
  fullName: string;
  label: string;
  type: string;
  isArray: boolean;
  required: boolean;
}

export interface RelatedScreenEntry {
  appKey: string;
  appDefinition: string;
  name: string;
  label: string;
  description: string;
  navVariables: RelatedScreenNavVariable[];
  sidebarEligible: boolean;
}

export interface RelatedAppEntry {
  appKey: string;
  appDefinition: string;
  screens: RelatedScreenEntry[];
}

export const RELATED_APPS: RelatedAppEntry[] = [];

/** Flat lookup: `${appKey}::${screenName}` → entry. */
export const RELATED_SCREENS_BY_KEY: Record<string, RelatedScreenEntry> = {};
for (const app of RELATED_APPS) {
  for (const screen of app.screens) {
    RELATED_SCREENS_BY_KEY[`${app.appKey}::${screen.name}`] = screen;
  }
}
