/* eslint-disable */
// AUTO-GENERATED by scripts/fetch-saved-queries.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/saved-query
// Regenerated on every workspace bootstrap; stays in sync with
// src/types/saved-queries/*.ts.

import type { AllocationClearOrderInput, AllocationClearOrderRow } from './saved-queries/aswathtestapp_6a67823a8fa7215710927dbc/allocation_clear_order';
import type { AllocationCreateInput, AllocationCreateResult } from './saved-queries/aswathtestapp_6a67823a8fa7215710927dbc/allocation_create';
import type { CardAddInput, CardAddResult } from './saved-queries/aswathtestapp_6a67823a8fa7215710927dbc/card_add';
import type { CardLineAddInput, CardLineAddResult } from './saved-queries/aswathtestapp_6a67823a8fa7215710927dbc/card_line_add';
import type { CardRevsInput, CardRevsRow } from './saved-queries/aswathtestapp_6a67823a8fa7215710927dbc/card_revs';
import type { CardSpecApproveInput, CardSpecApproveResult } from './saved-queries/aswathtestapp_6a67823a8fa7215710927dbc/card_spec_approve';
import type { CardSpecCreateInput, CardSpecCreateResult } from './saved-queries/aswathtestapp_6a67823a8fa7215710927dbc/card_spec_create';
import type { CardSpecCreateV2Input, CardSpecCreateV2Result } from './saved-queries/aswathtestapp_6a67823a8fa7215710927dbc/card_spec_create_v2';
import type { CardSpecPdfSaveInput, CardSpecPdfSaveResult } from './saved-queries/aswathtestapp_6a67823a8fa7215710927dbc/card_spec_pdf_save';
import type { CardSpecSaveInput, CardSpecSaveResult } from './saved-queries/aswathtestapp_6a67823a8fa7215710927dbc/card_spec_save';
import type { CardTemplateCreateInput, CardTemplateCreateResult } from './saved-queries/aswathtestapp_6a67823a8fa7215710927dbc/card_template_create';
import type { CardTemplatesInput, CardTemplatesRow } from './saved-queries/aswathtestapp_6a67823a8fa7215710927dbc/card_templates';
import type { CardVariantApproveInput, CardVariantApproveResult } from './saved-queries/aswathtestapp_6a67823a8fa7215710927dbc/card_variant_approve';
import type { CardVariantCreateInput, CardVariantCreateResult } from './saved-queries/aswathtestapp_6a67823a8fa7215710927dbc/card_variant_create';
import type { ComponentItemCreateInput, ComponentItemCreateResult } from './saved-queries/aswathtestapp_6a67823a8fa7215710927dbc/component_item_create';
import type { ComponentLineCreateInput, ComponentLineCreateResult } from './saved-queries/aswathtestapp_6a67823a8fa7215710927dbc/component_line_create';
import type { ComponentRevCreateInput, ComponentRevCreateResult } from './saved-queries/aswathtestapp_6a67823a8fa7215710927dbc/component_rev_create';
import type { MarginOverrideCreateInput, MarginOverrideCreateResult } from './saved-queries/aswathtestapp_6a67823a8fa7215710927dbc/margin_override_create';
import type { MarginOverrideSupersedeInput, MarginOverrideSupersedeRow } from './saved-queries/aswathtestapp_6a67823a8fa7215710927dbc/margin_override_supersede';
import type { MyTasksInput, MyTasksRow } from './saved-queries/aswathtestapp_6a67823a8fa7215710927dbc/my_tasks';
import type { OrderAllocationGridInput, OrderAllocationGridResult } from './saved-queries/aswathtestapp_6a67823a8fa7215710927dbc/order_allocation_grid';
import type { OrderCardSpecInput, OrderCardSpecResult } from './saved-queries/aswathtestapp_6a67823a8fa7215710927dbc/order_card_spec';
import type { OrderCardVariantsInput, OrderCardVariantsRow } from './saved-queries/aswathtestapp_6a67823a8fa7215710927dbc/order_card_variants';
import type { OrderCardsInput, OrderCardsRow } from './saved-queries/aswathtestapp_6a67823a8fa7215710927dbc/order_cards';
import type { OrderCreateInput, OrderCreateResult } from './saved-queries/aswathtestapp_6a67823a8fa7215710927dbc/order_create';
import type { OrderDetailInput, OrderDetailResult } from './saved-queries/aswathtestapp_6a67823a8fa7215710927dbc/order_detail';
import type { OrderLineItemRepairInput, OrderLineItemRepairResult } from './saved-queries/aswathtestapp_6a67823a8fa7215710927dbc/order_line_item_repair';
import type { OrderLinkTqInput, OrderLinkTqResult } from './saved-queries/aswathtestapp_6a67823a8fa7215710927dbc/order_link_tq';
import type { OrderListInput, OrderListRow } from './saved-queries/aswathtestapp_6a67823a8fa7215710927dbc/order_list';
import type { OrderMarginOverridesInput, OrderMarginOverridesRow } from './saved-queries/aswathtestapp_6a67823a8fa7215710927dbc/order_margin_overrides';
import type { OrderQuoteGridInput, OrderQuoteGridResult } from './saved-queries/aswathtestapp_6a67823a8fa7215710927dbc/order_quote_grid';
import type { OrderRfesInput, OrderRfesRow } from './saved-queries/aswathtestapp_6a67823a8fa7215710927dbc/order_rfes';
import type { OrderActivityFeedInput, OrderActivityFeedResult } from './saved-queries/aswathtestapp_6a67823a8fa7215710927dbc/order_activity_feed';
import type { OrderQuoteEventsInput, OrderQuoteEventsRow } from './saved-queries/aswathtestapp_6a67823a8fa7215710927dbc/order_quote_events';
import type { PartyListInput, PartyListRow } from './saved-queries/aswathtestapp_6a67823a8fa7215710927dbc/party_list';
import type { PricingTemplateAdminInput, PricingTemplateAdminResult } from './saved-queries/aswathtestapp_6a67823a8fa7215710927dbc/pricing_template_admin';
import type { PricingTemplateCreateInput, PricingTemplateCreateResult } from './saved-queries/aswathtestapp_6a67823a8fa7215710927dbc/pricing_template_create';
import type { PricingTemplateEditorInput, PricingTemplateEditorResult } from './saved-queries/aswathtestapp_6a67823a8fa7215710927dbc/pricing_template_editor';
import type { PricingTemplateRoleCreateInput, PricingTemplateRoleCreateResult } from './saved-queries/aswathtestapp_6a67823a8fa7215710927dbc/pricing_template_role_create';
import type { PricingTemplateRoleUpdateInput, PricingTemplateRoleUpdateResult } from './saved-queries/aswathtestapp_6a67823a8fa7215710927dbc/pricing_template_role_update';
import type { PricingTemplateUpdateInput, PricingTemplateUpdateResult } from './saved-queries/aswathtestapp_6a67823a8fa7215710927dbc/pricing_template_update';
import type { PricingTemplatesInput, PricingTemplatesResult } from './saved-queries/aswathtestapp_6a67823a8fa7215710927dbc/pricing_templates';
import type { RfeCreateInput, RfeCreateResult } from './saved-queries/aswathtestapp_6a67823a8fa7215710927dbc/rfe_create';
import type { RfeDetailInput, RfeDetailResult } from './saved-queries/aswathtestapp_6a67823a8fa7215710927dbc/rfe_detail';
import type { RfeLineCreateInput, RfeLineCreateResult } from './saved-queries/aswathtestapp_6a67823a8fa7215710927dbc/rfe_line_create';
import type { RfeMarkRespondedInput, RfeMarkRespondedResult } from './saved-queries/aswathtestapp_6a67823a8fa7215710927dbc/rfe_mark_responded';
import type { RfeResponseDetailInput, RfeResponseDetailResult } from './saved-queries/aswathtestapp_6a67823a8fa7215710927dbc/rfe_response_detail';
import type { RfeResponseLineCreateInput, RfeResponseLineCreateResult } from './saved-queries/aswathtestapp_6a67823a8fa7215710927dbc/rfe_response_line_create';
import type { RfeResponseLineUpdateInput, RfeResponseLineUpdateResult } from './saved-queries/aswathtestapp_6a67823a8fa7215710927dbc/rfe_response_line_update';
import type { RfeResponseStartInput, RfeResponseStartResult } from './saved-queries/aswathtestapp_6a67823a8fa7215710927dbc/rfe_response_start';
import type { RfeResponseSubmitInput, RfeResponseSubmitResult } from './saved-queries/aswathtestapp_6a67823a8fa7215710927dbc/rfe_response_submit';
import type { RfeTierCreateInput, RfeTierCreateResult } from './saved-queries/aswathtestapp_6a67823a8fa7215710927dbc/rfe_tier_create';
import type { SupplierBoardInput, SupplierBoardResult } from './saved-queries/aswathtestapp_6a67823a8fa7215710927dbc/supplier_board';
import type { SupplierCapacityListInput, SupplierCapacityListRow } from './saved-queries/aswathtestapp_6a67823a8fa7215710927dbc/supplier_capacity_list';
import type { SupplierCertListInput, SupplierCertListRow } from './saved-queries/aswathtestapp_6a67823a8fa7215710927dbc/supplier_cert_list';
import type { SupplierListInput, SupplierListRow } from './saved-queries/aswathtestapp_6a67823a8fa7215710927dbc/supplier_list';
import type { SupplierPriceListInput, SupplierPriceListRow } from './saved-queries/aswathtestapp_6a67823a8fa7215710927dbc/supplier_price_list';
import type { TaskBoardInput, TaskBoardRow } from './saved-queries/aswathtestapp_6a67823a8fa7215710927dbc/task_board';
import type { TaskListInput, TaskListRow } from './saved-queries/aswathtestapp_6a67823a8fa7215710927dbc/task_list';
import type { TqAssignInput, TqAssignResult } from './saved-queries/aswathtestapp_6a67823a8fa7215710927dbc/tq_assign';
import type { TqCreateInput, TqCreateResult } from './saved-queries/aswathtestapp_6a67823a8fa7215710927dbc/tq_create';
import type { TqStageListInput, TqStageListRow } from './saved-queries/aswathtestapp_6a67823a8fa7215710927dbc/tq_stage_list';
import type { TqStateAddInput, TqStateAddResult } from './saved-queries/aswathtestapp_6a67823a8fa7215710927dbc/tq_state_add';
import type { TqStatusHistoryInput, TqStatusHistoryRow } from './saved-queries/aswathtestapp_6a67823a8fa7215710927dbc/tq_status_history';
import type { TqSubTaskAddInput, TqSubTaskAddResult } from './saved-queries/aswathtestapp_6a67823a8fa7215710927dbc/tq_sub_task_add';
import type { TqSubTaskAssignInput, TqSubTaskAssignRow } from './saved-queries/aswathtestapp_6a67823a8fa7215710927dbc/tq_sub_task_assign';
import type { UnassignedTasksInput, UnassignedTasksRow } from './saved-queries/aswathtestapp_6a67823a8fa7215710927dbc/unassigned_tasks';
import type { ZzLeadProbeInput, ZzLeadProbeRow } from './saved-queries/aswathtestapp_6a67823a8fa7215710927dbc/zz_lead_probe';
import type { ZzLeadProbeMultiInput, ZzLeadProbeMultiResult } from './saved-queries/aswathtestapp_6a67823a8fa7215710927dbc/zz_lead_probe_multi';

/** All known saved-query names (typed union). */
export type SavedQueryName = "order_activity_feed" | "order_quote_events" | "allocation_clear_order" | "allocation_create" | "card_add" | "card_line_add" | "card_revs" | "card_spec_approve" | "card_spec_create" | "card_spec_create_v2" | "card_spec_pdf_save" | "card_spec_save" | "card_template_create" | "card_template_update" | "card_templates" | "card_variant_approve" | "card_variant_create" | "component_item_create" | "component_line_create" | "component_rev_create" | "margin_override_create" | "margin_override_supersede" | "my_tasks" | "order_allocation_grid" | "order_card_spec" | "order_card_variants" | "order_cards" | "order_create" | "order_detail" | "order_line_item_repair" | "order_link_tq" | "order_list" | "order_relation_list" | "order_margin_overrides" | "order_quote_grid" | "order_rfes" | "party_list" | "pricing_template_admin" | "pricing_template_create" | "pricing_template_editor" | "pricing_template_role_create" | "pricing_template_role_update" | "pricing_template_update" | "pricing_templates" | "rfe_create" | "rfe_detail" | "rfe_line_create" | "rfe_mark_responded" | "rfe_response_detail" | "rfe_response_line_create" | "rfe_response_line_update" | "rfe_response_start" | "rfe_response_submit" | "rfe_tier_create" | "supplier_board" | "supplier_capacity_list" | "supplier_cert_list" | "supplier_list" | "supplier_price_list" | "task_board" | "task_list" | "tq_assign" | "tq_create" | "tq_stage_list" | "tq_state_add" | "tq_status_history" | "tq_sub_task_add" | "tq_sub_task_assign" | "unassigned_tasks" | "zz_lead_probe" | "zz_lead_probe_multi" | "order_fulfilment_grid" | "order_proposals" | "order_reviews" | "supplier_rfe_packet" | "order_plan" | "plan_create" | "plan_item_create" | "plan_item_stamp" | "plan_item_edit" | "plan_set_state" | "plan_item_pad" | "supply_order_list" | "supply_line_create" | "allocation_bind_award" | "award_record_create" | "client_admin" | "client_create" | "client_update";

/**
 * Master saved-query registry. Consumed by useSavedQueryList /
 * useSavedQuerySingle to derive input + row types per query name.
 */
export interface SavedQuerySchema {
  "allocation_clear_order": {
    input: AllocationClearOrderInput;
    row: AllocationClearOrderRow;
    isSingle: false;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "dynamic";
  };
  "allocation_create": {
    input: AllocationCreateInput;
    row: AllocationCreateResult;
    isSingle: true;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "dynamic";
  };
  "card_add": {
    input: CardAddInput;
    row: CardAddResult;
    isSingle: true;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "dynamic";
  };
  "card_line_add": {
    input: CardLineAddInput;
    row: CardLineAddResult;
    isSingle: true;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "dynamic";
  };
  "card_revs": {
    input: CardRevsInput;
    row: CardRevsRow;
    isSingle: false;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "dynamic";
  };
  "card_spec_approve": {
    input: CardSpecApproveInput;
    row: CardSpecApproveResult;
    isSingle: true;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "common_table_expression";
  };
  "card_spec_create": {
    input: CardSpecCreateInput;
    row: CardSpecCreateResult;
    isSingle: true;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "common_table_expression";
  };
  "card_spec_create_v2": {
    input: CardSpecCreateV2Input;
    row: CardSpecCreateV2Result;
    isSingle: true;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "common_table_expression";
  };
  "card_spec_pdf_save": {
    input: CardSpecPdfSaveInput;
    row: CardSpecPdfSaveResult;
    isSingle: true;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "dynamic";
  };
  "card_spec_save": {
    input: CardSpecSaveInput;
    row: CardSpecSaveResult;
    isSingle: true;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "dynamic";
  };
  "card_template_create": {
    input: CardTemplateCreateInput;
    row: CardTemplateCreateResult;
    isSingle: true;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "dynamic";
  };
  "card_template_update": {
    input: CardTemplateCreateInput;
    row: CardTemplateCreateResult;
    isSingle: true;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "dynamic";
  };
  "card_templates": {
    input: CardTemplatesInput;
    row: CardTemplatesRow;
    isSingle: false;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "dynamic";
  };
  "card_variant_approve": {
    input: CardVariantApproveInput;
    row: CardVariantApproveResult;
    isSingle: true;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "dynamic";
  };
  "card_variant_create": {
    input: CardVariantCreateInput;
    row: CardVariantCreateResult;
    isSingle: true;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "dynamic";
  };
  "component_item_create": {
    input: ComponentItemCreateInput;
    row: ComponentItemCreateResult;
    isSingle: true;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "dynamic";
  };
  "component_line_create": {
    input: ComponentLineCreateInput;
    row: ComponentLineCreateResult;
    isSingle: true;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "dynamic";
  };
  "component_rev_create": {
    input: ComponentRevCreateInput;
    row: ComponentRevCreateResult;
    isSingle: true;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "dynamic";
  };
  "margin_override_create": {
    input: MarginOverrideCreateInput;
    row: MarginOverrideCreateResult;
    isSingle: true;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "dynamic";
  };
  "margin_override_supersede": {
    input: MarginOverrideSupersedeInput;
    row: MarginOverrideSupersedeRow;
    isSingle: false;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "dynamic";
  };
  "my_tasks": {
    input: MyTasksInput;
    row: MyTasksRow;
    isSingle: false;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "dynamic";
  };
  "order_allocation_grid": {
    input: OrderAllocationGridInput;
    row: OrderAllocationGridResult;
    isSingle: true;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "multi_query";
  };
  "order_card_spec": {
    input: OrderCardSpecInput;
    row: OrderCardSpecResult;
    isSingle: true;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "multi_query";
  };
  "order_card_variants": {
    input: OrderCardVariantsInput;
    row: OrderCardVariantsRow;
    isSingle: false;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "dynamic";
  };
  "order_cards": {
    input: OrderCardsInput;
    row: OrderCardsRow;
    isSingle: false;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "dynamic";
  };
  "order_create": {
    input: OrderCreateInput;
    row: OrderCreateResult;
    isSingle: true;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "common_table_expression";
  };
  "order_detail": {
    input: OrderDetailInput;
    row: OrderDetailResult;
    isSingle: true;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "dynamic";
  };
  "order_line_item_repair": {
    input: OrderLineItemRepairInput;
    row: OrderLineItemRepairResult;
    isSingle: true;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "common_table_expression";
  };
  "order_link_tq": {
    input: OrderLinkTqInput;
    row: OrderLinkTqResult;
    isSingle: true;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "common_table_expression";
  };
  "order_list": {
    input: OrderListInput;
    row: OrderListRow;
    isSingle: false;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "dynamic";
  };
  "order_relation_list": {
    input: OrderListInput;
    row: OrderListRow;
    isSingle: false;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "dynamic";
  };
  "order_margin_overrides": {
    input: OrderMarginOverridesInput;
    row: OrderMarginOverridesRow;
    isSingle: false;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "dynamic";
  };
  "order_quote_grid": {
    input: OrderQuoteGridInput;
    row: OrderQuoteGridResult;
    isSingle: true;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "multi_query";
  };
  "order_activity_feed": {
    input: OrderActivityFeedInput;
    row: OrderActivityFeedResult;
    isSingle: true;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "multi_query";
  };
  "order_quote_events": {
    input: OrderQuoteEventsInput;
    row: OrderQuoteEventsRow;
    isSingle: false;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "dynamic";
  };
  "order_rfes": {
    input: OrderRfesInput;
    row: OrderRfesRow;
    isSingle: false;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "dynamic";
  };
  "party_list": {
    input: PartyListInput;
    row: PartyListRow;
    isSingle: false;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "dynamic";
  };
  "pricing_template_admin": {
    input: PricingTemplateAdminInput;
    row: PricingTemplateAdminResult;
    isSingle: true;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "multi_query";
  };
  "pricing_template_create": {
    input: PricingTemplateCreateInput;
    row: PricingTemplateCreateResult;
    isSingle: true;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "dynamic";
  };
  "pricing_template_editor": {
    input: PricingTemplateEditorInput;
    row: PricingTemplateEditorResult;
    isSingle: true;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "multi_query";
  };
  "pricing_template_role_create": {
    input: PricingTemplateRoleCreateInput;
    row: PricingTemplateRoleCreateResult;
    isSingle: true;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "dynamic";
  };
  "pricing_template_role_update": {
    input: PricingTemplateRoleUpdateInput;
    row: PricingTemplateRoleUpdateResult;
    isSingle: true;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "dynamic";
  };
  "pricing_template_update": {
    input: PricingTemplateUpdateInput;
    row: PricingTemplateUpdateResult;
    isSingle: true;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "dynamic";
  };
  "pricing_templates": {
    input: PricingTemplatesInput;
    row: PricingTemplatesResult;
    isSingle: true;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "multi_query";
  };
  "rfe_create": {
    input: RfeCreateInput;
    row: RfeCreateResult;
    isSingle: true;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "common_table_expression";
  };
  "rfe_detail": {
    input: RfeDetailInput;
    row: RfeDetailResult;
    isSingle: true;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "multi_query";
  };
  "rfe_line_create": {
    input: RfeLineCreateInput;
    row: RfeLineCreateResult;
    isSingle: true;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "common_table_expression";
  };
  "rfe_mark_responded": {
    input: RfeMarkRespondedInput;
    row: RfeMarkRespondedResult;
    isSingle: true;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "dynamic";
  };
  "rfe_response_detail": {
    input: RfeResponseDetailInput;
    row: RfeResponseDetailResult;
    isSingle: true;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "multi_query";
  };
  "rfe_response_line_create": {
    input: RfeResponseLineCreateInput;
    row: RfeResponseLineCreateResult;
    isSingle: true;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "dynamic";
  };
  "rfe_response_line_update": {
    input: RfeResponseLineUpdateInput;
    row: RfeResponseLineUpdateResult;
    isSingle: true;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "dynamic";
  };
  "rfe_response_start": {
    input: RfeResponseStartInput;
    row: RfeResponseStartResult;
    isSingle: true;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "dynamic";
  };
  "rfe_response_submit": {
    input: RfeResponseSubmitInput;
    row: RfeResponseSubmitResult;
    isSingle: true;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "dynamic";
  };
  "rfe_tier_create": {
    input: RfeTierCreateInput;
    row: RfeTierCreateResult;
    isSingle: true;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "dynamic";
  };
  "supplier_board": {
    input: SupplierBoardInput;
    row: SupplierBoardResult;
    isSingle: true;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "multi_query";
  };
  "supplier_capacity_list": {
    input: SupplierCapacityListInput;
    row: SupplierCapacityListRow;
    isSingle: false;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "dynamic";
  };
  "supplier_cert_list": {
    input: SupplierCertListInput;
    row: SupplierCertListRow;
    isSingle: false;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "dynamic";
  };
  "supplier_list": {
    input: SupplierListInput;
    row: SupplierListRow;
    isSingle: false;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "dynamic";
  };
  "supply_order_list": {
    input: SupplierListInput;
    row: SupplierListRow;
    isSingle: false;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "dynamic";
  };
  "supplier_price_list": {
    input: SupplierPriceListInput;
    row: SupplierPriceListRow;
    isSingle: false;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "dynamic";
  };
  "task_board": {
    input: TaskBoardInput;
    row: TaskBoardRow;
    isSingle: false;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "multi_query";
  };
  "task_list": {
    input: TaskListInput;
    row: TaskListRow;
    isSingle: false;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "dynamic";
  };
  "tq_assign": {
    input: TqAssignInput;
    row: TqAssignResult;
    isSingle: true;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "dynamic";
  };
  "tq_create": {
    input: TqCreateInput;
    row: TqCreateResult;
    isSingle: true;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "common_table_expression";
  };
  "tq_stage_list": {
    input: TqStageListInput;
    row: TqStageListRow;
    isSingle: false;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "dynamic";
  };
  "tq_state_add": {
    input: TqStateAddInput;
    row: TqStateAddResult;
    isSingle: true;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "common_table_expression";
  };
  "tq_status_history": {
    input: TqStatusHistoryInput;
    row: TqStatusHistoryRow;
    isSingle: false;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "dynamic";
  };
  "tq_sub_task_add": {
    input: TqSubTaskAddInput;
    row: TqSubTaskAddResult;
    isSingle: true;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "common_table_expression";
  };
  "tq_sub_task_assign": {
    input: TqSubTaskAssignInput;
    row: TqSubTaskAssignRow;
    isSingle: false;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "dynamic";
  };
  "unassigned_tasks": {
    input: UnassignedTasksInput;
    row: UnassignedTasksRow;
    isSingle: false;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "dynamic";
  };
  "zz_lead_probe": {
    input: ZzLeadProbeInput;
    row: ZzLeadProbeRow;
    isSingle: false;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "dynamic";
  };
  // Added by hand: the codegen endpoint (component-definitions-all) is 403ed
  // by the edge WAF from this workspace, so these four queries — created
  // through the data-manager API — never made it into the generated schema.
  // Shapes are left open; their consumers cast to a local interface.
  "order_reviews": {
    input: Record<string, unknown>;
    row: Record<string, unknown>;
    isSingle: false;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "dynamic";
  };
  "order_proposals": {
    input: Record<string, unknown>;
    row: Record<string, unknown>;
    isSingle: false;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "dynamic";
  };
  "order_fulfilment_grid": {
    input: Record<string, unknown>;
    row: Record<string, unknown>;
    isSingle: true;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "multi_query";
  };
  "supplier_rfe_packet": {
    input: Record<string, unknown>;
    row: Record<string, unknown>;
    isSingle: true;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "multi_query";
  };
  "order_plan": {
    input: Record<string, unknown>;
    row: Record<string, unknown>;
    isSingle: true;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "multi_query";
  };
  "plan_create": {
    input: Record<string, unknown>;
    row: Record<string, unknown>;
    isSingle: false;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "dynamic";
  };
  "plan_item_create": {
    input: Record<string, unknown>;
    row: Record<string, unknown>;
    isSingle: false;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "dynamic";
  };
  "plan_item_stamp": {
    input: Record<string, unknown>;
    row: Record<string, unknown>;
    isSingle: false;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "dynamic";
  };
  "plan_item_edit": {
    input: Record<string, unknown>;
    row: Record<string, unknown>;
    isSingle: false;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "dynamic";
  };
  "plan_set_state": {
    input: Record<string, unknown>;
    row: Record<string, unknown>;
    isSingle: false;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "dynamic";
  };
  "plan_item_pad": {
    input: Record<string, unknown>;
    row: Record<string, unknown>;
    isSingle: false;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "dynamic";
  };
  "supply_line_create": {
    input: Record<string, unknown>;
    row: Record<string, unknown>;
    isSingle: false;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "dynamic";
  };
  "allocation_bind_award": {
    input: Record<string, unknown>;
    row: Record<string, unknown>;
    isSingle: false;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "dynamic";
  };
  "award_record_create": {
    input: Record<string, unknown>;
    row: Record<string, unknown>;
    isSingle: false;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "dynamic";
  };
  "client_admin": {
    input: Record<string, unknown>;
    row: Record<string, unknown>;
    isSingle: true;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "multi_query";
  };
  "client_create": {
    input: Record<string, unknown>;
    row: Record<string, unknown>;
    isSingle: false;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "dynamic";
  };
  "client_update": {
    input: Record<string, unknown>;
    row: Record<string, unknown>;
    isSingle: false;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "dynamic";
  };
  "zz_lead_probe_multi": {
    input: ZzLeadProbeMultiInput;
    row: ZzLeadProbeMultiResult;
    isSingle: true;
    appKey: "aswathtestapp_6a67823a8fa7215710927dbc";
    type: "multi_query";
  };
}

/** Input shape for a given saved query. */
export type SavedQueryInputOf<N extends SavedQueryName> = SavedQuerySchema[N]['input'];

/** Output row (list) or result (single) for a given saved query. */
export type SavedQueryRowOf<N extends SavedQueryName> = SavedQuerySchema[N]['row'];

/** Whether the saved query is single-output. */
export type SavedQueryIsSingleOf<N extends SavedQueryName> = SavedQuerySchema[N]['isSingle'];

/** Target app-definition key for cross-app saved queries. */
export type SavedQueryAppKeyOf<N extends SavedQueryName> = SavedQuerySchema[N]['appKey'];

/** Query type (dynamic|sql|multi_query|common_table_expression|patch). */
export type SavedQueryTypeOf<N extends SavedQueryName> = SavedQuerySchema[N]['type'];

/** Runtime map of saved-query name → target app-definition key. */
export const SAVED_QUERY_APP_KEYS: Record<SavedQueryName, string> = {
  "allocation_clear_order": "aswathtestapp_6a67823a8fa7215710927dbc",
  "allocation_create": "aswathtestapp_6a67823a8fa7215710927dbc",
  "card_add": "aswathtestapp_6a67823a8fa7215710927dbc",
  "card_line_add": "aswathtestapp_6a67823a8fa7215710927dbc",
  "card_revs": "aswathtestapp_6a67823a8fa7215710927dbc",
  "card_spec_approve": "aswathtestapp_6a67823a8fa7215710927dbc",
  "card_spec_create": "aswathtestapp_6a67823a8fa7215710927dbc",
  "card_spec_create_v2": "aswathtestapp_6a67823a8fa7215710927dbc",
  "card_spec_pdf_save": "aswathtestapp_6a67823a8fa7215710927dbc",
  "card_spec_save": "aswathtestapp_6a67823a8fa7215710927dbc",
  "card_template_create": "aswathtestapp_6a67823a8fa7215710927dbc",
  "card_template_update": "aswathtestapp_6a67823a8fa7215710927dbc",
  "card_templates": "aswathtestapp_6a67823a8fa7215710927dbc",
  "card_variant_approve": "aswathtestapp_6a67823a8fa7215710927dbc",
  "card_variant_create": "aswathtestapp_6a67823a8fa7215710927dbc",
  "component_item_create": "aswathtestapp_6a67823a8fa7215710927dbc",
  "component_line_create": "aswathtestapp_6a67823a8fa7215710927dbc",
  "component_rev_create": "aswathtestapp_6a67823a8fa7215710927dbc",
  "margin_override_create": "aswathtestapp_6a67823a8fa7215710927dbc",
  "margin_override_supersede": "aswathtestapp_6a67823a8fa7215710927dbc",
  "my_tasks": "aswathtestapp_6a67823a8fa7215710927dbc",
  "order_allocation_grid": "aswathtestapp_6a67823a8fa7215710927dbc",
  "order_card_spec": "aswathtestapp_6a67823a8fa7215710927dbc",
  "order_card_variants": "aswathtestapp_6a67823a8fa7215710927dbc",
  "order_cards": "aswathtestapp_6a67823a8fa7215710927dbc",
  "order_create": "aswathtestapp_6a67823a8fa7215710927dbc",
  "order_detail": "aswathtestapp_6a67823a8fa7215710927dbc",
  "order_line_item_repair": "aswathtestapp_6a67823a8fa7215710927dbc",
  "order_link_tq": "aswathtestapp_6a67823a8fa7215710927dbc",
  "order_list": "aswathtestapp_6a67823a8fa7215710927dbc",
  "order_relation_list": "aswathtestapp_6a67823a8fa7215710927dbc",
  "order_margin_overrides": "aswathtestapp_6a67823a8fa7215710927dbc",
  "order_quote_grid": "aswathtestapp_6a67823a8fa7215710927dbc",
  "order_activity_feed": "aswathtestapp_6a67823a8fa7215710927dbc",
  "order_quote_events": "aswathtestapp_6a67823a8fa7215710927dbc",
  "order_rfes": "aswathtestapp_6a67823a8fa7215710927dbc",
  "party_list": "aswathtestapp_6a67823a8fa7215710927dbc",
  "pricing_template_admin": "aswathtestapp_6a67823a8fa7215710927dbc",
  "pricing_template_create": "aswathtestapp_6a67823a8fa7215710927dbc",
  "pricing_template_editor": "aswathtestapp_6a67823a8fa7215710927dbc",
  "pricing_template_role_create": "aswathtestapp_6a67823a8fa7215710927dbc",
  "pricing_template_role_update": "aswathtestapp_6a67823a8fa7215710927dbc",
  "pricing_template_update": "aswathtestapp_6a67823a8fa7215710927dbc",
  "pricing_templates": "aswathtestapp_6a67823a8fa7215710927dbc",
  "rfe_create": "aswathtestapp_6a67823a8fa7215710927dbc",
  "rfe_detail": "aswathtestapp_6a67823a8fa7215710927dbc",
  "rfe_line_create": "aswathtestapp_6a67823a8fa7215710927dbc",
  "rfe_mark_responded": "aswathtestapp_6a67823a8fa7215710927dbc",
  "rfe_response_detail": "aswathtestapp_6a67823a8fa7215710927dbc",
  "rfe_response_line_create": "aswathtestapp_6a67823a8fa7215710927dbc",
  "rfe_response_line_update": "aswathtestapp_6a67823a8fa7215710927dbc",
  "rfe_response_start": "aswathtestapp_6a67823a8fa7215710927dbc",
  "rfe_response_submit": "aswathtestapp_6a67823a8fa7215710927dbc",
  "rfe_tier_create": "aswathtestapp_6a67823a8fa7215710927dbc",
  "supplier_board": "aswathtestapp_6a67823a8fa7215710927dbc",
  "supplier_capacity_list": "aswathtestapp_6a67823a8fa7215710927dbc",
  "supplier_cert_list": "aswathtestapp_6a67823a8fa7215710927dbc",
  "supplier_list": "aswathtestapp_6a67823a8fa7215710927dbc",
  "supply_order_list": "aswathtestapp_6a67823a8fa7215710927dbc",
  "supplier_price_list": "aswathtestapp_6a67823a8fa7215710927dbc",
  "task_board": "aswathtestapp_6a67823a8fa7215710927dbc",
  "task_list": "aswathtestapp_6a67823a8fa7215710927dbc",
  "tq_assign": "aswathtestapp_6a67823a8fa7215710927dbc",
  "tq_create": "aswathtestapp_6a67823a8fa7215710927dbc",
  "tq_stage_list": "aswathtestapp_6a67823a8fa7215710927dbc",
  "tq_state_add": "aswathtestapp_6a67823a8fa7215710927dbc",
  "tq_status_history": "aswathtestapp_6a67823a8fa7215710927dbc",
  "tq_sub_task_add": "aswathtestapp_6a67823a8fa7215710927dbc",
  "tq_sub_task_assign": "aswathtestapp_6a67823a8fa7215710927dbc",
  "unassigned_tasks": "aswathtestapp_6a67823a8fa7215710927dbc",
  "zz_lead_probe": "aswathtestapp_6a67823a8fa7215710927dbc",
  "zz_lead_probe_multi": "aswathtestapp_6a67823a8fa7215710927dbc",
  "order_fulfilment_grid": "aswathtestapp_6a67823a8fa7215710927dbc",
  "order_proposals": "aswathtestapp_6a67823a8fa7215710927dbc",
  "order_reviews": "aswathtestapp_6a67823a8fa7215710927dbc",
  "supplier_rfe_packet": "aswathtestapp_6a67823a8fa7215710927dbc",
  "order_plan": "aswathtestapp_6a67823a8fa7215710927dbc",
  "plan_create": "aswathtestapp_6a67823a8fa7215710927dbc",
  "plan_item_create": "aswathtestapp_6a67823a8fa7215710927dbc",
  "plan_item_stamp": "aswathtestapp_6a67823a8fa7215710927dbc",
  "plan_item_edit": "aswathtestapp_6a67823a8fa7215710927dbc",
  "plan_set_state": "aswathtestapp_6a67823a8fa7215710927dbc",
  "plan_item_pad": "aswathtestapp_6a67823a8fa7215710927dbc",
  "supply_line_create": "aswathtestapp_6a67823a8fa7215710927dbc",
  "allocation_bind_award": "aswathtestapp_6a67823a8fa7215710927dbc",
  "award_record_create": "aswathtestapp_6a67823a8fa7215710927dbc",
  "client_admin": "aswathtestapp_6a67823a8fa7215710927dbc",
  "client_create": "aswathtestapp_6a67823a8fa7215710927dbc",
  "client_update": "aswathtestapp_6a67823a8fa7215710927dbc",
};

/** Runtime map of saved-query name → query type (dynamic|sql|patch|…). */
export const SAVED_QUERY_TYPES: Record<SavedQueryName, string> = {
  "allocation_clear_order": "dynamic",
  "allocation_create": "dynamic",
  "card_add": "dynamic",
  "card_line_add": "dynamic",
  "card_revs": "dynamic",
  "card_spec_approve": "common_table_expression",
  "card_spec_create": "common_table_expression",
  "card_spec_create_v2": "common_table_expression",
  "card_spec_pdf_save": "dynamic",
  "card_spec_save": "dynamic",
  "card_template_create": "dynamic",
  "card_template_update": "dynamic",
  "card_templates": "dynamic",
  "card_variant_approve": "dynamic",
  "card_variant_create": "dynamic",
  "component_item_create": "dynamic",
  "component_line_create": "dynamic",
  "component_rev_create": "dynamic",
  "margin_override_create": "dynamic",
  "margin_override_supersede": "dynamic",
  "my_tasks": "dynamic",
  "order_allocation_grid": "multi_query",
  "order_card_spec": "multi_query",
  "order_card_variants": "dynamic",
  "order_cards": "dynamic",
  "order_create": "common_table_expression",
  "order_detail": "dynamic",
  "order_line_item_repair": "common_table_expression",
  "order_link_tq": "common_table_expression",
  "order_list": "dynamic",
  "order_relation_list": "dynamic",
  "order_margin_overrides": "dynamic",
  "order_quote_grid": "multi_query",
  "order_activity_feed": "multi_query",
  "order_quote_events": "dynamic",
  "order_rfes": "dynamic",
  "party_list": "dynamic",
  "pricing_template_admin": "multi_query",
  "pricing_template_create": "dynamic",
  "pricing_template_editor": "multi_query",
  "pricing_template_role_create": "dynamic",
  "pricing_template_role_update": "dynamic",
  "pricing_template_update": "dynamic",
  "pricing_templates": "multi_query",
  "rfe_create": "common_table_expression",
  "rfe_detail": "multi_query",
  "rfe_line_create": "common_table_expression",
  "rfe_mark_responded": "dynamic",
  "rfe_response_detail": "multi_query",
  "rfe_response_line_create": "dynamic",
  "rfe_response_line_update": "dynamic",
  "rfe_response_start": "dynamic",
  "rfe_response_submit": "dynamic",
  "rfe_tier_create": "dynamic",
  "supplier_board": "multi_query",
  "supplier_capacity_list": "dynamic",
  "supplier_cert_list": "dynamic",
  "supplier_list": "dynamic",
  "supply_order_list": "dynamic",
  "supplier_price_list": "dynamic",
  "task_board": "multi_query",
  "task_list": "dynamic",
  "tq_assign": "dynamic",
  "tq_create": "common_table_expression",
  "tq_stage_list": "dynamic",
  "tq_state_add": "common_table_expression",
  "tq_status_history": "dynamic",
  "tq_sub_task_add": "common_table_expression",
  "tq_sub_task_assign": "dynamic",
  "unassigned_tasks": "dynamic",
  "zz_lead_probe": "dynamic",
  "zz_lead_probe_multi": "multi_query",
  "order_fulfilment_grid": "multi_query",
  "order_proposals": "dynamic",
  "order_reviews": "dynamic",
  "supplier_rfe_packet": "multi_query",
  "order_plan": "multi_query",
  "plan_create": "dynamic",
  "plan_item_create": "dynamic",
  "plan_item_stamp": "dynamic",
  "plan_item_edit": "dynamic",
  "plan_set_state": "dynamic",
  "plan_item_pad": "dynamic",
  "supply_line_create": "dynamic",
  "allocation_bind_award": "dynamic",
  "award_record_create": "dynamic",
  "client_admin": "multi_query",
  "client_create": "dynamic",
  "client_update": "dynamic",
};

/** Runtime map of saved-query name → write op (insert|update|delete), '' for reads. */
export const SAVED_QUERY_OPERATIONS: Record<SavedQueryName, string> = {
  "allocation_clear_order": "delete",
  "allocation_create": "insert",
  "card_add": "insert",
  "card_line_add": "insert",
  "card_revs": "",
  "card_spec_approve": "update",
  "card_spec_create": "insert",
  "card_spec_create_v2": "insert",
  "card_spec_pdf_save": "update",
  "card_spec_save": "update",
  "card_template_create": "insert",
  "card_template_update": "update",
  "card_templates": "",
  "card_variant_approve": "update",
  "card_variant_create": "insert",
  "component_item_create": "insert",
  "component_line_create": "insert",
  "component_rev_create": "insert",
  "margin_override_create": "insert",
  "margin_override_supersede": "update",
  "my_tasks": "",
  "order_allocation_grid": "",
  "order_card_spec": "",
  "order_card_variants": "",
  "order_cards": "",
  "order_create": "insert",
  "order_detail": "",
  "order_line_item_repair": "update",
  "order_link_tq": "update",
  "order_list": "",
  "order_relation_list": "",
  "order_margin_overrides": "",
  "order_quote_grid": "",
  "order_activity_feed": "",
  "order_quote_events": "",
  "order_rfes": "",
  "party_list": "",
  "pricing_template_admin": "",
  "pricing_template_create": "insert",
  "pricing_template_editor": "",
  "pricing_template_role_create": "insert",
  "pricing_template_role_update": "update",
  "pricing_template_update": "update",
  "pricing_templates": "",
  "rfe_create": "insert",
  "rfe_detail": "",
  "rfe_line_create": "insert",
  "rfe_mark_responded": "update",
  "rfe_response_detail": "",
  "rfe_response_line_create": "insert",
  "rfe_response_line_update": "update",
  "rfe_response_start": "insert",
  "rfe_response_submit": "update",
  "rfe_tier_create": "insert",
  "supplier_board": "",
  "supplier_capacity_list": "",
  "supplier_cert_list": "",
  "supplier_list": "",
  "supply_order_list": "",
  "supplier_price_list": "",
  "task_board": "",
  "task_list": "",
  "tq_assign": "update",
  "tq_create": "insert",
  "tq_stage_list": "",
  "tq_state_add": "update",
  "tq_status_history": "",
  "tq_sub_task_add": "update",
  "tq_sub_task_assign": "update",
  "unassigned_tasks": "",
  "zz_lead_probe": "",
  "zz_lead_probe_multi": "",
  "order_fulfilment_grid": "read",
  "order_proposals": "read",
  "order_reviews": "read",
  "supplier_rfe_packet": "read",
  "order_plan": "read",
  "plan_create": "write",
  "plan_item_create": "write",
  "plan_item_stamp": "write",
  "plan_item_edit": "write",
  "plan_set_state": "write",
  "plan_item_pad": "write",
  "supply_line_create": "write",
  "allocation_bind_award": "write",
  "award_record_create": "write",
  "client_admin": "read",
  "client_create": "write",
  "client_update": "write",
};
