/* eslint-disable */
// AUTO-GENERATED by scripts/fetch-skills.ts - do not edit by hand.
// Source: Phoenix GET /api/internal/component-definitions-all/skill-definition
// Regenerated on every workspace bootstrap.

export interface SkillEntry {
  appKey: string;
  appDefinition: string;
  name: string;
  label: string;
  description: string;
  subType: string;
  tags: string[];
}

/** All known skill names (typed union). */
export type SkillName = never;

/** Every platform skill (agent) for this tenant. */
export const SKILLS: SkillEntry[] = [];

/** Map of skill name → its app_definition_key. */
export const SKILL_APP_KEYS: Record<string, string> = {};

/** Flat lookup: skill name → entry. */
export const SKILLS_BY_NAME: Record<string, SkillEntry> = {};
