/* eslint-disable */
// AUTO-GENERATED by scripts/fetch-workflows.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/workflow
// Regenerated on every workspace bootstrap; stays in sync with
// src/types/workflows/*.ts.

export type WorkflowName = never;

export interface WorkflowSchema {}

export type WorkflowInputOf<_N extends WorkflowName> = never;
export type WorkflowOutputOf<_N extends WorkflowName> = never;
export type WorkflowAppKeyOf<_N extends WorkflowName> = never;
