// AUTO-GENERATED by scripts/fetch-entities.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/entity
// Tenant scope: see TENANT_ID used at generation time.

import type { CardSpec } from '@/types/entities/aswathtestapp_6a67823a8fa7215710927dbc/card_spec';
import type { Orders } from '@/types/entities/aswathtestapp_6a67823a8fa7215710927dbc/orders';

/**
 * Card Variant
 * A variation of a card on one order. Shares the base card spec and records only what differs, so a run can carry a Thank-You and a Valentines version without duplicating the whole specification. At least one variation must be approved before the order can be sent for quotes.
 */
export interface CardVariant {
  /** ID */
  id: string;
  /** Approved — Send for quotes stays disabled until at least one variation is approved. */
  approved?: boolean;
  /** Approved At */
  approved_at?: string;
  /** Card Spec Ref — FK -> card_spec. The base card this varies from. */
  card_spec_ref?: CardSpec;
  /** Created At */
  created_at?: string;
  /** Delta — Only the spec fields that differ from the base card, as JSON. An empty object means identical to the base. */
  delta?: Record<string, unknown>;
  /** Due Date */
  due_date?: string;
  /** Label — What this variation is called, for example Thank-You or Valentines. */
  label?: string;
  /** Order Ref — FK -> orders. */
  order_ref?: Orders;
  /** Qty — Units of this variation. */
  qty?: number;
}

export const CARD_VARIANT_APP_KEY = "aswathtestapp_6a67823a8fa7215710927dbc";

export type CardVariantSchema = { 'card_variant': CardVariant };

/**
 * Field-level validation declared in Phoenix for `card_variant`.
 * Use as DEFAULT UI constraints when building a form for this entity
 * (mark required fields, set maxLength / min / max, apply regex / oneOf).
 * Only fields that are required or carry a constraint are listed.
 */
export const CARD_VARIANT_FIELD_CONSTRAINTS = {
  id: { required: true },
} as const;
