// AUTO-GENERATED by scripts/fetch-entities.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/entity
// Tenant scope: see TENANT_ID used at generation time.

import type { Item } from '@/types/entities/aswathtestapp_6a67823a8fa7215710927dbc/item';

/**
 * Item Revision
 * A frozen, numbered version of an item's definition.
 */
export interface ItemRevision {
  /** Id — PK */
  id: string;
  /** Item Id — FK -> Item */
  item_id?: Item;
  /** Rev — Revision number */
  rev?: number;
  /** Status — Revision status: draft, active or superseded */
  status?: string;
}

export const ITEM_REVISION_APP_KEY = "aswathtestapp_6a67823a8fa7215710927dbc";

export type ItemRevisionSchema = { 'item_revision': ItemRevision };

/**
 * Field-level validation declared in Phoenix for `item_revision`.
 * Use as DEFAULT UI constraints when building a form for this entity
 * (mark required fields, set maxLength / min / max, apply regex / oneOf).
 * Only fields that are required or carry a constraint are listed.
 */
export const ITEM_REVISION_FIELD_CONSTRAINTS = {
  id: { required: true },
} as const;
