// AUTO-GENERATED by scripts/fetch-entities.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/entity
// Tenant scope: see TENANT_ID used at generation time.

import type { OrderLine } from '@/types/entities/aswathtestapp_6a67823a8fa7215710927dbc/order_line';
import type { Orders } from '@/types/entities/aswathtestapp_6a67823a8fa7215710927dbc/orders';
import type { Party } from '@/types/entities/aswathtestapp_6a67823a8fa7215710927dbc/party';

/**
 * Line Allocation
 * Award allocation for one order line. A line can be awarded whole to one supplier, split by quantity across several, or have a component material carved out to a different supplier that then ships to the assembler.
 */
export interface LineAllocation {
  /** ID */
  id: string;
  /** Assembler — FK -> party. On a carve_out row, the supplier the carved material ships to. */
  assembler?: Party;
  /** Component Role — Only set on a carve_out row: card, carrier, features or setup. */
  component_role?: string;
  /** Created At */
  created_at?: string;
  /** Exception Note — Why this allocation departs from the single-winner default. */
  exception_note?: string;
  /** Kind — line for a quantity allocation, carve_out for a component material awarded to a different supplier */
  kind?: string;
  /** Order Line Ref — FK -> order_line. */
  order_line_ref?: OrderLine;
  /** Order Ref — FK -> orders. Named order_ref because the DynQL filter parser treats order as a reserved word. */
  order_ref?: Orders;
  /** Qty — Units allocated to this supplier for this line. */
  qty?: number;
  /** Supplier — FK -> party. The supplier awarded this quantity or material. */
  supplier?: Party;
  /** Unit Cost Micros — Supplier buy price per unit in millionths. 49000 = 0.049. */
  unit_cost_micros?: number;
}

export const LINE_ALLOCATION_APP_KEY = "aswathtestapp_6a67823a8fa7215710927dbc";

export type LineAllocationSchema = { 'line_allocation': LineAllocation };

/**
 * Field-level validation declared in Phoenix for `line_allocation`.
 * Use as DEFAULT UI constraints when building a form for this entity
 * (mark required fields, set maxLength / min / max, apply regex / oneOf).
 * Only fields that are required or carry a constraint are listed.
 */
export const LINE_ALLOCATION_FIELD_CONSTRAINTS = {
  id: { required: true },
} as const;
