// AUTO-GENERATED by scripts/fetch-entities.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/entity
// Tenant scope: see TENANT_ID used at generation time.

/**
 * Party
 * Every company/person the business deals with, recorded once.
 */
export interface Party {
  /** Id — PK */
  id: string;
  /** Kind — Discriminator: org or person */
  kind?: string;
  /** Legal Name — Registered legal entity name */
  legal_name?: string;
  /** Name — Display name of the party */
  name?: string;
  /** Status — Lifecycle status (active/inactive) */
  status?: string;
}

export const PARTY_APP_KEY = "aswathtestapp_6a67823a8fa7215710927dbc";

export type PartySchema = { 'party': Party };

/**
 * Field-level validation declared in Phoenix for `party`.
 * Use as DEFAULT UI constraints when building a form for this entity
 * (mark required fields, set maxLength / min / max, apply regex / oneOf).
 * Only fields that are required or carry a constraint are listed.
 */
export const PARTY_FIELD_CONSTRAINTS = {
  id: { required: true },
} as const;
