// AUTO-GENERATED by scripts/fetch-entities.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/entity
// Tenant scope: see TENANT_ID used at generation time.

import type { Party } from '@/types/entities/aswathtestapp_6a67823a8fa7215710927dbc/party';

/**
 * Pricing Template
 * Client-bound pricing rules: component-role margins, floor and scenario. Buy-side cost is converted to sale price with sale = buy / (1 - marginPct).
 */
export interface PricingTemplate {
  /** ID */
  id: string;
  /** Active */
  active?: boolean;
  /** Basis — cost_plus, msrp or wholesale */
  basis?: string;
  /** Client — FK -> Party. The buyer this template prices for. */
  client?: Party;
  /** Effective From */
  effective_from?: string;
  /** Effective To */
  effective_to?: string;
  /** Floor Bps — Minimum acceptable line margin in basis points. 800 = 8%. */
  floor_bps?: number;
  /** Model — markup_pct or flat_per_thousand */
  model?: string;
  /** Name */
  name?: string;
  /** Scenario — standard, rfp or premium */
  scenario?: string;
}

export const PRICING_TEMPLATE_APP_KEY = "aswathtestapp_6a67823a8fa7215710927dbc";

export type PricingTemplateSchema = { 'pricing_template': PricingTemplate };

/**
 * Field-level validation declared in Phoenix for `pricing_template`.
 * Use as DEFAULT UI constraints when building a form for this entity
 * (mark required fields, set maxLength / min / max, apply regex / oneOf).
 * Only fields that are required or carry a constraint are listed.
 */
export const PRICING_TEMPLATE_FIELD_CONSTRAINTS = {
  id: { required: true },
} as const;
