// AUTO-GENERATED by scripts/fetch-entities.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/entity
// Tenant scope: see TENANT_ID used at generation time.

import type { TqDefinition } from '@/types/entities/aswathtestapp_6a67823a8fa7215710927dbc/tq_definition';
import type { TqStateInstance } from '@/types/entities/aswathtestapp_6a67823a8fa7215710927dbc/tq_state_instance';
import type { TqSubTaskInstance } from '@/types/entities/aswathtestapp_6a67823a8fa7215710927dbc/tq_sub_task_instance';

/**
 * TQ Instance
 * [task-queue] Running header: definition, current sub-task, current status.
 */
export interface TqInstance {
  /** Id — PK */
  id: string;
  /** Assignee — N:1 -> platform user who owns this order end-to-end */
  assignee?: unknown;
  /** Created At */
  created_at?: string;
  /** Created By */
  created_by?: unknown;
  /** Current Status — N:1 -> current status */
  current_status?: TqStateInstance;
  /** Current Task — N:1 -> active sub-task */
  current_task?: TqSubTaskInstance;
  /** Last Modified At */
  last_modified_at?: string;
  /** Last Modified By */
  last_modified_by?: unknown;
  /** Sub Task History — 1:N -> sub-task history */
  sub_task_history?: TqSubTaskInstance[];
  /** TQ Definition — N:1 -> TQ Definition */
  tq_definition?: TqDefinition;
}

export const TQ_INSTANCE_APP_KEY = "aswathtestapp_6a67823a8fa7215710927dbc";

export type TqInstanceSchema = { 'tq_instance': TqInstance };

/**
 * Field-level validation declared in Phoenix for `tq_instance`.
 * Use as DEFAULT UI constraints when building a form for this entity
 * (mark required fields, set maxLength / min / max, apply regex / oneOf).
 * Only fields that are required or carry a constraint are listed.
 */
export const TQ_INSTANCE_FIELD_CONSTRAINTS = {
  id: { required: true },
} as const;
