// AUTO-GENERATED by scripts/fetch-entities.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/entity
// Tenant scope: see TENANT_ID used at generation time.

/**
 * TQ State Definition
 * [task-queue] An allowed state within a sub-task.
 */
export interface TqStateDefinition {
  /** Id — PK */
  id: string;
  /** Created At */
  created_at?: string;
  /** Created By */
  created_by?: unknown;
  /** Is Final — Ending state */
  is_final?: boolean;
  /** Is Initial — Entry state */
  is_initial?: boolean;
  /** Last Modified At */
  last_modified_at?: string;
  /** Last Modified By */
  last_modified_by?: unknown;
  /** State — State name */
  state?: string;
}

export const TQ_STATE_DEFINITION_APP_KEY = "aswathtestapp_6a67823a8fa7215710927dbc";

export type TqStateDefinitionSchema = { 'tq_state_definition': TqStateDefinition };

/**
 * Field-level validation declared in Phoenix for `tq_state_definition`.
 * Use as DEFAULT UI constraints when building a form for this entity
 * (mark required fields, set maxLength / min / max, apply regex / oneOf).
 * Only fields that are required or carry a constraint are listed.
 */
export const TQ_STATE_DEFINITION_FIELD_CONSTRAINTS = {
  id: { required: true },
} as const;
