/* eslint-disable */
// AUTO-GENERATED by scripts/fetch-application.ts - do not edit by hand.
// Source: Phoenix GET /api/internal/applications?name=<name>
export interface ApplicationRecord {
  id?: string;
  name?: string;
  label?: string;
  description?: string;
  app_definition_key?: string;
  tenant?: string;
  status?: string;
  created_date?: string;
  modified_date?: string;
  [key: string]: unknown;
}

export const APPLICATION: ApplicationRecord = {
  "id": "6a67823a8fa7215710927dc0",
  "created_date": "2026-07-27T16:07:22.39Z",
  "modified_date": "2026-07-27T16:07:22.912Z",
  "tenant": "giftcards",
  "name": "aswathtestapp",
  "label": "Aswath Test App",
  "app_definition_key": "aswathtestapp_6a67823a8fa7215710927dbc",
  "status": "started",
  "description": "Aswath Test App",
  "editable": true,
  "app_definition": "aswathtestapp__V0_0_1",
  "version": "0.0.1",
  "is_branch": false,
  "environment": "develop",
  "ui_type": "ai-first",
  "target_platform": "web"
} as const;
