/* eslint-disable */
// AUTO-GENERATED by scripts/fetch-tenant-refs.ts - do not edit by hand.
// Source: Phoenix /data/internal/query/org
// Tenant reference snapshot — regenerated on every workspace bootstrap.

/** One Orgs record (shape is tenant-defined; keys are open). */
export interface OrgsRecord { [key: string]: unknown }

/** All Orgs for this tenant (snapshot at bootstrap). */
export const ORGS: ReadonlyArray<OrgsRecord> = [];

export const ORGS_COUNT = 0;
