/* eslint-disable */
// AUTO-GENERATED by scripts/fetch-partner-modules.ts - do not edit by hand.
// Source: Phoenix /api/internal/component-definitions-all/partner_module_request
// Regenerated on every workspace bootstrap; stays in sync with
// src/types/partner-modules/*.ts.

export type PartnerModuleName = never;

export interface PartnerModuleSchema {}

export type PartnerModuleInputOf<_N extends PartnerModuleName> = never;
export type PartnerModuleOutputOf<_N extends PartnerModuleName> = never;
export type PartnerModuleAppKeyOf<_N extends PartnerModuleName> = never;
export type PartnerModuleCategoryOf<_N extends PartnerModuleName> = never;
