/* eslint-disable */
// AUTO-GENERATED by scripts/fetch-tenant-refs.ts - do not edit by hand.
// Source: Phoenix /api/internal/permission-groups
// Tenant reference snapshot — regenerated on every workspace bootstrap.

/** One Permission Groups record (shape is tenant-defined; keys are open). */
export interface PermissionGroupsRecord { [key: string]: unknown }

/** All Permission Groups for this tenant (snapshot at bootstrap). */
export const PERMISSION_GROUPS: ReadonlyArray<PermissionGroupsRecord> = [];

export const PERMISSION_GROUPS_COUNT = 0;
