/* eslint-disable */
// AUTO-GENERATED by scripts/fetch-tenant-refs.ts - do not edit by hand.
// Source: Phoenix /api/internal/roles
// Tenant reference snapshot — regenerated on every workspace bootstrap.

/** One Roles record (shape is tenant-defined; keys are open). */
export interface RolesRecord { [key: string]: unknown }

/** All Roles for this tenant (snapshot at bootstrap). */
export const ROLES: ReadonlyArray<RolesRecord> = [];

export const ROLES_COUNT = 0;
