/**
 * Fetches the deployed app's metadata for the configured tenant from the
 * Phoenix `/api/internal/applications?name={name}` endpoint (which returns
 * an ARRAY of matches — we take the first) and emits:
 *
 *   1. `<workspace>/src/types/catalogs/app.md`           — agent-facing reference card
 *   2. `<workspace>/src/types/app.generated.ts` — typed `APPLICATION` const
 *
 * Both are tenant-specific. Runtime code (DefaultLayout, theme.ts) reads
 * `APPLICATION.label` for branding so the cloned app shows the real name
 * instead of the starter's default "Codegen Starter" placeholder.
 *
 * Config (env-only, sourced from `codegen-starter/.env` or the process env):
 *   - PHOENIX_API_URL          e.g. https://jiffy.us.sandbox.phoenix.jiffy.ai
 *   - TENANT_ID                e.g. aiwithdata
 *   - APP_NAME (preferred)     the app slug used in the URL — e.g.
 *                              `advisorworkstation`. Falls back to APP_ID
 *                              (the existing deployed task-env name) for
 *                              backward-compat; both hold the slug, the
 *                              naming was inconsistent across teams.
 *   - FETCH_APPLICATION_OUT_DIR (optional) absolute path to write into.
 *                              Defaults to `<starter>/src/types`.
 *
 * Invocation:
 *   npm run fetch:application
 *   # or directly:
 *   npx tsx scripts/fetch-application.ts
 *
 * Soft-fails on missing env / non-2xx response (matches the rest of the
 * codegen scripts) and overwrites the two outputs with empty stubs so the
 * runtime still compiles. Worker boots either way.
 */

import {
  existsSync,
  mkdirSync,
  readFileSync,
  writeFileSync,
} from 'fs';
import { dirname, resolve } from 'path';
import { fileURLToPath } from 'url';

import { phoenixUrl, withAuth } from './lib/phoenix-http';

// =============================================================================
// .env loader (no `dotenv` dep — same pattern as fetch-entities, fetch-saved-
// queries, fetch-workflows, fetch-partner-modules so the four scripts stay in
// sync without a shared import)
// =============================================================================

function loadDotEnv(envPath: string): void {
  if (!existsSync(envPath)) return;
  const raw = readFileSync(envPath, 'utf8');
  for (const line of raw.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq <= 0) continue;
    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    if (process.env[key] === undefined) {
      process.env[key] = value;
    }
  }
}

// =============================================================================
// Application shape
// =============================================================================

/**
 * Wire shape of a single element in the array returned by
 * `GET /api/internal/applications?name={name}`. Documented from
 * the user-pasted example; we mirror the fields the runtime actually
 * uses (label, description, definition key, status) plus the ones useful
 * for the catalog markdown. Unknown extra fields on the response are
 * preserved on the typed const via an `[key: string]: unknown` index sig.
 */
export interface ApplicationRecord {
  id?: string;
  name?: string;
  label?: string;
  description?: string;
  app_definition_key?: string;
  tenant?: string;
  status?: string;
  created_date?: string;
  modified_date?: string;
  [key: string]: unknown;
}

// =============================================================================
// Renderers — pure helpers (exported for unit tests if added later)
// =============================================================================

/**
 * Render the markdown reference card the agent reads at session start.
 * Empty fields collapse to em-dashes so the agent can grep for missing
 * data without choking on `undefined`.
 */
export function renderApplicationMarkdown(
  app: ApplicationRecord | null,
): string {
  const header = [
    '<!-- AUTO-GENERATED by scripts/fetch-application.ts — do not edit by hand.',
    '     Source: GET /api/internal/applications?name=<name>. Regenerated on every workspace',
    '     bootstrap; reflects the deployed editor\'s tenant + application. -->',
    '',
    '# Application context',
    '',
  ].join('\n');

  if (!app) {
    return (
      header +
      '_No application metadata available. Either `PHOENIX_API_URL` /\n' +
      '`TENANT_ID` / `APP_NAME` were not set when the catalog was\n' +
      'regenerated, or the `/api/internal/applications?name={name}` endpoint returned\n' +
      'an error. Run `npm run fetch:application` to refresh._\n'
    );
  }

  const lines: string[] = [header];
  if (app.label) {
    lines.push(`# ${app.label}`);
    lines.push('');
  }
  if (app.description) {
    lines.push(`> ${app.description.replace(/\r?\n+/g, ' ').trim()}`);
    lines.push('');
  }
  lines.push('| Field | Value |');
  lines.push('|---|---|');
  const row = (field: string, value: unknown): void => {
    const v =
      typeof value === 'string' && value.length > 0
        ? `\`${value}\``
        : '—';
    lines.push(`| \`${field}\` | ${v} |`);
  };
  row('name', app.name);
  row('label', app.label);
  row('app_definition_key', app.app_definition_key);
  row('tenant', app.tenant);
  row('status', app.status);
  row('id', app.id);
  row('description', app.description);
  row('created_date', app.created_date);
  row('modified_date', app.modified_date);
  lines.push('');
  return lines.join('\n');
}

/**
 * Render the typed TS module. Runtime code reads `APPLICATION.label` for
 * branding, `APPLICATION.app_definition_key` for header injection, etc.
 *
 * When `app` is null (offline / fetch failed) we emit the stub so the
 * import doesn't break and `applyStoredTheme` etc. can fall back to
 * defaults.
 */
export function renderApplicationTs(app: ApplicationRecord | null): string {
  const header = [
    '/* eslint-disable */',
    '// AUTO-GENERATED by scripts/fetch-application.ts - do not edit by hand.',
    '// Source: Phoenix GET /api/internal/applications?name=<name>',
    '',
  ].join('\n');

  if (!app) {
    return (
      header +
      'export interface ApplicationRecord {\n' +
      '  id?: string;\n' +
      '  name?: string;\n' +
      '  label?: string;\n' +
      '  description?: string;\n' +
      '  app_definition_key?: string;\n' +
      '  tenant?: string;\n' +
      '  status?: string;\n' +
      '  created_date?: string;\n' +
      '  modified_date?: string;\n' +
      '  [key: string]: unknown;\n' +
      '}\n\n' +
      'export const APPLICATION: ApplicationRecord | null = null;\n'
    );
  }

  const json = JSON.stringify(app, null, 2);
  return (
    header +
    'export interface ApplicationRecord {\n' +
    '  id?: string;\n' +
    '  name?: string;\n' +
    '  label?: string;\n' +
    '  description?: string;\n' +
    '  app_definition_key?: string;\n' +
    '  tenant?: string;\n' +
    '  status?: string;\n' +
    '  created_date?: string;\n' +
    '  modified_date?: string;\n' +
    '  [key: string]: unknown;\n' +
    '}\n\n' +
    `export const APPLICATION: ApplicationRecord = ${json} as const;\n`
  );
}

// =============================================================================
// Disk helpers
// =============================================================================

function writeIfChanged(filePath: string, contents: string): boolean {
  if (existsSync(filePath)) {
    const existing = readFileSync(filePath, 'utf8');
    if (existing === contents) return false;
  }
  mkdirSync(dirname(filePath), { recursive: true });
  writeFileSync(filePath, contents);
  return true;
}

// =============================================================================
// API call
// =============================================================================

function applicationUrl(apiUrl: string, appName: string): string {
  const base = apiUrl.replace(/\/+$/, '');
  // Phoenix returns an ARRAY of matching applications from this endpoint.
  return phoenixUrl(`${base}/api/internal/applications?name=${encodeURIComponent(appName)}`);
}

async function fetchApplication(
  apiUrl: string,
  tenant: string,
  appName: string,
): Promise<ApplicationRecord | null> {
  const url = applicationUrl(apiUrl, appName);

  const res = await fetch(url, {
    method: 'GET',
    headers: withAuth({
      accept: 'application/json',
      'Content-Type': 'application/json',
      'X-Jiffy-Tenant': tenant,
    }),
  });

  if (!res.ok) {
    // Soft-fail: log and return null so the caller writes stubs and the rest of
    // the bootstrap continues (matches this script's documented behaviour and
    // the other fetchers). A non-2xx here must NOT abort the whole chain.
    const body = await res.text().catch(() => '');
    console.warn(
      `fetch-application: ${res.status} ${res.statusText} for ${url} — ` +
        `writing empty stub. ${body.slice(0, 200)}`,
    );
    return null;
  }

  const data = (await res.json()) as unknown;
  // `/api/internal/applications?name=` returns an array of matches; take
  // the first record. Tolerate a bare object too (defensive).
  const record = Array.isArray(data) ? data[0] : data;
  if (!record || typeof record !== 'object') {
    // No app matched (empty array) — soft-fail with a stub rather than throwing
    // and killing the bootstrap chain.
    console.warn(
      `fetch-application: no application named "${appName}" for tenant ` +
        `"${tenant}" (response was ${Array.isArray(data) ? 'an empty array' : typeof data}) — ` +
        `writing empty stub.`,
    );
    return null;
  }
  return record as ApplicationRecord;
}

// =============================================================================
// Main
// =============================================================================

interface RunOptions {
  envPath: string;
  outDir: string;
  catalogPath: string;
  tsPath: string;
}

async function run(opts: RunOptions): Promise<void> {
  loadDotEnv(opts.envPath);

  const apiUrl = process.env.PHOENIX_API_URL?.trim();
  const tenant = process.env.TENANT_ID?.trim();
  // `APP_NAME` is the preferred env; some deployed contexts still set
  // `APP_ID` (which holds the slug, not a UUID — the naming is legacy).
  const appName = (
    process.env.APP_NAME ??
    process.env.APP_ID ??
    ''
  ).trim();

  if (!apiUrl || !tenant || !appName) {
    const missing: string[] = [];
    if (!apiUrl) missing.push('PHOENIX_API_URL');
    if (!tenant) missing.push('TENANT_ID');
    if (!appName) missing.push('APP_NAME (or APP_ID)');
    console.log(
      `fetch-application: skipped — ${missing.join(', ')} not set. ` +
        `Add to .env and re-run \`npm run fetch:application\` to populate ` +
        `src/types/catalogs/app.md + src/types/app.generated.ts.`,
    );
    // PHX-4513: only seed empty stubs on first run — never clobber an
    // already-populated app.md / app.generated.ts when skipping for missing
    // creds (a credential-less refetch would otherwise reset the app label /
    // app_definition_key back to the starter defaults).
    mkdirSync(opts.outDir, { recursive: true });
    if (!existsSync(opts.catalogPath)) {
      writeIfChanged(opts.catalogPath, renderApplicationMarkdown(null));
    }
    if (!existsSync(opts.tsPath)) {
      writeIfChanged(opts.tsPath, renderApplicationTs(null));
    } else {
      console.log(
        `fetch-application: preserving existing ${opts.tsPath} / ${opts.catalogPath} ` +
          `(not overwriting with empty stubs).`,
      );
    }
    return;
  }

  console.log(
    `fetch-application: GET ${applicationUrl(apiUrl, appName)} (tenant=${tenant})`,
  );

  const app = await fetchApplication(apiUrl, tenant, appName);

  mkdirSync(opts.outDir, { recursive: true });
  const mdWritten = writeIfChanged(
    opts.catalogPath,
    renderApplicationMarkdown(app),
  );
  const tsWritten = writeIfChanged(opts.tsPath, renderApplicationTs(app));
  console.log(
    `fetch-application: ${app?.label ?? app?.name ?? '(no app — stub)'} → ` +
      `${opts.outDir} (md=${mdWritten ? 'written' : 'unchanged'}, ` +
      `ts=${tsWritten ? 'written' : 'unchanged'})`,
  );
}

// CLI entry
if (
  typeof process !== 'undefined' &&
  process.argv[1] &&
  process.argv[1] === fileURLToPath(import.meta.url)
) {
  const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
  const outDir = process.env.FETCH_APPLICATION_OUT_DIR
    ? resolve(process.env.FETCH_APPLICATION_OUT_DIR)
    : resolve(root, 'src/types');
  const catalogPath = resolve(outDir, 'catalogs/app.md');
  const tsPath = resolve(outDir, 'app.generated.ts');
  run({
    envPath: resolve(root, '.env'),
    outDir,
    catalogPath,
    tsPath,
  }).catch((err) => {
    console.error(err instanceof Error ? err.message : String(err));
    process.exit(1);
  });
}
